import {useSyncExternalStore, type ReactElement} from "react";
import type {ReviewCase} from "../../types";
import {addEditorialOutcomeNote, confirmEditorialOutcome, getOutcomeEvents, getOutcomesForCase, getOutcomeStoreVersion, importLegacyOutcomesForCase, reconcileOutcome, rejectEditorialOutcome, subscribeOutcomeStore} from "..";
import OutcomeStatusBadge from "./OutcomeStatusBadge";
import OutcomeTimeline from "./OutcomeTimeline";

export default function DecisionOutcomePanel({reviewCase}: {reviewCase: ReviewCase}): ReactElement | null {
  useSyncExternalStore(subscribeOutcomeStore, getOutcomeStoreVersion, getOutcomeStoreVersion);
  const records = getOutcomesForCase(reviewCase.id);
  if (!records.length && !reviewCase.resolutions.length) return null;
  function initialize(): void { importLegacyOutcomesForCase(reviewCase); }
  function feedback(kind: "confirm" | "reject" | "note", outcomeId: string): void { const actor = window.prompt("Identificador del editor:", "editor")?.trim(); if (!actor) return; const reason = window.prompt(kind === "note" ? "Nota auditable:" : "Motivo obligatorio:", "")?.trim(); if (!reason) return; if (kind === "confirm") confirmEditorialOutcome(outcomeId, actor, reason); else if (kind === "reject") rejectEditorialOutcome(outcomeId, actor, reason); else addEditorialOutcomeNote(outcomeId, actor, reason); }
  return <section className="review-subsection outcome-panel" aria-labelledby={`outcome-title-${reviewCase.id}`}>
    <p className="review-kicker">OUTCOME Y FEEDBACK · LEDGER LOCAL</p>
    <h4 className="review-subtitle" id={`outcome-title-${reviewCase.id}`}>Resultado real de las decisiones</h4>
    <p className="review-muted">El éxito técnico, estructural, editorial y operativo se evalúa por separado. Este panel no modifica documentos ni reejecuta operaciones.</p>
    {!records.length ? <div><p>No existe outcome para las resoluciones reales de este caso.</p><button className="review-button" type="button" onClick={initialize}>Inicializar desde resoluciones existentes</button></div> : <div className="outcome-records">{records.map((record) => { const events = getOutcomeEvents(record.id); return <article key={record.id} className="outcome-record"><header><div><h5>{record.decisionType} · {record.issueId}</h5><p>{record.id}</p></div><OutcomeStatusBadge label="General" status={record.currentStatus} /></header><div className="outcome-status-grid"><OutcomeStatusBadge label="Técnico" status={record.technicalStatus} /><OutcomeStatusBadge label="Estructural" status={record.structuralStatus} /><OutcomeStatusBadge label="Editorial" status={record.editorialStatus} /><OutcomeStatusBadge label="Operativo" status={record.operationalStatus} /></div><dl className="review-definition-grid"><dt>Entidad</dt><dd>{record.entityType ?? "No aplicable"}</dd><dt>Materialización</dt><dd>{record.materializationReference ?? "Sin referencia"}</dd><dt>Resume</dt><dd>{record.resumeReference ?? "Sin referencia"}</dd><dt>Documento</dt><dd>{record.documentReference ?? "Sin referencia"}</dd><dt>Actualizado</dt><dd>{new Date(record.updatedAt).toLocaleString("es-ES")}</dd></dl>{record.conflicts.map((conflict) => <p key={conflict} className="review-readonly-message">{conflict}</p>)}<div className="review-actions"><button className="review-button review-button-secondary" type="button" disabled={record.currentStatus === "superseded"} onClick={() => feedback("confirm", record.id)}>Confirmar editorialmente</button><button className="review-button review-button-danger" type="button" disabled={record.currentStatus === "superseded"} onClick={() => feedback("reject", record.id)}>Rechazar editorialmente</button><button className="review-button review-button-secondary" type="button" onClick={() => feedback("note", record.id)}>Añadir nota</button><button className="review-button review-button-secondary" type="button" onClick={() => reconcileOutcome(record.id)}>Reconciliar localmente</button></div><details><summary>Timeline ({events.length})</summary><OutcomeTimeline events={events} /></details><details><summary>Fingerprints y provenance</summary><dl className="review-definition-grid"><dt>Decision</dt><dd>{record.decisionFingerprint}</dd><dt>Context</dt><dd>{record.contextFingerprint}</dd><dt>Input</dt><dd>{record.inputFingerprint}</dd><dt>Evidence</dt><dd>{record.evidenceFingerprint}</dd><dt>Engine</dt><dd>{record.engineVersion}</dd></dl></details></article>; })}</div>}
  </section>;
}
