import {MAX_RETRIEVAL_EVENTS, MAX_RETRIEVAL_RESULTS, RETRIEVAL_STORAGE_KEY} from "./constants";
import type {RetrievalLedger} from "./types";
import {validateRetrievalLedger} from "./validation";
export type RetrievalRepository = {load(): RetrievalLedger; save(value: RetrievalLedger): void};
export const emptyRetrievalLedger = (): RetrievalLedger => ({schemaVersion: 1, queries: [], results: [], events: []});
export function migrateRetrievalLedger(value: unknown): RetrievalLedger { if (!value || typeof value !== "object") return emptyRetrievalLedger(); const item = value as Partial<RetrievalLedger>; if (item.schemaVersion !== 1 || !Array.isArray(item.queries) || !Array.isArray(item.results) || !Array.isArray(item.events)) return emptyRetrievalLedger(); const ledger = item as RetrievalLedger; return validateRetrievalLedger(ledger).valid ? ledger : emptyRetrievalLedger(); }
export function createMemoryRetrievalRepository(initial = emptyRetrievalLedger()): RetrievalRepository & {snapshot(): RetrievalLedger} { let value = structuredClone(initial); return {load: () => structuredClone(value), save: (next) => { value = structuredClone(next); }, snapshot: () => structuredClone(value)}; }
function boundLedger(value: RetrievalLedger): RetrievalLedger { const results: RetrievalLedger["results"] = []; let count = 0; [...value.results].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, MAX_RETRIEVAL_RESULTS).forEach((result) => { const related = value.events.filter((item) => item.retrievalId === result.id).length; if (count + related <= MAX_RETRIEVAL_EVENTS) { results.push(result); count += related; } }); const ids = new Set(results.map((item) => item.id)); const events = value.events.filter((item) => ids.has(item.retrievalId)); const queryIds = new Set(results.map((item) => item.query.id)); const queries = value.queries.filter((item) => queryIds.has(item.id)); return {schemaVersion: 1, queries, results, events}; }
export function createLocalStorageRetrievalRepository(): RetrievalRepository { return {load() { if (typeof window === "undefined") return emptyRetrievalLedger(); try { const raw = window.localStorage.getItem(RETRIEVAL_STORAGE_KEY); return raw ? migrateRetrievalLedger(JSON.parse(raw) as unknown) : emptyRetrievalLedger(); } catch { return emptyRetrievalLedger(); } }, save(value) { if (typeof window === "undefined") return; const validation = validateRetrievalLedger(value); if (!validation.valid) throw new Error(validation.errors.join(" ")); const bounded = boundLedger(value); const boundedValidation = validateRetrievalLedger(bounded); if (!boundedValidation.valid) throw new Error(boundedValidation.errors.join(" ")); window.localStorage.setItem(RETRIEVAL_STORAGE_KEY, JSON.stringify(bounded)); }}; }
export const localStorageRetrievalRepository = createLocalStorageRetrievalRepository();
