import {getDecisionMemories, getMemoryClusters} from "../memory";
import {hashRetrievalValue} from "./normalization";
import {RETRIEVAL_SCORING_VERSION, RETRIEVAL_SCHEMA_VERSION} from "./constants";
import {localStorageRetrievalRepository, type RetrievalRepository} from "./persistence";
import {retrieveRelevantMemoriesPure} from "./retrieveRelevantMemories";
import type {RetrievalEvent, RetrievalEventType, RetrievalLedger, RetrievalQuery, RetrievalResult} from "./types";
import {validateRetrievalLedger} from "./validation";
let repository: RetrievalRepository = localStorageRetrievalRepository; let version = 0; const listeners = new Set<() => void>(); const emit = () => { version += 1; listeners.forEach((item) => item()); };
const save = (ledger: RetrievalLedger) => { repository.save(ledger); emit(); };
const event = (result: RetrievalResult, type: RetrievalEventType, payload: Record<string, unknown>, suffix: string = type): RetrievalEvent => ({schemaVersion: 1, id: `retrieval-event:${hashRetrievalValue([result.id, suffix])}`, retrievalId: result.id, type, timestamp: result.createdAt, payload, idempotencyKey: `${result.id}:${suffix}`, actor: {type: "system"}, module: "review.retrieval", engineVersion: result.engineVersion, scoringVersion: result.scoringVersion, provenance: "local_retrieval"});
export const subscribeRetrievalStore = (listener: () => void) => { listeners.add(listener); return () => listeners.delete(listener); };
export const getRetrievalStoreVersion = () => version;
export const getRetrievalResults = () => repository.load().results.sort((a, b) => b.createdAt.localeCompare(a.createdAt) || a.id.localeCompare(b.id));
export const getRetrievalResult = (id: string) => repository.load().results.find((item) => item.id === id);
export const getRetrievalResultsForCase = (caseId: string) => getRetrievalResults().filter((item) => item.query.caseId === caseId);
export const getRetrievalResultsForIssue = (issueId: string) => getRetrievalResults().filter((item) => item.query.issueId === issueId);
export const getLatestRetrievalForIssue = (issueId: string) => getRetrievalResultsForIssue(issueId)[0];
export function persistRetrieval(query: RetrievalQuery): RetrievalResult { const ledger = repository.load(); const result = retrieveRelevantMemoriesPure(query, getDecisionMemories(), getMemoryClusters()); const existing = ledger.results.find((item) => item.id === result.id); if (existing) return existing; const events = [event(result, "retrieval_started", {}), event(result, "query_built", {queryFingerprint: query.queryFingerprint}), event(result, "candidates_generated", {count: result.candidates.length}), ...result.candidates.map((item) => event(result, item.candidateStatus === "excluded" ? "candidate_excluded" : "candidate_included", {memoryId: item.memoryId, score: item.finalScore}, `${item.candidateStatus}:${item.memoryId}`)), ...result.negativeEvidence.map((item) => event(result, "negative_evidence_detected", {memoryId: item.memoryId}, `negative:${item.memoryId}`)), ...result.contradictions.map((item, index) => event(result, "contradiction_detected", {type: item.type, memoryIds: item.memoryIds}, `contradiction:${index}`)), event(result, "retrieval_completed", {status: result.status})]; result.eventIds = events.map((item) => item.id); save({...ledger, queries: [...ledger.queries, query], results: [...ledger.results, result], events: [...ledger.events, ...events]}); return result; }
export function reconcileDecisionRetrieval(id?: string) { const ledger = repository.load(); const targets = id ? ledger.results.filter((item) => item.id === id) : ledger.results; if (id && !targets.length) throw new Error("retrieval_not_found"); const memories = getDecisionMemories(); const clusters = getMemoryClusters(); const currentFingerprint = `rml1:${hashRetrievalValue({memories: memories.map((item) => [item.id, item.updatedAt, item.memoryFingerprint, item.status]).sort(), clusters: clusters.map((item) => [item.id, item.updatedAt, item.status, item.memoryIds]).sort()})}`; let changed = false; const results = ledger.results.map((result) => { if (!targets.some((item) => item.id === result.id)) return result; const reasons = [...result.candidates.filter((item) => !memories.some((memory) => memory.id === item.memoryId)).map((item) => `Memoria ${item.memoryId} ya no existe.`)]; if (result.memoryLedgerFingerprint !== currentFingerprint) reasons.push("El ledger de memorias o clústeres cambió."); if (result.scoringVersion !== RETRIEVAL_SCORING_VERSION) reasons.push("La versión de scoring cambió."); if (result.query.queryVersion !== 1) reasons.push("La versión de query cambió."); if (result.schemaVersion !== RETRIEVAL_SCHEMA_VERSION) reasons.push("La versión de schema cambió."); if (result.eventIds.some((eventId) => !ledger.events.some((item) => item.id === eventId))) reasons.push("Falta un evento histórico referenciado."); if (reasons.length && !result.stale) changed = true; return reasons.length ? {...result, stale: true, staleReasons: [...new Set(reasons)]} : result; }); const extraEvents = results.filter((item) => item.stale && !ledger.results.find((old) => old.id === item.id)?.stale).map((item) => event(item, "retrieval_marked_stale", {reasons: item.staleReasons}, "stale")); if (changed) save({...ledger, results, events: [...ledger.events, ...extraEvents]}); return {changed, results: id ? results.filter((item) => item.id === id) : results}; }
export const getRelevantCandidates = (id: string) => getRetrievalResult(id)?.includedCandidates ?? [];
export const getNegativeEvidence = (id: string) => getRetrievalResult(id)?.negativeEvidence ?? [];
export const getContradictions = (id: string) => getRetrievalResult(id)?.contradictions ?? [];
export const getExcludedCandidates = (id: string) => getRetrievalResult(id)?.excludedCandidates ?? [];
export const getStaleRetrievals = () => getRetrievalResults().filter((item) => item.stale);
export const getRetrievalDiagnostics = (id: string) => { const result = getRetrievalResult(id); return result ? {status: result.status, stale: result.stale, limitations: result.limitations, eventCount: result.eventIds.length} : undefined; };
export const validateDecisionRetrievalStore = () => validateRetrievalLedger(repository.load());
export const exportDecisionRetrieval = () => structuredClone(repository.load());
export function clearDecisionRetrievalHistory(confirm: string) { if (confirm !== "CLEAR_RETRIEVAL_HISTORY") throw new Error("explicit_confirmation_required"); save({schemaVersion: 1, queries: [], results: [], events: []}); }
export function addRetrievalNote(id: string, actorId: string, note: string) { if (!actorId.trim() || !note.trim()) throw new Error("actor_and_note_required"); const ledger = repository.load(); const result = ledger.results.find((item) => item.id === id); if (!result) throw new Error("retrieval_not_found"); const created = {...event({...result, createdAt: new Date().toISOString()}, "retrieval_note_added", {note}, `note:${result.eventIds.length}`), actor: {type: "human" as const, id: actorId}}; const results = ledger.results.map((item) => item.id === id ? {...item, eventIds: [...item.eventIds, created.id]} : item); save({...ledger, results, events: [...ledger.events, created]}); return created; }
export function setRetrievalRepositoryForTests(next: RetrievalRepository) { const previous = repository; repository = next; emit(); return () => { repository = previous; emit(); }; }
