import type {ReviewCase, ReviewIssue, ReviewJsonObject, ReviewJsonValue, ReviewResolution} from "../types";

export type InvestigationSourceType = "local_case" | "existing_analysis" | "original_article" | "sanity_read";
export type InvestigationErrorCode = "source_unavailable" | "source_timeout" | "invalid_source_result" | "investigation_not_supported" | "insufficient_evidence" | "ambiguous_identity" | "conflicting_evidence" | "unsafe_prepared_entity" | "validation_failed" | "case_not_found" | "issue_not_found" | "invalid_state" | "unknown_error";
export type InvestigationTarget = {caseId: string; issueId: string; producer: string; issueType: string; field?: string; mentionedLabel?: string; entityType?: string};
export type InvestigationPlanStep = {id: string; source: InvestigationSourceType; strategy: string; required: boolean; timeoutMs?: number; query?: ReviewJsonObject; reason: string};
export type InvestigationPlan = {caseId: string; issueId: string; steps: InvestigationPlanStep[]; generatedAt: string; version: number};
export type InvestigationEvidence = {id: string; source: string; sourceType: string; reliability: number; label: string; value?: ReviewJsonValue; entityType?: string; entityId?: string; canonicalUrl?: string; excerpt?: string; observedAt: string; revision?: string; reasons: string[]; warnings: string[]};
export type InvestigationSourceError = {code: InvestigationErrorCode; message: string; sourceType: string};
export type InvestigationSourceResult = {evidence: InvestigationEvidence[]; warnings: string[]; errors: InvestigationSourceError[]};
export type SanityEntityCandidate = {id: string; entityType: string; name: string; aliases?: string[]; slug?: string; disciplineIds?: string[]; organizationIds?: string[]; eventIds?: string[]; revision?: string};
export type SanityRelatedContent = {id: string; title: string; names?: string[]; sourceUrl?: string; publishedAt?: string};
export type SanityInvestigationReader = {findEntities(input: {entityType: string; names: string[]; disciplineId?: string; organizationId?: string; limit?: number}): Promise<SanityEntityCandidate[]>; findRelatedContent(input: {names: string[]; sourceUrl?: string; limit?: number}): Promise<SanityRelatedContent[]>};
export type InvestigationExecutionContext = {caseData: ReviewCase; issue: ReviewIssue; target: InvestigationTarget; now: string};
export type InvestigationSourceAdapter = {id: string; sourceType: InvestigationSourceType; investigate(step: InvestigationPlanStep, context: InvestigationExecutionContext): Promise<InvestigationSourceResult>};
export type InvestigationConclusion = {issueId: string; status: "resolved_existing_entity" | "prepared_new_entity" | "resolved_value" | "needs_more_evidence" | "conflict" | "rejected"; confidence: number; proposedResolution?: ReviewResolution; proposedEntity?: {entityType: string; draft: ReviewJsonObject; identityKey: string}; evidence: InvestigationEvidence[]; reasoningSummary: string; alternativesRejected: Array<{label: string; entityId?: string; reason: string}>; warnings: string[]; validation: {valid: boolean; errors: string[]}; generatedAt: string};
export type RunAutonomousInvestigationOptions = {dryRun?: boolean; issueIds?: string[]; minimumConfidence?: number; allowPreparedEntities?: boolean; now?: () => string};
export type AutonomousInvestigationResult = {caseId: string; status: "completed" | "partially_completed" | "needs_more_evidence" | "failed"; conclusions: InvestigationConclusion[]; plans: InvestigationPlan[]; investigatedIssueCount: number; resolvedExistingCount: number; preparedEntityCount: number; resolvedValueCount: number; pendingCount: number; conflictCount: number; failedCount: number; sourcesUsed: string[]; warnings: string[]; generatedAt: string; dryRun: boolean; appliedIssueIds: string[]};
