import type {DecisionOutcomeRecord} from "../outcomes";
import {getOutcomeEvents, getOutcomeRecords} from "../outcomes";
import {MEMORY_ENGINE_VERSION} from "./constants";
import {buildClusterFingerprint, buildMemoryFingerprint, hashMemoryValue} from "./fingerprints";
import {appendMemoryEvent, getDecisionMemories, insertDecisionMemory} from "./memoryStore";
import {calculateIndividualConfidence, evaluateMemoryCompatibility, evaluateOutcomeMemoryEligibility} from "./policy";
import type {DecisionMemoryRecord, MemoryImportResult} from "./types";

export function buildDecisionMemoryFromOutcome(outcome: DecisionOutcomeRecord): DecisionMemoryRecord | undefined {
  const eligibility = evaluateOutcomeMemoryEligibility(outcome); if (!eligibility.eligible || !eligibility.decision) return undefined;
  const normalizedPattern = {producer: outcome.producer, entityType: outcome.entityType ?? "unknown", issueType: outcome.issueType, decisionType: outcome.decisionType, decisionFingerprint: outcome.decisionFingerprint};
  const clusterFingerprint = buildClusterFingerprint(normalizedPattern); const memoryFingerprint = buildMemoryFingerprint({...normalizedPattern, editorialDecision: eligibility.decision, evidenceFingerprint: outcome.evidenceFingerprint}); const createdAt = outcome.confirmedAt ?? outcome.updatedAt;
  const confidence = calculateIndividualConfidence(outcome, eligibility.decision); const compatibility = evaluateMemoryCompatibility(outcome); const reuseBlockedReasons = eligibility.decision === "rejected" ? ["La decisión fue rechazada editorialmente."] : ["5D no autoriza reutilización automática; requiere evaluación humana futura."];
  return {schemaVersion: 1, memorySchemaVersion: 1, engineVersion: MEMORY_ENGINE_VERSION, fingerprintVersion: 1, id: `memory:${hashMemoryValue([outcome.id, memoryFingerprint])}`, outcomeId: outcome.id, caseId: outcome.caseId, issueId: outcome.issueId, resolutionId: outcome.resolutionId, producer: outcome.producer, source: outcome.source, entityType: outcome.entityType, issueType: outcome.issueType, decisionType: outcome.decisionType, editorialDecision: eligibility.decision, status: outcome.currentStatus === "superseded" ? "superseded" : eligibility.decision, reusePolicy: eligibility.decision === "rejected" ? "never" : "manual_only", reusable: eligibility.decision === "confirmed" && compatibility.status === "compatible", reuseBlockedReasons, decisionFingerprint: outcome.decisionFingerprint, contextFingerprint: outcome.contextFingerprint, inputFingerprint: outcome.inputFingerprint, evidenceFingerprint: outcome.evidenceFingerprint, memoryFingerprint, clusterFingerprint, normalizedPattern, technicalOutcome: outcome.technicalStatus, structuralOutcome: outcome.structuralStatus, editorialOutcome: outcome.editorialStatus, operationalOutcome: outcome.operationalStatus, confidence, confidenceScore: confidence.score, confidenceLevel: confidence.level, confidenceReason: confidence.reasons.join(" "), evidenceCount: outcome.eventIds.length, confirmationCount: eligibility.decision === "confirmed" ? 1 : 0, rejectionCount: eligibility.decision === "rejected" ? 1 : 0, contradictionCount: 0, distinctCaseCount: 1, distinctSourceCount: 1, distinctProducerCount: 1, compatibility, compatibilityStatus: compatibility.status, compatibleSchemaVersions: compatibility.status === "compatible" ? [outcome.reviewSchemaVersion] : [], compatibleEngineVersions: compatibility.status === "compatible" ? [outcome.engineVersion] : [], compatibleProducers: compatibility.status === "compatible" ? [outcome.producer] : [], incompatibilityReasons: compatibility.status === "compatible" ? [] : compatibility.reasons, clusterId: clusterFingerprint, clusterStatus: "emerging", provenance: {outcomeSchemaVersion: outcome.schemaVersion, outcomeEngineVersion: outcome.engineVersion, reviewSchemaVersion: outcome.reviewSchemaVersion, outcomeEventIds: [...outcome.eventIds]}, createdBy: "review.memory", createdFrom: "outcome_observer", imported: false, migrated: false, sourceOutcomeEventIds: [...outcome.eventIds], evidence: [{kind: "outcome", value: outcome.id}, {kind: "fingerprint", value: outcome.evidenceFingerprint}], notes: [], createdAt, updatedAt: createdAt, supersededBy: outcome.supersededBy, eventIds: []};
}
export function createMemoryFromOutcome(outcome: DecisionOutcomeRecord, actor: "system" | "legacy_import" = "system") { const built = buildDecisionMemoryFromOutcome(outcome); if (!built) return {eligible: false, created: false}; const stable = {...built, id: `memory:${hashMemoryValue([outcome.id, outcome.decisionFingerprint, outcome.schemaVersion, outcome.reviewSchemaVersion])}`}; const prepared = actor === "legacy_import" ? {...stable, createdFrom: "outcome_import" as const, imported: true} : stable; const insertion = insertDecisionMemory(prepared, {type: actor}); return {eligible: true, created: insertion.created, record: insertion.record}; }
export function synchronizeMemoryFromOutcome(outcome: DecisionOutcomeRecord) { const built = buildDecisionMemoryFromOutcome(outcome); const result = createMemoryFromOutcome(outcome); if (!result.eligible || !result.record || !built) return result; const type = outcome.currentStatus === "superseded" ? "memory_superseded" : outcome.editorialStatus === "rejected" ? "memory_rejected" : "memory_confirmed"; appendMemoryEvent(result.record.id, type, `Sincronización secundaria desde outcome ${outcome.id}.`, {type: "system"}, `outcome-sync:${outcome.id}:${outcome.updatedAt}:${type}`, {memoryFingerprint: built.memoryFingerprint, evidenceFingerprint: built.evidenceFingerprint, editorialOutcome: built.editorialOutcome, reusePolicy: built.reusePolicy, reusable: built.reusable, reuseBlockedReasons: built.reuseBlockedReasons, ...(outcome.currentStatus === "superseded" ? {replacementMemoryId: outcome.supersededBy ?? "unknown"} : {})}); return result; }
export function safelyObserveOutcomeForMemory(outcome: DecisionOutcomeRecord): void { if (typeof window === "undefined") return; try { synchronizeMemoryFromOutcome(outcome); } catch (error) { console.warn("Decision memory observer failed without affecting the outcome.", error); } }
export function importExistingOutcomesToMemory(caseId?: string): MemoryImportResult { const outcomes = getOutcomeRecords().filter((item) => !caseId || item.caseId === caseId); const result: MemoryImportResult = {eligible: 0, created: 0, updated: 0, skipped: 0, memoryIds: []}; outcomes.forEach((outcome) => { const eligible = evaluateOutcomeMemoryEligibility(outcome).eligible; if (!eligible) { result.skipped += 1; return; } result.eligible += 1; const created = createMemoryFromOutcome(outcome, "legacy_import"); if (created.record) result.memoryIds.push(created.record.id); if (created.created) result.created += 1; else result.updated += 1; }); return result; }
export function reconcileMemory(memoryId: string) { const memory = getDecisionMemories().find((item) => item.id === memoryId); if (!memory) throw new Error("memory_not_found"); const outcome = getOutcomeRecords().find((item) => item.id === memory.outcomeId); const findings: string[] = []; if (!outcome) findings.push("Outcome de origen no disponible."); else { if (outcome.decisionFingerprint !== memory.decisionFingerprint) findings.push("La huella de decisión cambió."); if (outcome.currentStatus === "superseded" && memory.status !== "superseded") synchronizeMemoryFromOutcome(outcome); }
  appendMemoryEvent(memoryId, "memory_reconciled", findings.length ? findings.join(" ") : "Memoria coherente con su outcome de origen.", {type: "reconciliation"}, `memory-reconcile:${memoryId}:${hashMemoryValue(findings)}`); return {memoryId, changed: findings.length > 0, findings}; }
export function reconcileAllMemories() { return getDecisionMemories().map((item) => reconcileMemory(item.id)); }
export const reconcileDecisionMemory = (memoryId?: string) => memoryId ? reconcileMemory(memoryId) : reconcileAllMemories();
export const importDecisionMemoriesFromOutcomes = importExistingOutcomesToMemory;
export function getOutcomeSourceEvents(outcomeId: string) { return getOutcomeEvents(outcomeId); }
