import type {
  ContentTypeDefinition,
  ContentTypeId,
  ContentTypeOption,
  SchemaFieldDefinition,
  SupportEntityDefinition,
} from "../types";

const commonSlugField = (sourceLabel: string): SchemaFieldDefinition => ({
  name: "slug",
  label: "Slug",
  kind: "slug",
  sanityType: "slug",
  description: `Se genera a partir de ${sourceLabel} y debe terminar guardándose como { current: string }.`,
  required: true,
  validations: [{ type: "required", value: true }],
});

export const contentTypes: ContentTypeDefinition[] = [
  {
    id: "noticia",
    label: "Noticia",
    description:
      "Documento editorial de actualidad con cuerpo principal en Portable Text y relaciones opcionales a evento, organización y luchadores.",
    supportsImageGeneration: true,
    hasSlug: true,
    references: ["disciplina", "organizacion", "luchador", "evento"],
    schemaFields: [
      {
        name: "titulo",
        label: "Título",
        kind: "string",
        sanityType: "string",
        required: true,
        description: "Título principal de la noticia.",
        validations: [
          { type: "required", value: true },
          { type: "min", value: 8 },
          { type: "max", value: 160 },
        ],
      },
      commonSlugField("título"),
      {
        name: "imagenPrincipal",
        label: "Imagen principal",
        kind: "image",
        sanityType: "image",
        required: false,
        description: "Imagen principal opcional de la noticia.",
      },
      {
        name: "extracto",
        label: "Extracto",
        kind: "text",
        sanityType: "text",
        required: true,
        rows: 3,
        description: "Resumen corto para listados, tarjetas y SEO editorial.",
        validations: [
          { type: "required", value: true },
          { type: "min", value: 20 },
        ],
      },
      {
        name: "contenido",
        label: "Contenido",
        kind: "portableText",
        sanityType: "array<block>",
        required: true,
        description: "Cuerpo principal de la noticia en formato Portable Text.",
        validations: [
          { type: "required", value: true },
          { type: "min", value: 1 },
        ],
      },
      {
        name: "fechaPublicacion",
        label: "Fecha de publicación",
        kind: "datetime",
        sanityType: "datetime",
        required: true,
        description: "Fecha real de publicación del documento.",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "disciplina",
        label: "Disciplina",
        kind: "reference",
        sanityType: "reference",
        required: true,
        referenceTo: "disciplina",
        description: "Referencia obligatoria a la disciplina.",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "organizacionRelacionada",
        label: "Organización relacionada",
        kind: "reference",
        sanityType: "reference",
        required: false,
        referenceTo: "organizacion",
        description: "Organización principal vinculada a la noticia, si aplica.",
      },
      {
        name: "luchadoresRelacionados",
        label: "Luchadores relacionados",
        kind: "referenceArray",
        sanityType: "array<reference>",
        required: false,
        referenceTo: "luchador",
        description: "Luchadores protagonistas o mencionados de forma relevante.",
        validations: [{ type: "unique", value: true }],
      },
      {
        name: "eventoRelacionado",
        label: "Evento relacionado",
        kind: "reference",
        sanityType: "reference",
        required: false,
        referenceTo: "evento",
        description: "Evento principal asociado a la noticia, si existe.",
      },
      {
        name: "destacada",
        label: "Destacada",
        kind: "boolean",
        sanityType: "boolean",
        required: true,
        description: "Marca si la noticia debe tratarse como destacada.",
        validations: [{ type: "required", value: true }],
      },
    ],
    auxiliaryInputs: [
      {
        name: "anguloEditorial",
        label: "Ángulo editorial",
        kind: "text",
        rows: 3,
        description: "Enfoque principal con el que se quiere contar la noticia.",
      },
      {
        name: "hechoPrincipal",
        label: "Hecho principal",
        kind: "text",
        rows: 3,
        description: "Qué ha ocurrido exactamente o cuál es el dato clave.",
      },
      {
        name: "contextoPrevio",
        label: "Contexto previo",
        kind: "text",
        rows: 4,
        description: "Antecedentes relevantes para que la IA no escriba en vacío.",
      },
      {
        name: "tono",
        label: "Tono",
        kind: "string",
        description: "Ejemplo: informativo, analítico, directo, editorial.",
      },
      {
        name: "seoObjetivo",
        label: "Objetivo SEO",
        kind: "string",
        description: "Keyword o intención de búsqueda principal.",
      },
      {
        name: "protagonistasTexto",
        label: "Protagonistas en texto",
        kind: "text",
        rows: 2,
        description:
          "Ayuda editorial libre para que la IA entienda quién pesa en la pieza.",
      },
      {
        name: "instruccionesRedaccion",
        label: "Instrucciones de redacción",
        kind: "text",
        rows: 4,
        description: "Instrucciones especiales para el borrador.",
      },
    ],
  },
  {
    id: "evento",
    label: "Evento",
    description:
      "Ficha editorial de evento con relaciones obligatorias a organización y disciplina, y estado controlado por enum real.",
    supportsImageGeneration: true,
    hasSlug: true,
    references: ["organizacion", "disciplina"],
    schemaFields: [
      {
        name: "nombre",
        label: "Nombre",
        kind: "string",
        sanityType: "string",
        required: true,
        description: "Nombre oficial del evento.",
        validations: [
          { type: "required", value: true },
          { type: "min", value: 3 },
          { type: "max", value: 140 },
        ],
      },
      commonSlugField("nombre"),
      {
        name: "organizacion",
        label: "Organización",
        kind: "reference",
        sanityType: "reference",
        required: true,
        referenceTo: "organizacion",
        description: "Organización obligatoria del evento.",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "disciplina",
        label: "Disciplina",
        kind: "reference",
        sanityType: "reference",
        required: true,
        referenceTo: "disciplina",
        description: "Disciplina obligatoria del evento.",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "fecha",
        label: "Fecha",
        kind: "datetime",
        sanityType: "datetime",
        required: true,
        description: "Fecha y hora real del evento.",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "horaLocal",
        label: "Hora local",
        kind: "string",
        sanityType: "string",
        required: false,
        description: "Ejemplo: 22:00 o 04:00 (hora peninsular española).",
        validations: [{ type: "max", value: 60 }],
      },
      {
        name: "ciudad",
        label: "Ciudad",
        kind: "string",
        sanityType: "string",
        required: false,
        validations: [{ type: "max", value: 100 }],
      },
      {
        name: "pais",
        label: "País",
        kind: "string",
        sanityType: "string",
        required: false,
        validations: [{ type: "max", value: 100 }],
      },
      {
        name: "recinto",
        label: "Recinto",
        kind: "string",
        sanityType: "string",
        required: false,
        validations: [{ type: "max", value: 140 }],
      },
      {
        name: "cartelPrincipal",
        label: "Cartel principal",
        kind: "string",
        sanityType: "string",
        required: false,
        description: "Ejemplo: Topuria vs Holloway.",
        validations: [{ type: "max", value: 140 }],
      },
      {
        name: "dondeVer",
        label: "Dónde ver",
        kind: "string",
        sanityType: "string",
        required: false,
        validations: [{ type: "max", value: 180 }],
      },
      {
        name: "descripcionCorta",
        label: "Descripción corta",
        kind: "text",
        sanityType: "text",
        required: false,
        rows: 3,
        validations: [{ type: "max", value: 280 }],
      },
      {
        name: "descripcion",
        label: "Descripción editorial",
        kind: "text",
        sanityType: "text",
        required: false,
        rows: 8,
        description:
          "Texto principal del evento: contexto, interés del show, protagonistas, cartelera y lectura editorial.",
        validations: [
          { type: "min", value: 20 },
          { type: "max", value: 3000 },
        ],
      },
      {
        name: "notas",
        label: "Notas adicionales",
        kind: "text",
        sanityType: "text",
        required: false,
        rows: 4,
        validations: [{ type: "max", value: 1200 }],
      },
      {
        name: "imagen",
        label: "Imagen",
        kind: "image",
        sanityType: "image",
        required: true,
        description: "Imagen principal del evento.",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "estado",
        label: "Estado",
        kind: "string",
        sanityType: "string",
        required: true,
        description: "Estado editorial real permitido por el schema.",
        options: [
          { label: "Próximo", value: "proximo" },
          { label: "Celebrado", value: "celebrado" },
          { label: "Cancelado", value: "cancelado" },
        ],
        validations: [{ type: "required", value: true }],
      },
    ],
    auxiliaryInputs: [
      {
        name: "tipoEvento",
        label: "Tipo de evento",
        kind: "string",
        description: "Ejemplo: PPV, Fight Night, velada, torneo, cartel local.",
      },
      {
        name: "importanciaEditorial",
        label: "Importancia editorial",
        kind: "text",
        rows: 3,
        description: "Por qué merece cobertura y qué peso tiene.",
      },
      {
        name: "combateEstelarTexto",
        label: "Combate estelar en texto",
        kind: "string",
        description: "Apoyo para que la IA entienda el gancho principal.",
      },
      {
        name: "contextoCartelera",
        label: "Contexto de cartelera",
        kind: "text",
        rows: 4,
        description: "Contexto narrativo de la cartelera y del momento del evento.",
      },
      {
        name: "clavesNarrativas",
        label: "Claves narrativas",
        kind: "text",
        rows: 4,
        description: "Puntos que la IA debe enfatizar.",
      },
      {
        name: "publicoObjetivo",
        label: "Público objetivo",
        kind: "string",
        description: "Ejemplo: fan hardcore, lector generalista, SEO informativo.",
      },
      {
        name: "tono",
        label: "Tono",
        kind: "string",
        description: "Tono deseado para la redacción del evento.",
      },
    ],
  },
  {
    id: "luchador",
    label: "Luchador",
    description:
      "Perfil editorial de luchador con referencias obligatorias a disciplina y organización, y reglas condicionales para destacado en home.",
    supportsImageGeneration: true,
    hasSlug: true,
    references: ["disciplina", "organizacion", "categoriaPeso"],
    schemaFields: [
      {
        name: "nombre",
        label: "Nombre",
        kind: "string",
        sanityType: "string",
        required: true,
        validations: [
          { type: "required", value: true },
          { type: "min", value: 2 },
          { type: "max", value: 120 },
        ],
      },
      commonSlugField("nombre"),
      {
        name: "apodo",
        label: "Apodo",
        kind: "string",
        sanityType: "string",
        required: false,
        validations: [{ type: "max", value: 120 }],
      },
      {
        name: "imagen",
        label: "Imagen",
        kind: "image",
        sanityType: "image",
        required: false,
        description: "Imagen opcional del luchador.",
      },
      {
        name: "nacionalidad",
        label: "Nacionalidad",
        kind: "string",
        sanityType: "string",
        required: false,
        validations: [{ type: "max", value: 80 }],
      },
      {
        name: "record",
        label: "Récord",
        kind: "string",
        sanityType: "string",
        required: false,
        description: "Ejemplo: 27-3-0.",
        validations: [{ type: "max", value: 40 }],
      },
      {
        name: "disciplina",
        label: "Disciplina",
        kind: "reference",
        sanityType: "reference",
        required: true,
        referenceTo: "disciplina",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "organizacion",
        label: "Organización",
        kind: "reference",
        sanityType: "reference",
        required: true,
        referenceTo: "organizacion",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "categoriaPeso",
        label: "Categoría de peso",
        kind: "reference",
        sanityType: "reference",
        required: false,
        referenceTo: "categoriaPeso",
      },
      {
        name: "activo",
        label: "Activo",
        kind: "boolean",
        sanityType: "boolean",
        required: false,
        description: "Booleano editorial del estado competitivo del luchador.",
      },
      {
        name: "rankingDisciplina",
        label: "Ranking editorial en disciplina",
        kind: "number",
        sanityType: "number",
        required: false,
        validations: [
          { type: "min", value: 1 },
          { type: "max", value: 999 },
        ],
      },
      {
        name: "destacadoHome",
        label: "Destacado en inicio",
        kind: "boolean",
        sanityType: "boolean",
        required: false,
        description:
          "Activa este campo si quieres que el luchador pueda aparecer en la home.",
      },
      {
        name: "ordenDestacadoHome",
        label: "Orden en luchadores destacados de inicio",
        kind: "number",
        sanityType: "number",
        required: false,
        hiddenWhen: {
          field: "destacadoHome",
          notEquals: true,
        },
        description: "Control manual del orden en la home. Ejemplo: 1, 2, 3, 4...",
        validations: [{ type: "min", value: 1 }],
        conditionalRules: [
          {
            type: "requiredWhen",
            dependsOn: "destacadoHome",
            equals: true,
            message:
              "Si el luchador está destacado en inicio, debes indicar su orden.",
          },
        ],
      },
      {
        name: "descripcion",
        label: "Descripción",
        kind: "text",
        sanityType: "text",
        required: false,
        rows: 5,
        validations: [{ type: "max", value: 2000 }],
      },
    ],
    auxiliaryInputs: [
      {
        name: "contextoCompetitivo",
        label: "Contexto competitivo",
        kind: "text",
        rows: 4,
        description: "Momento deportivo actual del luchador.",
      },
      {
        name: "momentoActual",
        label: "Momento actual",
        kind: "text",
        rows: 3,
        description: "Situación reciente, racha o narrativa vigente.",
      },
      {
        name: "estiloLucha",
        label: "Estilo de lucha",
        kind: "text",
        rows: 3,
        description: "Cómo compite y qué rasgos diferenciales tiene.",
      },
      {
        name: "logrosClave",
        label: "Logros clave",
        kind: "text",
        rows: 3,
        description: "Títulos, victorias, hitos o valor editorial del perfil.",
      },
      {
        name: "narrativaEditorial",
        label: "Narrativa editorial",
        kind: "text",
        rows: 4,
        description: "Qué lectura quieres que la IA haga del luchador.",
      },
      {
        name: "tono",
        label: "Tono",
        kind: "string",
        description: "Tono deseado para la ficha.",
      },
    ],
  },
  {
    id: "combate",
    label: "Combate",
    description:
      "Cobertura estructurada de combate con reglas duras de coherencia entre luchadores, ganador y estado.",
    supportsImageGeneration: false,
    hasSlug: false,
    references: ["evento", "luchador", "categoriaPeso"],
    schemaFields: [
      {
        name: "evento",
        label: "Evento",
        kind: "reference",
        sanityType: "reference",
        required: true,
        referenceTo: "evento",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "luchadorRojo",
        label: "Luchador rojo",
        kind: "reference",
        sanityType: "reference",
        required: true,
        referenceTo: "luchador",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "luchadorAzul",
        label: "Luchador azul",
        kind: "reference",
        sanityType: "reference",
        required: true,
        referenceTo: "luchador",
        validations: [{ type: "required", value: true }],
        conditionalRules: [
          {
            type: "mustDifferFrom",
            dependsOn: "luchadorRojo",
            message:
              "El luchador azul no puede ser el mismo que el luchador rojo.",
          },
        ],
      },
      {
        name: "ganador",
        label: "Ganador",
        kind: "reference",
        sanityType: "reference",
        required: false,
        referenceTo: "luchador",
        description: "Déjalo vacío si el combate aún no ha finalizado.",
        conditionalRules: [
          {
            type: "requiredWhen",
            dependsOn: "estado",
            equals: "finalizado",
            message:
              "Si el combate está finalizado, debes indicar un ganador.",
          },
          {
            type: "mustBeOneOfFields",
            dependsOn: ["luchadorRojo", "luchadorAzul"],
            message:
              "El ganador debe ser uno de los dos luchadores del combate.",
          },
        ],
      },
      {
        name: "metodo",
        label: "Método",
        kind: "string",
        sanityType: "string",
        required: false,
        description: "Ejemplo: KO, TKO, Sumisión, Decisión unánime.",
        validations: [{ type: "max", value: 120 }],
      },
      {
        name: "asalto",
        label: "Asalto final",
        kind: "number",
        sanityType: "number",
        required: false,
        validations: [
          { type: "integer", value: true },
          { type: "min", value: 1 },
          { type: "max", value: 15 },
        ],
      },
      {
        name: "tiempo",
        label: "Tiempo final",
        kind: "string",
        sanityType: "string",
        required: false,
        description: "Formato esperado: 3:42",
        validations: [
          {
            type: "regex",
            value: "^\\d{1,2}:\\d{2}$",
            message: "Usa el formato 3:42",
          },
        ],
      },
      {
        name: "categoriaPeso",
        label: "Categoría de peso",
        kind: "reference",
        sanityType: "reference",
        required: true,
        referenceTo: "categoriaPeso",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "tituloEnJuego",
        label: "Título en juego",
        kind: "boolean",
        sanityType: "boolean",
        required: true,
        validations: [{ type: "required", value: true }],
      },
      {
        name: "cartelera",
        label: "Cartelera",
        kind: "string",
        sanityType: "string",
        required: true,
        options: [
          { label: "Preliminar", value: "preliminar" },
          { label: "Principal", value: "principal" },
        ],
        validations: [{ type: "required", value: true }],
      },
      {
        name: "orden",
        label: "Orden en el evento",
        kind: "number",
        sanityType: "number",
        required: false,
        description: "1 = combate principal, 2 = coestelar, etc.",
        validations: [
          { type: "integer", value: true },
          { type: "min", value: 1 },
        ],
      },
      {
        name: "estado",
        label: "Estado",
        kind: "string",
        sanityType: "string",
        required: true,
        options: [
          { label: "Programado", value: "programado" },
          { label: "Finalizado", value: "finalizado" },
          { label: "Cancelado", value: "cancelado" },
        ],
        validations: [{ type: "required", value: true }],
      },
      {
        name: "resumen",
        label: "Resumen del combate",
        kind: "text",
        sanityType: "text",
        required: false,
        rows: 3,
        validations: [{ type: "max", value: 400 }],
      },
      {
        name: "desarrollo",
        label: "Desarrollo del combate",
        kind: "text",
        sanityType: "text",
        required: false,
        rows: 8,
        validations: [{ type: "max", value: 3000 }],
      },
      {
        name: "momentoClave",
        label: "Momento clave",
        kind: "text",
        sanityType: "text",
        required: false,
        rows: 3,
        validations: [{ type: "max", value: 500 }],
      },
      {
        name: "consecuencia",
        label: "Consecuencia del resultado",
        kind: "text",
        sanityType: "text",
        required: false,
        rows: 3,
        validations: [{ type: "max", value: 700 }],
      },
    ],
    auxiliaryInputs: [
      {
        name: "contextoPrevio",
        label: "Contexto previo",
        kind: "text",
        rows: 4,
        description: "Qué historia previa hay detrás del combate.",
      },
      {
        name: "lecturaEditorial",
        label: "Lectura editorial",
        kind: "text",
        rows: 4,
        description: "Qué lectura narrativa debe priorizar la IA.",
      },
      {
        name: "claveTactica",
        label: "Clave táctica",
        kind: "text",
        rows: 3,
        description: "Aspecto técnico o táctico a enfatizar.",
      },
      {
        name: "tipoCobertura",
        label: "Tipo de cobertura",
        kind: "string",
        description: "Ejemplo: previa, resultado, análisis, ficha rápida.",
      },
      {
        name: "tono",
        label: "Tono",
        kind: "string",
        description: "Tono editorial de la redacción del combate.",
      },
    ],
  },
  {
    id: "categoriaPeso",
    label: "Categoría de peso",
    description:
      "Documento taxonómico editorial con referencia obligatoria a disciplina y unidad controlada por enum real.",
    supportsImageGeneration: false,
    hasSlug: true,
    references: ["disciplina"],
    schemaFields: [
      {
        name: "nombre",
        label: "Nombre",
        kind: "string",
        sanityType: "string",
        required: true,
        validations: [
          { type: "required", value: true },
          { type: "min", value: 2 },
          { type: "max", value: 120 },
        ],
      },
      commonSlugField("nombre"),
      {
        name: "disciplina",
        label: "Disciplina",
        kind: "reference",
        sanityType: "reference",
        required: true,
        referenceTo: "disciplina",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "limitePeso",
        label: "Límite de peso",
        kind: "number",
        sanityType: "number",
        required: true,
        description: "Ejemplo: 145",
        validations: [
          { type: "required", value: true },
          { type: "positive", value: true },
        ],
      },
      {
        name: "unidad",
        label: "Unidad",
        kind: "string",
        sanityType: "string",
        required: true,
        options: [
          { label: "Libras (lb)", value: "lb" },
          { label: "Kilogramos (kg)", value: "kg" },
        ],
        validations: [{ type: "required", value: true }],
      },
      {
        name: "descripcion",
        label: "Descripción",
        kind: "text",
        sanityType: "text",
        required: false,
        rows: 4,
        description: "Resumen editorial breve de la categoría de peso.",
        validations: [
          { type: "min", value: 10 },
          { type: "max", value: 500 },
        ],
      },
    ],
    auxiliaryInputs: [
      {
        name: "tipoCategoria",
        label: "Tipo de categoría",
        kind: "string",
        description: "Ayuda editorial para describir la división con claridad.",
      },
      {
        name: "posicionEnJerarquia",
        label: "Posición en jerarquía",
        kind: "string",
        description:
          "Contexto sobre dónde encaja la categoría dentro de la disciplina.",
      },
      {
        name: "contextoDeUso",
        label: "Contexto de uso",
        kind: "text",
        rows: 3,
        description: "Notas para que la IA no redacte una descripción vacía.",
      },
      {
        name: "tono",
        label: "Tono",
        kind: "string",
        description: "Tono de la descripción editorial.",
      },
    ],
  },
  {
    id: "disciplina",
    label: "Disciplina",
    description:
      "Documento base de disciplina con descripción breve y estado activa/inactiva.",
    supportsImageGeneration: false,
    hasSlug: true,
    references: [],
    schemaFields: [
      {
        name: "nombre",
        label: "Nombre",
        kind: "string",
        sanityType: "string",
        required: true,
        validations: [
          { type: "required", value: true },
          { type: "min", value: 2 },
          { type: "max", value: 100 },
        ],
      },
      commonSlugField("nombre"),
      {
        name: "descripcion",
        label: "Descripción",
        kind: "text",
        sanityType: "text",
        required: true,
        rows: 4,
        description: "Resumen editorial breve de la disciplina.",
        validations: [
          { type: "min", value: 10 },
          { type: "max", value: 800 },
          { type: "required", value: true },
        ],
      },
      {
        name: "activa",
        label: "Activa",
        kind: "boolean",
        sanityType: "boolean",
        required: true,
        description: "Estado real de la disciplina.",
        validations: [{ type: "required", value: true }],
      },
    ],
    auxiliaryInputs: [
      {
        name: "enfoqueEditorial",
        label: "Enfoque editorial",
        kind: "text",
        rows: 3,
        description: "Qué mirada debe proyectar la descripción.",
      },
      {
        name: "caracteristicasClave",
        label: "Características clave",
        kind: "text",
        rows: 3,
        description: "Rasgos esenciales de la disciplina.",
      },
      {
        name: "perfilCompetitivo",
        label: "Perfil competitivo",
        kind: "text",
        rows: 3,
        description: "Cómo se compite o qué define la práctica.",
      },
      {
        name: "tono",
        label: "Tono",
        kind: "string",
        description: "Tono de la descripción editorial.",
      },
    ],
  },
  {
    id: "organizacion",
    label: "Organización",
    description:
      "Ficha editorial de organización alineada con el schema real de Sanity, incluyendo logo obligatorio, disciplinas y campos de contexto institucional.",
    supportsImageGeneration: true,
    hasSlug: true,
    references: ["disciplina"],
    schemaFields: [
      {
        name: "nombre",
        label: "Nombre",
        kind: "string",
        sanityType: "string",
        required: true,
        validations: [
          { type: "required", value: true },
          { type: "min", value: 2 },
          { type: "max", value: 120 },
        ],
      },
      commonSlugField("nombre"),
      {
        name: "logo",
        label: "Logo",
        kind: "image",
        sanityType: "image",
        required: true,
        description: "Logo obligatorio de la organización.",
        validations: [{ type: "required", value: true }],
      },
      {
        name: "banner",
        label: "Banner",
        kind: "image",
        sanityType: "image",
        required: false,
        description:
          "Imagen horizontal opcional para reforzar la presencia visual de la organización.",
      },
      {
        name: "descripcionCorta",
        label: "Descripción corta",
        kind: "text",
        sanityType: "string",
        required: true,
        rows: 3,
        description: "Resumen breve para tarjetas, listados y bloques destacados.",
        validations: [
          { type: "required", value: true },
          { type: "min", value: 20 },
          { type: "max", value: 180 },
        ],
      },
      {
        name: "descripcion",
        label: "Descripción",
        kind: "text",
        sanityType: "text",
        required: true,
        rows: 6,
        description:
          "Texto editorial principal sobre la organización: qué es, su relevancia y su contexto.",
        validations: [
          { type: "required", value: true },
          { type: "min", value: 60 },
          { type: "max", value: 1600 },
        ],
      },
      {
        name: "paisOrigen",
        label: "País de origen",
        kind: "string",
        sanityType: "string",
        required: true,
        description: "Ejemplo: Estados Unidos, Singapur, Japón.",
        validations: [
          { type: "required", value: true },
          { type: "min", value: 2 },
          { type: "max", value: 80 },
        ],
      },
      {
        name: "sede",
        label: "Sede",
        kind: "string",
        sanityType: "string",
        required: false,
        description: "Ciudad o ubicación principal de la organización.",
        validations: [{ type: "max", value: 120 }],
      },
      {
        name: "anioFundacion",
        label: "Año de fundación",
        kind: "number",
        sanityType: "number",
        required: false,
        description: "Ejemplo: 1993",
        validations: [
          { type: "integer", value: true },
          { type: "min", value: 1900 },
        ],
      },
      {
        name: "identidad",
        label: "Identidad / estilo editorial",
        kind: "text",
        sanityType: "text",
        required: false,
        rows: 4,
        description:
          "Qué diferencia a esta organización: tono, propuesta, estilo competitivo, perfil de eventos, etc.",
        validations: [
          { type: "min", value: 20 },
          { type: "max", value: 800 },
        ],
      },
      {
        name: "datosCuriosos",
        label: "Datos curiosos",
        kind: "text",
        sanityType: "array<string>",
        required: false,
        rows: 6,
        description:
          "Un dato curioso por línea. El builder lo convertirá en array de strings.",
        validations: [{ type: "max", value: 1760 }],
      },
      {
        name: "disciplinas",
        label: "Disciplinas",
        kind: "referenceArray",
        sanityType: "array<reference>",
        required: true,
        referenceTo: "disciplina",
        description:
          "Disciplinas principales en las que opera la organización.",
        validations: [
          { type: "required", value: true },
          { type: "unique", value: true },
        ],
      },
      {
        name: "sitioWeb",
        label: "Sitio web",
        kind: "string",
        sanityType: "url",
        required: false,
        description: "Web oficial de la organización.",
      },
      {
        name: "activa",
        label: "Activa",
        kind: "boolean",
        sanityType: "boolean",
        required: true,
        description: "Estado operativo de la organización.",
        validations: [{ type: "required", value: true }],
      },
    ],
    auxiliaryInputs: [
      {
        name: "enfoqueEditorial",
        label: "Enfoque editorial",
        kind: "text",
        rows: 3,
        description: "Qué lectura quieres que la IA priorice en la ficha.",
      },
      {
        name: "rasgosDiferenciales",
        label: "Rasgos diferenciales",
        kind: "text",
        rows: 3,
        description: "Qué hace distinta a esta organización.",
      },
      {
        name: "contextoHistorico",
        label: "Contexto histórico",
        kind: "text",
        rows: 4,
        description: "Antecedentes o marco histórico relevante.",
      },
      {
        name: "tono",
        label: "Tono",
        kind: "string",
        description: "Tono deseado para la redacción de la ficha.",
      },
    ],
  },
];

export const supportEntities: SupportEntityDefinition[] = [
  {
    id: "organizacion",
    label: "Organización",
    description:
      "Entidad de soporte necesaria para resolver referencias reales en noticia, evento y luchador.",
    referenceFields: [
      {
        name: "organizacionRelacionada",
        label: "Organización relacionada de noticia",
        targetTypes: ["organizacion"],
      },
      {
        name: "organizacion",
        label: "Organización de evento o luchador",
        targetTypes: ["organizacion"],
      },
    ],
  },
];

export const contentTypeMap: Record<ContentTypeId, ContentTypeDefinition> =
  contentTypes.reduce((acc, item) => {
    acc[item.id] = item;
    return acc;
  }, {} as Record<ContentTypeId, ContentTypeDefinition>);

export const contentTypeOptions: ContentTypeOption[] = contentTypes.map((type) => ({
  value: type.id,
  label: type.label,
  description: type.description,
}));

export function getContentTypeDefinition(
  typeId: ContentTypeId
): ContentTypeDefinition {
  return contentTypeMap[typeId];
}