import {buildEvidenceDependencyGraph, buildFindings, deduplicateEvidence, detectInvestigationConflicts, evaluateCandidates, evaluateCoverage, evaluateInvestigationSufficiency, extractClaimsFromEvidence} from "./analysis";
import {buildDeepInvestigationPlan} from "./planning";
import {assertSafeSerializable, sanitizeExternalError} from "./security";
import {stableHash} from "./normalization";
import type {DeepInvestigationResult, InvestigationDependencies, InvestigationEvent, InvestigationRequest, ProviderRun} from "./types";

const event = (investigationId: string, type: InvestigationEvent["type"], timestamp: string, payload: InvestigationEvent["payload"] = {}, suffix: string = type): InvestigationEvent => ({id: `investigation-event:${stableHash([investigationId, suffix])}`, investigationId, type, timestamp, payload, idempotencyKey: `${investigationId}:${suffix}`, actor: "system", module: "review.investigation.deep", investigationVersion: "5f.1", policyVersion: "5f.1", provenance: "local_read_only"});
export function analyzeCollectedEvidence(request: InvestigationRequest, plan: ReturnType<typeof buildDeepInvestigationPlan>, collected: Parameters<typeof deduplicateEvidence>[0], failedProviders: string[], skippedProviders: string[], providerRuns: ProviderRun[], completedAt: string): {result: DeepInvestigationResult; events: InvestigationEvent[]} {
  const evidence = deduplicateEvidence(collected); evidence.forEach((item) => assertSafeSerializable(item, request.policy.maxEvidenceBytes));
  const dependencyGraph = buildEvidenceDependencyGraph(evidence); if (!dependencyGraph.valid) throw new Error("invalid_evidence_dependency_graph");
  const claims = extractClaimsFromEvidence(evidence).slice(0, request.policy.maxClaims); const conflicts = detectInvestigationConflicts(claims, evidence).slice(0, request.policy.maxConflicts); const candidateAssessments = evaluateCandidates(evidence); const findings = buildFindings(claims, conflicts, candidateAssessments); const coverage = evaluateCoverage(plan, evidence); const sufficiency = evaluateInvestigationSufficiency({coverage, conflicts, evidence, candidates: candidateAssessments, failedProviders, policyBlocked: false});
  const status: DeepInvestigationResult["status"] = sufficiency.status === "contradictory" ? "conflicting_evidence" : sufficiency.status === "provider_failure" ? "provider_failure" : sufficiency.status === "insufficient" ? "insufficient_evidence" : skippedProviders.length ? "completed_with_limitations" : "completed";
  const id = request.id; const events = [event(id, "investigation_requested", request.requestedAt), event(id, "investigation_planned", request.requestedAt, {planId: plan.id}), ...providerRuns.map((run) => event(id, run.status === "failed" ? "provider_failed" : run.status === "skipped" ? "provider_skipped" : "provider_completed", run.completedAt, {providerId: run.providerId}, `provider:${run.providerId}:${run.status}`)), ...evidence.map((item) => event(id, "evidence_collected", completedAt, {evidenceId: item.id}, `evidence:${item.id}`)), ...claims.map((item) => event(id, "claim_created", completedAt, {claimId: item.id}, `claim:${item.id}`)), ...conflicts.map((item) => event(id, "conflict_detected", completedAt, {conflictId: item.id}, `conflict:${item.id}`)), ...findings.map((item) => event(id, "finding_created", completedAt, {findingId: item.id}, `finding:${item.id}`)), event(id, "sufficiency_evaluated", completedAt, {status: sufficiency.status}), event(id, "investigation_completed", completedAt, {status})];
  const result: DeepInvestigationResult = {id, request, plan, status, evidence, dependencyGraph, claims, conflicts, candidateAssessments, findings, coverage, sufficiency, limitations: [...new Set([...skippedProviders.map((item) => `Proveedor omitido: ${item}`), ...providerRuns.flatMap((item) => item.limitation ? [item.limitation] : [])])], failedProviders, skippedProviders, providerRuns, createdAt: request.requestedAt, completedAt, investigationVersion: "5f.1", analysisVersion: "5f.1", eventIds: events.map((item) => item.id), stale: false, staleReasons: [], fingerprints: {case: stableHash([request.case.id, request.case.version, request.case.updatedAt]), issue: stableHash(request.issue), candidates: stableHash(request.issue.candidates ?? []), snapshot: stableHash(request.case.context.snapshot ?? request.case.context.sourceSnapshot ?? request.case.context.originalPayload ?? null), outcomes: stableHash(providerRuns.find((item) => item.providerId === "outcomes")?.evidenceCount ?? 0), memory: stableHash(providerRuns.find((item) => item.providerId === "memory")?.evidenceCount ?? 0), retrieval: stableHash(request.retrieval ?? null), providers: stableHash(plan.providers), policy: stableHash(request.policy), analysis: stableHash("5f.1"), context: request.contextFingerprint}, notes: []};
  return {result, events};
}

export async function investigateReviewIssueCore(request: InvestigationRequest, dependencies: InvestigationDependencies, signal?: AbortSignal) {
  assertSafeSerializable(request, request.policy.maxTotalBytes); const plan = buildDeepInvestigationPlan(request, dependencies.providers); const now = dependencies.now ?? (() => new Date().toISOString()); const controller = new AbortController(); const forward = () => controller.abort(); signal?.addEventListener("abort", forward, {once: true});
  const collected = []; const failedProviders: string[] = []; const skippedProviders: string[] = []; const runs: ProviderRun[] = [];
  try {
    for (const selection of plan.providers) {
      const provider = dependencies.providers.find((item) => item.id === selection.providerId)!; const startedAt = now();
      if (!selection.selected) { skippedProviders.push(provider.id); runs.push({id: `${request.id}:${provider.id}`, providerId: provider.id, status: "skipped", startedAt, completedAt: startedAt, evidenceCount: 0, limitation: selection.reason}); continue; }
      if (controller.signal.aborted) throw new Error("cancelled");
      try { const timer = setTimeout(() => controller.abort(), Math.min(provider.timeoutMs, request.timeoutMs)); const output = await provider.collect({request, outcomes: dependencies.outcomes, memories: dependencies.memories, clusters: dependencies.clusters, retrieval: dependencies.retrieval, signal: controller.signal, now: startedAt}); clearTimeout(timer); assertSafeSerializable(output, request.policy.maxTotalBytes); collected.push(...output.evidence.slice(0, request.maxEvidence - collected.length)); runs.push({id: `${request.id}:${provider.id}`, providerId: provider.id, status: "completed", startedAt, completedAt: now(), evidenceCount: output.evidence.length, limitation: output.limitations.join(" ") || undefined}); }
      catch (error) { failedProviders.push(provider.id); runs.push({id: `${request.id}:${provider.id}`, providerId: provider.id, status: controller.signal.aborted ? "cancelled" : "failed", startedAt, completedAt: now(), evidenceCount: 0, limitation: sanitizeExternalError(error)}); if (controller.signal.aborted) throw new Error("cancelled"); }
    }
    const analyzed = analyzeCollectedEvidence(request, plan, collected, failedProviders, skippedProviders, runs, now());
    analyzed.result.fingerprints.outcomes = stableHash(dependencies.outcomes.map((item) => [item.id, item.updatedAt, item.currentStatus]));
    analyzed.result.fingerprints.memory = stableHash(dependencies.memories.map((item) => [item.id, item.updatedAt, item.status, item.memoryFingerprint]));
    analyzed.result.fingerprints.providers = stableHash(dependencies.providers.map((item) => [item.id, item.version, item.enabled, item.sanitizationVersion]));
    return analyzed;
  } finally { signal?.removeEventListener("abort", forward); }
}
