import {useEffect, useState, useSyncExternalStore} from "react";
import type {ReviewCase} from "../../types";
import {addInvestigationNote, buildReviewInvestigationPlan, exportReviewInvestigations, getInvestigationStoreVersion, getLatestReviewInvestigationForIssue, investigateReviewIssue, reconcileReviewInvestigations, subscribeInvestigationStore} from "./store";
import type {DeepInvestigationPlan, InvestigationMode} from "./types";

const labels: Record<InvestigationMode, string> = {local_only: "Datos locales", local_and_cms_read: "Incluir CMS de solo lectura", authorized_sources: "Incluir fuentes autorizadas"};
export default function InvestigationPanel({reviewCase}: {reviewCase: ReviewCase}) {
  useSyncExternalStore(subscribeInvestigationStore, getInvestigationStoreVersion, getInvestigationStoreVersion);
  const [issueId, setIssueId] = useState(reviewCase.issues[0]?.id ?? ""); const [mode, setMode] = useState<InvestigationMode>("local_only"); const [planned, setPlanned] = useState<DeepInvestigationPlan>(); const [running, setRunning] = useState(false); const [error, setError] = useState(""); const [note, setNote] = useState("");
  useEffect(() => { if (!reviewCase.issues.some((item) => item.id === issueId)) setIssueId(reviewCase.issues[0]?.id ?? ""); }, [reviewCase.issues, issueId]);
  useEffect(() => { setPlanned(undefined); }, [issueId, mode, reviewCase.version]);
  const result = issueId ? getLatestReviewInvestigationForIssue(issueId) : undefined;
  const run = async () => { setRunning(true); setError(""); try { await investigateReviewIssue(reviewCase.id, issueId, {mode}); } catch (caught) { setError(caught instanceof Error && caught.message === "cancelled" ? "Investigación cancelada." : "La investigación falló de forma controlada."); } finally { setRunning(false); } };
  const download = () => { const blob = new Blob([JSON.stringify(exportReviewInvestigations(), null, 2)], {type: "application/json"}); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "ffn3-investigaciones.json"; anchor.click(); URL.revokeObjectURL(url); };
  return <section className="review-subsection investigation-panel" aria-labelledby={`investigation-${reviewCase.id}`}>
    <p className="review-kicker">5F · Solo lectura</p><h4 className="review-subtitle" id={`investigation-${reviewCase.id}`}>Investigación profunda</h4>
    <p>Recopila y contrasta evidencia. No decide, no aplica resoluciones y no modifica ningún dominio editorial.</p>
    <div className="review-row review-row-wrap"><label>Incidencia <select value={issueId} onChange={(event) => setIssueId(event.target.value)}>{reviewCase.issues.map((issue) => <option key={issue.id} value={issue.id}>{issue.label}</option>)}</select></label><label>Alcance <select value={mode} onChange={(event) => setMode(event.target.value as InvestigationMode)}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
    {mode !== "local_only" ? <p className="review-readonly-message">Los proveedores de red requieren infraestructura servidor allowlisted. Si no está disponible, el plan los omitirá y explicará el motivo.</p> : null}
    <div className="review-actions"><button className="review-button" type="button" disabled={!issueId || running} onClick={() => { if (mode !== "local_only" && !planned) { setPlanned(buildReviewInvestigationPlan(reviewCase.id, issueId, {mode})); return; } void run(); }}>{running ? "Investigando…" : mode !== "local_only" && !planned ? "Revisar plan" : result ? "Volver a investigar" : "Investigar incidencia"}</button>{result ? <><button className="review-button review-button-secondary" type="button" onClick={() => reconcileReviewInvestigations(result.id)}>Reconciliar</button><button className="review-button review-button-secondary" type="button" onClick={download}>Exportar expediente</button></> : null}</div>
    {planned ? <div className="review-readonly-message"><strong>Plan previo</strong><ul>{planned.providers.map((item) => <li key={item.providerId}>{item.providerId}: {item.selected ? "incluido" : "excluido"} — {item.reason}</li>)}</ul><p>La ejecución seguirá siendo de solo lectura. Pulsa “Investigar incidencia” para continuar.</p></div> : null}
    {error ? <p role="alert">{error}</p> : null}
    {!result ? <p className="review-empty">Sin investigación</p> : <div className="investigation-results">
      <dl className="review-definition-grid"><dt>Estado</dt><dd>{result.status}</dd><dt>Modo</dt><dd>{result.request.mode}</dd><dt>Cobertura</dt><dd>{result.coverage.coveredCriticalQuestions}/{result.coverage.criticalQuestions}</dd><dt>Suficiencia</dt><dd>{result.sufficiency.status}</dd><dt>Independencia</dt><dd>{result.coverage.independentGroups} grupos</dd><dt>Stale</dt><dd>{result.stale ? "Sí" : "No"}</dd></dl>
      <h5>Preguntas</h5><ul>{result.plan.questions.map((item) => <li key={item.id}><strong>{item.subject} · {item.predicate}</strong> — {item.reason}</li>)}</ul>
      <h5>Findings</h5>{result.findings.length ? <ul>{result.findings.map((item) => <li key={item.id}><strong>{item.status}</strong> — {item.explanation}{item.blocksResolution ? " · Bloqueante" : ""}</li>)}</ul> : <p>Sin findings.</p>}
      <h5>Claims</h5>{result.claims.length ? <ul>{result.claims.map((item) => <li key={item.id}><strong>{item.subject} · {item.predicate}</strong> — {item.assessment} ({Math.round(item.confidence * 100)} %). Evidencia: {item.sourceEvidenceIds.length}; contraria: {item.opposingEvidenceIds.length}.</li>)}</ul> : <p>Sin claims.</p>}
      <h5>Conflictos</h5>{result.conflicts.length ? <ul>{result.conflicts.map((item) => <li key={item.id}>{item.severity}: {item.explanation}</li>)}</ul> : <p>Sin conflictos detectados.</p>}
      <h5>Evidencia</h5>{result.evidence.length ? <div className="investigation-evidence-list">{result.evidence.map((item) => <article className="review-resolution" key={item.id}><strong>{item.subject} · {item.predicate}</strong><span>Origen: {item.provenance} · {item.sourceClass}</span><span>{item.authority} · {item.directness} · {item.freshness} · {item.reliability}</span><span>Independencia: {item.independenceGroup}</span>{item.transformations.length ? <span>Transformaciones: {item.transformations.join(", ")}</span> : null}{item.parentEvidenceIds.length ? <span>Dependencias: {item.parentEvidenceIds.join(", ")}</span> : null}{item.limitations.map((limitation) => <span key={limitation}>Limitación: {limitation}</span>)}</article>)}</div> : <p>Sin evidencia disponible.</p>}
      {result.limitations.length ? <><h5>Limitaciones</h5><ul>{result.limitations.map((item) => <li key={item}>{item}</li>)}</ul></> : null}
      <div className="review-row"><input aria-label="Nota local" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Añadir nota al expediente"/><button className="review-button review-button-secondary" type="button" disabled={!note.trim()} onClick={() => { addInvestigationNote(result.id, note); setNote(""); }}>Añadir nota</button></div>
    </div>}
  </section>;
}
