import type {ReviewCase, ReviewIssue, ReviewJsonValue, ReviewResolution} from "../../types";
import type {DecisionOutcomeRecord} from "../../outcomes";
import type {DecisionMemoryCluster, DecisionMemoryRecord} from "../../memory";
import type {RetrievalResult} from "../../retrieval";

export type InvestigationMode = "local_only" | "local_and_cms_read" | "authorized_sources";
export type EvidenceSourceClass = "internal_local" | "cms_read" | "producer" | "authorized_source";
export type InvestigationStatus = "planned" | "running" | "completed" | "completed_with_limitations" | "insufficient_evidence" | "conflicting_evidence" | "provider_failure" | "cancelled" | "stale" | "failed";
export type SufficiencyStatus = "sufficient_for_proposal" | "sufficient_only_for_rejection" | "insufficient" | "contradictory" | "stale" | "provider_failure" | "policy_blocked";
export type EvidenceAuthority = "official_primary" | "official_secondary" | "trusted_editorial" | "internal_structured" | "historical_editorial" | "derived_analysis" | "unknown";
export type EvidenceDirectness = "direct" | "near_direct" | "derived" | "inferred";
export type EvidenceFreshness = "current" | "recent" | "aging" | "stale" | "unknown";
export type EvidenceReliability = "high" | "medium" | "low" | "unknown";
export type ClaimAssessment = "supported" | "partially_supported" | "contradicted" | "unresolved" | "insufficient_evidence" | "stale_only";

export type InvestigationPolicy = {version: "5f.1"; maxProviders: number; maxEvidence: number; maxClaims: number; maxConflicts: number; maxDepth: number; maxTotalBytes: number; maxEvidenceBytes: number; timeoutMs: number};
export type InvestigationRequest = {id: string; version: 1; case: ReviewCase; issue: ReviewIssue; retrieval?: RetrievalResult; requestedAt: string; requestedBy: string; mode: InvestigationMode; allowedProviderIds: string[]; maxDepth: number; maxEvidence: number; timeoutMs: number; contextFingerprint: string; policy: InvestigationPolicy};
export type ResearchQuestion = {id: string; kind: string; subject: string; predicate: string; critical: boolean; reason: string; expectedEvidenceKinds: string[]};
export type ProviderSelection = {providerId: string; selected: boolean; reason: string};
export type DeepInvestigationPlan = {id: string; requestId: string; version: 1; issueType: string; questions: ResearchQuestion[]; providers: ProviderSelection[]; createdAt: string; deterministicFingerprint: string};

export type EvidenceItem = {id: string; providerId: string; providerRunId: string; sourceClass: EvidenceSourceClass; sourceId: string; sourceFingerprint: string; subject: string; predicate: string; originalValue?: ReviewJsonValue; normalizedValue?: ReviewJsonValue; transformations: string[]; normalizerVersion: "5f.1"; authority: EvidenceAuthority; directness: EvidenceDirectness; freshness: EvidenceFreshness; reliability: EvidenceReliability; observedAt?: string; collectedAt: string; provenance: string; parentEvidenceIds: string[]; independenceGroup: string; limitations: string[]; status: "active" | "stale" | "contradicted" | "excluded" | "unavailable"; equivalentEvidenceIds: string[]};
export type EvidenceDependencyGraph = {nodes: Array<{evidenceId: string; independenceGroup: string}>; edges: Array<{from: string; to: string; transformation: string}>; valid: boolean; errors: string[]};
export type Claim = {id: string; subject: string; predicate: string; normalizedValue: ReviewJsonValue; claimType: string; sourceEvidenceIds: string[]; opposingEvidenceIds: string[]; dependencyGroups: string[]; assessment: ClaimAssessment; confidence: number; explanation: string; limitations: string[]};
export type InvestigationConflict = {id: string; conflictType: string; claimIds: string[]; evidenceIds: string[]; independenceGroups: string[]; severity: "low" | "medium" | "high" | "critical"; explanation: string; resolvableByCurrentEvidence: boolean; missingEvidenceKinds: string[]};
export type CandidateAssessment = {candidateId: string; status: "supported" | "partially_supported" | "contradicted" | "insufficient_evidence" | "incompatible"; evidenceIds: string[]; opposingEvidenceIds: string[]; matchedDimensions: string[]; mismatchedDimensions: string[]; missingDimensions: string[]; dependencyGroups: string[]; confidence: number; explanation: string};
export type InvestigationFinding = {id: string; findingType: string; subject: string; status: ClaimAssessment | "entity_ambiguity" | "relationship_ambiguity"; claimIds: string[]; evidenceIds: string[]; confidence: number; explanation: string; limitations: string[]; blocksResolution: boolean; suggestedNextEvidenceKinds: string[]};
export type InvestigationCoverage = {criticalQuestions: number; coveredCriticalQuestions: number; ratio: number; independentGroups: number};
export type InvestigationSufficiency = {status: SufficiencyStatus; reasons: string[]; policyVersion: string};
export type ProviderRun = {id: string; providerId: string; status: "completed" | "failed" | "skipped" | "cancelled"; startedAt: string; completedAt: string; evidenceCount: number; limitation?: string};
export type InvestigationEventType = "investigation_requested" | "investigation_planned" | "provider_selected" | "provider_skipped" | "provider_started" | "provider_completed" | "provider_failed" | "evidence_collected" | "evidence_deduplicated" | "evidence_excluded" | "claim_created" | "conflict_detected" | "finding_created" | "sufficiency_evaluated" | "investigation_completed" | "investigation_failed" | "investigation_cancelled" | "investigation_marked_stale" | "investigation_reconciled" | "investigation_note_added";
export type InvestigationEvent = {id: string; investigationId: string; type: InvestigationEventType; timestamp: string; payload: Record<string, ReviewJsonValue>; idempotencyKey: string; actor: string; module: "review.investigation.deep"; providerId?: string; investigationVersion: string; policyVersion: string; provenance: string};
export type DeepInvestigationResult = {id: string; request: InvestigationRequest; plan: DeepInvestigationPlan; status: InvestigationStatus; evidence: EvidenceItem[]; dependencyGraph: EvidenceDependencyGraph; claims: Claim[]; conflicts: InvestigationConflict[]; candidateAssessments: CandidateAssessment[]; findings: InvestigationFinding[]; coverage: InvestigationCoverage; sufficiency: InvestigationSufficiency; limitations: string[]; failedProviders: string[]; skippedProviders: string[]; providerRuns: ProviderRun[]; createdAt: string; completedAt: string; investigationVersion: "5f.1"; analysisVersion: "5f.1"; eventIds: string[]; stale: boolean; staleReasons: string[]; fingerprints: Record<string, string>; notes: string[]};
export type InvestigationLedger = {schemaVersion: 1; requests: InvestigationRequest[]; plans: DeepInvestigationPlan[]; results: DeepInvestigationResult[]; events: InvestigationEvent[]};

export type InvestigationProviderContext = {request: InvestigationRequest; outcomes: DecisionOutcomeRecord[]; memories: DecisionMemoryRecord[]; clusters: DecisionMemoryCluster[]; retrieval?: RetrievalResult; signal: AbortSignal; now: string};
export type InvestigationProvider = {id: string; version: string; sourceClass: EvidenceSourceClass; capabilities: string[]; supportedIssueTypes: string[]; requiredContext: string[]; riskLevel: "low" | "medium" | "high"; readOnly: true; networkAccess: boolean; authorizedDomains: string[]; maximumRequests: number; timeoutMs: number; cachePolicy: string; storesRawPayload: false; sanitizationVersion: string; enabled: boolean; unavailableReason?: string; collect(context: InvestigationProviderContext): Promise<{evidence: EvidenceItem[]; limitations: string[]}>};
export type InvestigationDependencies = {outcomes: DecisionOutcomeRecord[]; memories: DecisionMemoryRecord[]; clusters: DecisionMemoryCluster[]; retrieval?: RetrievalResult; providers: InvestigationProvider[]; now?: () => string};
export type ObservedResolution = ReviewResolution;
