import {getSchemaRequirementReferenceOptions} from "../../integrations/editorialSchemaRequirements";
import {getReviewCase} from "../store/reviewStore";
import type {InvestigationEvidence} from "../investigation";
import type {ReviewCase, ReviewJsonObject, ReviewJsonValue} from "../types";
import {inspectPreparedEntityRequirements} from "./inspectPreparedEntityRequirements";
import type {MissingEntityRequirement, PreparedEntityRequirementReport, RequirementResolutionConclusion, RequiredReferenceFallbackPolicy} from "./types";

const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const object = (value: ReviewJsonValue | undefined): ReviewJsonObject | undefined => value && typeof value === "object" && !Array.isArray(value) ? value : undefined;
const text = (value: ReviewJsonValue | undefined): string => typeof value === "string" ? value : "";
function evidence(id: string, label: string, value: ReviewJsonValue, now: string, reasons: string[]): InvestigationEvidence { return {id, source: "review_case", sourceType: "existing_analysis", reliability: .95, label, value, observedAt: now, reasons, warnings: []}; }
function findExact(target: "disciplina" | "organizacion", label: string) { const wanted = normalize(label); return getSchemaRequirementReferenceOptions().filter((item) => item.target === target && normalize(item.label) === wanted); }
function contextText(reviewCase: ReviewCase): string { return JSON.stringify({title: reviewCase.title, subject: reviewCase.subject, context: reviewCase.context}).toLowerCase(); }
function conclusion(base: MissingEntityRequirement, input: Partial<RequirementResolutionConclusion> & Pick<RequirementResolutionConclusion, "status" | "confidence" | "reasoningSummary">): RequirementResolutionConclusion { return {requirementId: base.requirement.id, evidence: [], warnings: [], validation: {valid: input.status === "resolved", errors: input.status === "resolved" ? [] : [base.requirement.message]}, ...input}; }

function resolveDiscipline(reviewCase: ReviewCase, missing: MissingEntityRequirement, now: string): RequirementResolutionConclusion {
  const analysis = object(reviewCase.context.analysisSnapshot); const nestedAnalysis = object(analysis?.analysis); const label = text(analysis?.disciplinaPrincipal) || text(nestedAnalysis?.disciplinaPrincipal);
  const body = contextText(reviewCase); const boxingClassified = normalize(label) === "boxeo"; const participants = body.includes("combate") || body.includes("disputar") || body.includes("boxe"); const contradictory = /\bmma\b|kickboxing|muay thai/.test(body) && !boxingClassified;
  const candidates = findExact("disciplina", label || "Boxeo");
  if (boxingClassified && participants && !contradictory && candidates.length === 1 && candidates[0].value.trim()) { const found = candidates[0]; const proof = evidence(`${missing.requirement.id}:classification`, `Disciplina clasificada: ${label}`, {label, entityId: found.value}, now, ["La clasificación persistida es inequívoca.", "Los sujetos son participantes principales del combate.", "La referencia existe una sola vez en el catálogo Sanity de solo lectura."]); return conclusion(missing, {status: "resolved", confidence: .97, proposedReference: {entityType: "discipline", entityId: found.value, label: found.label}, proposedDraftPatch: {disciplineId: found.value}, evidence: [proof], reasoningSummary: `Boxeo está demostrado por clasificación persistida, contexto de combate y referencia Sanity inequívoca (${found.value}).`}); }
  if (candidates.length > 1) return conclusion(missing, {status: "conflict", confidence: .45, reasoningSummary: "Varias referencias de disciplina coinciden; no se puede elegir una de forma reproducible.", warnings: ["Disciplina ambigua."]});
  return conclusion(missing, {status: "needs_more_evidence", confidence: boxingClassified ? .7 : 0, reasoningSummary: !boxingClassified ? "No existe una clasificación persistida inequívoca de la disciplina." : candidates.length === 0 ? "Boxeo está demostrado editorialmente, pero no existe un ID inequívoco en las referencias cargadas." : "El contexto no demuestra que la mención de boxeo describa el combate de los sujetos."});
}

function fallbackPolicy(reviewCase: ReviewCase, field: string): RequiredReferenceFallbackPolicy | undefined { const value = object(reviewCase.context.requiredReferenceFallbackPolicy); if (!value || value.field !== field) return undefined; return value as unknown as RequiredReferenceFallbackPolicy; }
function resolveOrganization(reviewCase: ReviewCase, draft: ReviewJsonObject, missing: MissingEntityRequirement, now: string): RequirementResolutionConclusion {
  const sourceEvidence = Array.isArray(draft.sourceEvidence) ? draft.sourceEvidence.map(object).filter(Boolean) : []; const affiliationEvidence = sourceEvidence.find((item) => text(item?.relationRole) === "stable_fighter_affiliation");
  const affiliation = text(affiliationEvidence?.organizationLabel) || text(object(reviewCase.context.analysisSnapshot)?.fighterOrganization);
  const role = text(affiliationEvidence?.relationRole) || text(object(reviewCase.context.analysisSnapshot)?.fighterOrganizationRole);
  if (affiliation && role === "stable_fighter_affiliation") { const candidates = findExact("organizacion", affiliation); if (candidates.length === 1) { const found = candidates[0]; return conclusion(missing, {status: "resolved", confidence: .95, proposedReference: {entityType: "organization", entityId: found.value, label: found.label}, proposedDraftPatch: {organizationIds: [found.value]}, evidence: [evidence(`${missing.requirement.id}:affiliation`, affiliation, {role, entityId: found.value}, now, ["La evidencia declara una afiliación estable del luchador."])], reasoningSummary: "La organización se aplica porque está demostrada como afiliación estable, no por mera mención contextual."}); } }
  const policy = fallbackPolicy(reviewCase, "organizationIds");
  if (policy?.approved && policy.strategy === "use_default_reference" && policy.defaultEntityId?.trim()) return conclusion(missing, {status: "resolved", confidence: .9, proposedReference: {entityType: "organization", entityId: policy.defaultEntityId}, proposedDraftPatch: {organizationIds: [policy.defaultEntityId]}, evidence: [evidence(`${missing.requirement.id}:policy`, policy.id, {policyId: policy.id, version: policy.version, approved: true}, now, [policy.reason])], reasoningSummary: "Se propone la referencia únicamente por una política de fallback explícita, aprobada y versionada."});
  const analysis = object(reviewCase.context.analysisSnapshot); const mentioned = text(analysis?.organizacionPrincipal) || text(object(analysis?.analysis)?.organizacionPrincipal); const sanctioning = /\b(wba|wbc|ibf|wbo)\b/i.test(mentioned) || /titulo.*\b(wba|wbc|ibf|wbo)\b/i.test(contextText(reviewCase));
  const recommendation = {type: "split_relationship" as const, field: "organizationIds", reason: "La obligatoriedad mezcla afiliación estable del luchador con promotora, liga y organismo sancionador.", useCurrent: "Se usa en ficha, filtros y consultas inversas como organización del luchador.", contradiction: sanctioning ? `${mentioned || "El organismo mencionado"} sanciona un título, pero eso no demuestra afiliación del boxeador.` : "Un boxeador puede existir editorialmente sin afiliación estable demostrable.", impact: "La obligación fuerza relaciones falsas y bloquea altas legítimas.", alternative: "Hacer opcional la afiliación estable y modelar promotora/organismo sancionador en evento o combate.", risks: ["Cambiar filtros que hoy asumen una organización.", "Revisar documentos existentes antes de una migración futura."], potentiallyAffectedDocuments: "Luchadores sin afiliación estable y productores ajenos a ligas cerradas."};
  return conclusion(missing, {status: policy && !policy.approved ? "schema_policy_required" : "schema_change_recommended", confidence: .94, schemaRecommendation: recommendation, evidence: sanctioning ? [evidence(`${missing.requirement.id}:sanctioning`, mentioned || "Organismo sancionador", {role: "sanctioning_body"}, now, ["La mención corresponde al título o sanción, no a afiliación estable."])] : [], reasoningSummary: policy && !policy.approved ? "Existe una política de fallback, pero no está aprobada; no puede aplicarse." : "No hay afiliación estable demostrada. La ausencia no invalida al luchador y revela un posible problema de modelado.", warnings: ["La organización mencionada no se aplicará como afiliación."]});
}

export function resolveEntityRequirements(caseId: string, now = () => new Date().toISOString()): PreparedEntityRequirementReport {
  const report = inspectPreparedEntityRequirements(caseId, now); const reviewCase = getReviewCase(caseId); if (!reviewCase || !report.items.length) return report;
  const items = report.items.map((item) => { const conclusions = item.missing.map((missing) => missing.requirement.field === "disciplineId" ? resolveDiscipline(reviewCase, missing, report.generatedAt) : missing.requirement.field === "organizationIds" ? resolveOrganization(reviewCase, item.draft, missing, report.generatedAt) : conclusion(missing, {status: "needs_more_evidence", confidence: 0, reasoningSummary: "No existe todavía una capacidad registrada para resolver este requisito."})); const unresolved = conclusions.filter((entry) => entry.status !== "resolved"); return {...item, conclusions, validAfterEnrichment: unresolved.length === 0, blockingReasons: unresolved.map((entry) => entry.reasoningSummary)}; });
  return {...report, status: items.every((item) => item.validAfterEnrichment) ? "ready" : "blocked", items};
}
