import {registerEditorialCapability, runEditorialAgent, type EditorialAgentFact, type EditorialCapabilityAdapter} from "../agent";
import type {ReviewJsonObject} from "../types";
import {applyPreparedEntityEnrichment, inspectPreparedEntityRequirements, resolveEntityRequirements} from ".";

const result = (id: string, outcome: string, value: ReviewJsonObject, now: string, summary: string, status: "completed" | "needs_input" = "completed") => ({status, producedOutcomes: status === "completed" ? [outcome] : [], facts: status === "completed" ? [{key: outcome, value, source: id, confidence: 1, observedAt: now} satisfies EditorialAgentFact] : [], artifact: value, reasoningSummary: summary, evidence: [], warnings: []});
const manifest = (id: string, provides: string[], requires: string[], effects: EditorialCapabilityAdapter["manifest"]["effects"], risk: EditorialCapabilityAdapter["manifest"]["risk"]): EditorialCapabilityAdapter["manifest"] => ({id, version: 1, description: id, provides, requires, effects, risk, timeoutMs: 10_000, priority: 100 - requires.length, maxExecutionsPerRun: 1, idempotency: effects.includes("write_review_store") ? "store_versioned" : "read_only"});
const adapters: EditorialCapabilityAdapter[] = [
  {manifest: manifest("schema.inspect_entity_requirements", ["entity_schema_requirements_inspected"], [], ["read_local"], "low"), supports: (goal) => typeof goal.target.caseId === "string", execute: async (ctx) => result("schema.inspect_entity_requirements", "entity_schema_requirements_inspected", inspectPreparedEntityRequirements(String(ctx.goal.target.caseId), () => ctx.now) as unknown as ReviewJsonObject, ctx.now, "Requisitos inspeccionados mediante adapter declarado fuera del kernel.")},
  {manifest: manifest("schema.detect_missing_requirements", ["missing_entity_requirements_detected"], ["entity_schema_requirements_inspected"], ["read_local"], "low"), supports: () => true, execute: async (ctx) => result("schema.detect_missing_requirements", "missing_entity_requirements_detected", inspectPreparedEntityRequirements(String(ctx.goal.target.caseId), () => ctx.now) as unknown as ReviewJsonObject, ctx.now, "Requisitos ausentes detectados sin mutación.")},
  {manifest: manifest("schema.resolve_required_reference", ["required_reference_investigated"], ["missing_entity_requirements_detected"], ["read_local", "read_external"], "low"), supports: () => true, execute: async (ctx) => { const report = resolveEntityRequirements(String(ctx.goal.target.caseId), () => ctx.now); return result("schema.resolve_required_reference", "required_reference_investigated", report as unknown as ReviewJsonObject, ctx.now, "Referencias investigadas; el resultado conserva explícitamente resolución, conflicto o falta de evidencia."); }},
  {manifest: manifest("schema.evaluate_requirement_semantics", ["requirement_semantics_evaluated"], ["required_reference_investigated"], ["read_local"], "low"), supports: () => true, execute: async (ctx) => result("schema.evaluate_requirement_semantics", "requirement_semantics_evaluated", resolveEntityRequirements(String(ctx.goal.target.caseId), () => ctx.now) as unknown as ReviewJsonObject, ctx.now, "Se distinguieron afiliación, promotora y organismo sancionador.")},
  {manifest: manifest("schema.propose_policy_or_schema_change", ["schema_recommendation_prepared"], ["requirement_semantics_evaluated"], ["read_local"], "low"), supports: () => true, execute: async (ctx) => result("schema.propose_policy_or_schema_change", "schema_recommendation_prepared", resolveEntityRequirements(String(ctx.goal.target.caseId), () => ctx.now) as unknown as ReviewJsonObject, ctx.now, "Recomendaciones preparadas; no se modifica el schema.")},
  {manifest: manifest("review.enrich_prepared_entity", ["prepared_entity_enriched"], ["schema_recommendation_prepared"], ["write_review_store"], "medium"), supports: () => true, execute: async (ctx) => result("review.enrich_prepared_entity", "prepared_entity_enriched", applyPreparedEntityEnrichment(String(ctx.goal.target.caseId)) as unknown as ReviewJsonObject, ctx.now, "Solo se aplicaron patches respaldados por conclusiones resueltas.")},
  {manifest: manifest("review.revalidate_prepared_entity", ["prepared_entity_revalidated", "prepared_entity_schema_requirements_resolved"], ["prepared_entity_enriched"], ["read_local"], "low"), supports: () => true, execute: async (ctx) => { const report = resolveEntityRequirements(String(ctx.goal.target.caseId), () => ctx.now); return {status: "completed", producedOutcomes: ["prepared_entity_revalidated", ...(report.status === "ready" ? ["prepared_entity_schema_requirements_resolved"] : [])], facts: [], artifact: report as unknown as ReviewJsonObject, reasoningSummary: report.status === "ready" ? "Todos los requisitos quedaron resueltos." : "La revalidación mantiene el bloqueo por evidencia, política o schema.", evidence: [], warnings: report.items.flatMap((item) => item.blockingReasons)}; }},
];
export function registerSchemaRequirementCapabilities(): () => void { const cleanups = adapters.map(registerEditorialCapability); return () => cleanups.reverse().forEach((cleanup) => cleanup()); }
export function runPreparedEntityRequirementAgent(caseId: string) { return runEditorialAgent({id: `schema-requirements:${caseId}`, objective: "Resolver requisitos obligatorios demostrables sin crear entidades.", target: {caseId}, requiredOutcomes: ["prepared_entity_schema_requirements_resolved"]}, {policy: {allowedEffects: ["read_local", "read_external"], maximumRisk: "low"}}); }
