import type {InvestigationEvidence} from "../investigation";
import type {ReviewJsonObject, ReviewJsonValue} from "../types";

export type EntitySchemaRequirement = {id: string; entityType: string; field: string; label: string; requirementType: "required_value" | "required_reference" | "required_array" | "required_format" | "required_relationship" | "cross_field_constraint"; expectedType: "string" | "number" | "boolean" | "date" | "url" | "reference" | "references" | "object" | "array"; targetEntityType?: string; semanticRole?: string; source: "sanity_schema" | "builder_validation" | "resume_validation" | "business_rule"; blocking: boolean; message: string; metadata?: ReviewJsonObject};
export type MissingEntityRequirement = {requirement: EntitySchemaRequirement; currentValue?: ReviewJsonValue; status: "missing" | "invalid" | "ambiguous" | "inapplicable" | "schema_question"; evidence: InvestigationEvidence[]; reasons: string[]};
export type SchemaRecommendation = {type: "make_optional" | "change_semantics" | "add_fallback_policy" | "split_relationship" | "document_requirement"; field: string; reason: string; useCurrent?: string; contradiction?: string; impact?: string; alternative?: string; risks?: string[]; potentiallyAffectedDocuments?: string};
export type RequirementResolutionConclusion = {requirementId: string; status: "resolved" | "needs_more_evidence" | "not_applicable" | "schema_policy_required" | "schema_change_recommended" | "conflict" | "rejected"; confidence: number; proposedValue?: ReviewJsonValue; proposedReference?: {entityType: string; entityId: string; label?: string}; proposedDraftPatch?: ReviewJsonObject; schemaRecommendation?: SchemaRecommendation; evidence: InvestigationEvidence[]; reasoningSummary: string; warnings: string[]; validation: {valid: boolean; errors: string[]}};
export type RequiredReferenceFallbackPolicy = {id: string; entityType: string; field: string; strategy: "use_default_reference" | "allow_missing" | "defer_materialization" | "require_source_confirmation"; defaultEntityId?: string; conditions: ReviewJsonObject; reason: string; approved: boolean; version: number};
export type PreparedEntityRequirementItem = {issueId: string; entityType: string; draft: ReviewJsonObject; requirements: EntitySchemaRequirement[]; missing: MissingEntityRequirement[]; conclusions: RequirementResolutionConclusion[]; validAfterEnrichment: boolean; blockingReasons: string[]};
export type PreparedEntityRequirementReport = {caseId: string; status: "ready" | "blocked" | "case_not_found" | "no_prepared_entities" | "adapter_missing"; dryRun: boolean; items: PreparedEntityRequirementItem[]; generatedAt: string; warnings: string[]};
export type EntitySchemaRequirementAdapter = {entityType: string; requirements: readonly EntitySchemaRequirement[]; inspect(draft: ReviewJsonObject): EntitySchemaRequirement[]};
