import type {KnowledgeValidityState} from "../knowledge";
import type {ReviewCaseStatus, ReviewPriority} from "../types";
import type {NucleusPrimaryAction, NucleusResolutionState, NucleusRisk} from "./types";

export const OPERATOR_EXPERIENCE_VERSION = "1.0.0" as const;
export type OperatorWorkspaceSection = "dashboard" | "priorities" | "case" | "activity" | "knowledge";
export type OperatorFeedbackStatus = "started" | "completed" | "blocked" | "authorization_required" | "reconciliation_required" | "safe_error";
export type OperatorFilters = Readonly<{status?: ReviewCaseStatus | "all"; severity?: ReviewPriority | "all"; producer?: string | "all"; entityType?: string | "all"; autonomy?: string | "all"; risk?: NucleusRisk | "all"; capability?: string | "all"; knowledgeState?: KnowledgeValidityState | "all"; actionRequired?: NucleusPrimaryAction["kind"] | "all"; query?: string; page?: number; pageSize?: number}>;
export type OperatorCaseRow = Readonly<{caseId: string; title: string; state: NucleusResolutionState; action: NucleusPrimaryAction; progress: Readonly<{completed: number; total: number; percent: number}>; investigationSources: number; phaseCount: number; live: boolean; blockers: readonly string[]; relatedCases: number; fingerprint: string}>;
export type OperatorNotification = Readonly<{id: string; priority: "critical" | "high" | "normal"; kind: "authorization" | "reconciliation" | "failure" | "completed" | "stale" | "shared_blocker"; caseIds: readonly string[]; safeMessage: string; fingerprint: string}>;
export type OperatorExperienceViewModel = Readonly<{version: typeof OPERATOR_EXPERIENCE_VERSION; activeSection: OperatorWorkspaceSection; breadcrumbs: readonly string[]; navigation: readonly Readonly<{id: OperatorWorkspaceSection; label: string; badge: number}>[]; filters: OperatorFilters; facets: Readonly<{statuses: readonly string[]; severities: readonly string[]; producers: readonly string[]; entityTypes: readonly string[]; autonomies: readonly string[]; risks: readonly string[]; capabilities: readonly string[]; knowledgeStates: readonly string[]; actions: readonly string[]}>; total: number; filtered: number; page: number; pageSize: number; pageCount: number; rows: readonly OperatorCaseRow[]; notifications: readonly OperatorNotification[]; dashboardFingerprint: string; writes: false; persistsFilters: false; invokesExecutors: false; autoExecutes: false}>;
export const operatorExperienceSecurity = Object.freeze({pure: true, createsStores: false, createsRouters: false, invokesExecutors: false, accessesSanity: false, autoExecutes: false, persistsFilters: false, persistsAuth: false, autoAppliesKnowledge: false, writes: false} as const);
