import type {ReviewCase, ReviewJsonValue} from "../types";
import {computeUniversalFingerprint} from "../universal";
import {buildGlobalResolutionDashboard, projectGlobalDashboardCase} from "./dashboard";
import {OPERATOR_EXPERIENCE_VERSION, type OperatorCaseContext, type OperatorCaseRow, type OperatorExperienceViewModel, type OperatorFilters, type OperatorNotification, type OperatorWorkspaceSection} from "./operatorExperienceTypes";
import {buildNucleusResolutionViewModel} from "./model";

const fp = (value: unknown) => computeUniversalFingerprint(value as ReviewJsonValue);
const unique = (values: readonly string[]) => Object.freeze([...new Set(values.filter(Boolean))].sort());
const active = new Set(["analyzing", "planning", "executing", "observing"]);
const sectionLabels: Readonly<Record<OperatorWorkspaceSection, string>> = Object.freeze({dashboard: "Dashboard", priorities: "Casos prioritarios", case: "Núcleo Resolutivo IA", activity: "Actividad", knowledge: "Conocimiento"});
const defaultFilters: OperatorFilters = Object.freeze({status: "all", severity: "all", producer: "all", entityType: "all", autonomy: "all", risk: "all", capability: "all", knowledgeState: "all", actionRequired: "all", query: "", page: 1, pageSize: 8});

export function buildOperatorExperience(input: Readonly<{cases: readonly ReviewCase[]; evaluatedAt: string; activeSection?: OperatorWorkspaceSection; selectedCaseId?: string; caseContext?: OperatorCaseContext; filters?: OperatorFilters}>): OperatorExperienceViewModel {
  const filters = Object.freeze({...defaultFilters, ...input.filters}); const dashboard = buildGlobalResolutionDashboard({cases: input.cases, evaluatedAt: input.evaluatedAt});
  const projections = input.cases.map((reviewCase) => ({reviewCase, projection: projectGlobalDashboardCase(reviewCase, input.evaluatedAt), nucleus: buildNucleusResolutionViewModel({reviewCase, evaluatedAt: input.evaluatedAt})}));
  const query = (filters.query ?? "").trim().toLocaleLowerCase("es");
  const filtered = projections.filter(({reviewCase, projection, nucleus}) => (filters.status === "all" || !filters.status || projection.caseStatus === filters.status) && (filters.severity === "all" || !filters.severity || projection.severity === filters.severity) && (filters.producer === "all" || !filters.producer || projection.producer === filters.producer) && (filters.entityType === "all" || !filters.entityType || projection.entityType === filters.entityType) && (filters.autonomy === "all" || !filters.autonomy || projection.autonomy === filters.autonomy) && (filters.risk === "all" || !filters.risk || projection.risk === filters.risk) && (filters.capability === "all" || !filters.capability || projection.capabilities.includes(filters.capability)) && (filters.knowledgeState === "all" || !filters.knowledgeState || projection.knowledgeStates.includes(filters.knowledgeState)) && (filters.actionRequired === "all" || !filters.actionRequired || nucleus.primaryAction.kind === filters.actionRequired) && (!query || [projection.title, projection.caseId, reviewCase.subject.id, reviewCase.subject.sanityId, projection.producer, projection.entityType, ...projection.capabilities].filter(Boolean).join(" ").toLocaleLowerCase("es").includes(query)));
  const rank = new Map(dashboard.priorityCases.map((entry, index) => [entry.caseId, index]));
  filtered.sort((a, b) => (rank.get(a.reviewCase.id) ?? 999999) - (rank.get(b.reviewCase.id) ?? 999999) || a.reviewCase.id.localeCompare(b.reviewCase.id));
  const pageSize = Math.max(1, Math.min(50, Math.floor(filters.pageSize ?? 8))); const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const page = Math.max(1, Math.min(pageCount, Math.floor(filters.page ?? 1)));
  const rows: readonly OperatorCaseRow[] = Object.freeze(filtered.slice((page - 1) * pageSize, page * pageSize).map(({reviewCase, projection, nucleus}) => { const related = dashboard.crossCase.relations.filter((entry) => entry.caseIds.includes(reviewCase.id)); const fingerprint = fp({caseId: reviewCase.id, version: reviewCase.version, state: nucleus.state, progress: nucleus.progress, action: nucleus.primaryAction.kind}); return Object.freeze({caseId: reviewCase.id, title: reviewCase.title, state: nucleus.state, action: nucleus.primaryAction, progress: nucleus.progress, investigationSources: nucleus.evidence.sourceCount, phaseCount: nucleus.timeline.length, live: active.has(nucleus.state), blockers: projection.blockers, relatedCases: new Set(related.flatMap((entry) => entry.caseIds).filter((id) => id !== reviewCase.id)).size, fingerprint}); }));
  const notifications: OperatorNotification[] = [];
  const add = (priority: OperatorNotification["priority"], kind: OperatorNotification["kind"], caseIds: readonly string[], safeMessage: string) => { const fingerprint = fp({priority, kind, caseIds: [...caseIds].sort(), safeMessage}); notifications.push(Object.freeze({id: `operator:${fingerprint}`, priority, kind, caseIds: Object.freeze([...caseIds].sort()), safeMessage, fingerprint})); };
  const by = (predicate: (entry: typeof projections[number]) => boolean) => projections.filter(predicate).map((entry) => entry.reviewCase.id);
  const authorization = by((entry) => entry.projection.authorizationRequired); if (authorization.length) add("high", "authorization", authorization, `${authorization.length} casos requieren autorización.`);
  const reconciliation = by((entry) => entry.projection.reconciliationRequired); if (reconciliation.length) add("critical", "reconciliation", reconciliation, `${reconciliation.length} casos requieren reconciliación.`);
  const failures = by((entry) => entry.projection.blocked); if (failures.length) add("high", "failure", failures, `${failures.length} casos están bloqueados.`);
  const stale = by((entry) => entry.projection.stale && entry.projection.severity === "critical"); if (stale.length) add("high", "stale", stale, `${stale.length} casos críticos están stale.`);
  const completed = by((entry) => ["resolved", "resumed"].includes(entry.reviewCase.status)); if (completed.length) add("normal", "completed", completed, `${completed.length} casos han terminado.`);
  const shared = dashboard.bottlenecks.filter((entry) => entry.kind === "shared_blocker" || entry.kind === "shared_conflict"); if (shared.length) add("high", "shared_blocker", shared.flatMap((entry) => entry.affectedCaseIds), `${shared.length} blockers compartidos requieren coordinación.`);
  const navigation = Object.freeze((["dashboard", "priorities", "case", "activity", "knowledge"] as OperatorWorkspaceSection[]).map((id) => Object.freeze({id, label: sectionLabels[id], badge: id === "priorities" ? dashboard.summary.blocked + dashboard.summary.authorizationRequired + dashboard.summary.reconciliationRequired : id === "activity" ? dashboard.activity.recent.length : id === "knowledge" ? dashboard.knowledge.recommendationsRelevant : id === "case" ? input.selectedCaseId ? 1 : 0 : dashboard.summary.totalCases})));
  const selected = input.selectedCaseId ? projections.find((entry) => entry.reviewCase.id === input.selectedCaseId)?.reviewCase.title : undefined;
  const notificationPriority = {critical: 3, high: 2, normal: 1};
  const orderedNotifications = Object.freeze(notifications.sort((a, b) => notificationPriority[b.priority] - notificationPriority[a.priority] || a.fingerprint.localeCompare(b.fingerprint)).slice(0, 8));
  const contextBreadcrumb = input.activeSection === "case" && input.caseContext && input.caseContext !== "overview" ? [input.caseContext === "workspace" ? "Workspace" : "Timeline"] : [];
  return Object.freeze({version: OPERATOR_EXPERIENCE_VERSION, activeSection: input.activeSection ?? "dashboard", breadcrumbs: Object.freeze(["Centro de revisión", sectionLabels[input.activeSection ?? "dashboard"], ...(input.activeSection === "case" && selected ? [selected] : []), ...contextBreadcrumb]), navigation, filters, facets: Object.freeze({statuses: dashboard.facets.statuses, severities: dashboard.facets.severities, producers: dashboard.facets.producers, entityTypes: dashboard.facets.entityTypes, autonomies: dashboard.facets.autonomies, risks: dashboard.facets.risks, capabilities: dashboard.facets.capabilities, knowledgeStates: dashboard.facets.knowledgeStates, actions: unique(projections.map((entry) => entry.nucleus.primaryAction.kind))}), total: input.cases.length, filtered: filtered.length, page, pageSize, pageCount, rows, notifications: orderedNotifications, dashboardFingerprint: dashboard.dashboardFingerprint, writes: false, persistsFilters: false, invokesExecutors: false, autoExecutes: false});
}
