import type {ReviewCase, ReviewResolution} from "../types";
import {validateReviewResolution} from "../cases/validateResolution";
import {buildContextFingerprint, buildDecisionFingerprint, buildEvidenceFingerprint, buildInputFingerprint} from "./fingerprints";
import {appendOutcomeEvent, ensureOutcomeRecord, getOutcomesForCase} from "./outcomeStore";
import type {DecisionOutcomeRecord, OutcomeEventSource, OutcomeReference} from "./types";

const safe = (operation: () => void): void => { try { operation(); } catch (error) { console.error("[FFN3 outcomes] No se pudo registrar una observación secundaria.", error); } };
function resolutionIdentity(reviewCase: ReviewCase, resolution: ReviewResolution) {
  const issue = reviewCase.issues.find((item) => item.id === resolution.issueId); if (!issue) throw new Error("outcome_issue_missing");
  const producer = typeof reviewCase.context.producer === "string" ? reviewCase.context.producer : reviewCase.module;
  const entityType = resolution.type === "create_entity" ? resolution.entityType : issue.valueKind;
  const decisionFingerprint = buildDecisionFingerprint({issueType: issue.kind, entityType, operation: resolution.type, target: {caseId: reviewCase.id, issueId: issue.id, field: issue.fieldPath}, resolution, scope: {module: reviewCase.module, source: reviewCase.source}, producer, schemaVersion: reviewCase.schemaVersion});
  const id = `outcome:${reviewCase.id}:${issue.id}:${decisionFingerprint.split(":").at(-1)}`;
  return {id, issue, producer, entityType, decisionFingerprint, correlationKey: `review:${reviewCase.id}:${issue.id}`};
}
export function ensureResolutionOutcome(reviewCase: ReviewCase, resolution: ReviewResolution, source: OutcomeEventSource = "review_store"): DecisionOutcomeRecord {
  const identity = resolutionIdentity(reviewCase, resolution); const now = reviewCase.updatedAt;
  const record = ensureOutcomeRecord({id: identity.id, caseId: reviewCase.id, issueId: resolution.issueId, resolutionId: identity.decisionFingerprint, decisionFingerprint: identity.decisionFingerprint, contextFingerprint: buildContextFingerprint({module: reviewCase.module, source: reviewCase.source, subject: reviewCase.subject, producer: identity.producer}), inputFingerprint: buildInputFingerprint({currentValue: identity.issue.currentValue, expected: identity.issue.expected, fieldPath: identity.issue.fieldPath}), evidenceFingerprint: buildEvidenceFingerprint({evidence: identity.issue.evidence, candidates: identity.issue.candidates}), correlationKey: identity.correlationKey, producer: identity.producer, source: reviewCase.source, entityType: identity.entityType, issueType: identity.issue.kind, decisionType: resolution.type, reviewSchemaVersion: reviewCase.schemaVersion, createdAt: now});
  const previous = getOutcomesForCase(reviewCase.id).filter((item) => item.issueId === resolution.issueId && item.id !== record.id && item.currentStatus !== "superseded");
  for (const item of previous) appendOutcomeEvent({outcomeId: item.id, caseId: item.caseId, type: "outcome_superseded", stage: "decision", status: "superseded", source, correlationKey: item.correlationKey, idempotencyKey: `resolution-replaced:${item.id}:${record.id}`, occurredAt: now, actor: {type: "system", label: "Review store"}, operation: "replace_resolution", payload: {reason: "La resolución del mismo issue fue reemplazada."}, references: [{type: "outcome", id: record.id}]});
  appendOutcomeEvent({outcomeId: record.id, caseId: reviewCase.id, type: "outcome_created", stage: "decision", status: "pending", source, correlationKey: identity.correlationKey, idempotencyKey: `outcome-created:${record.id}`, occurredAt: now, actor: {type: "system", label: source}, operation: "observe_resolution", references: [{type: "case", id: reviewCase.id}, {type: "issue", id: resolution.issueId}]});
  appendOutcomeEvent({outcomeId: record.id, caseId: reviewCase.id, type: "resolution_recorded", stage: "decision", status: "recorded", source, correlationKey: identity.correlationKey, idempotencyKey: `resolution-recorded:${record.id}`, occurredAt: now, actor: {type: "system", label: source}, operation: resolution.type, payload: {resolutionType: resolution.type}, references: [{type: "issue", id: resolution.issueId}]});
  const validation = validateReviewResolution(reviewCase, resolution);
  appendOutcomeEvent({outcomeId: record.id, caseId: reviewCase.id, type: "resolution_validated", stage: "decision", status: validation.valid ? "valid" : "invalid", source, correlationKey: identity.correlationKey, idempotencyKey: `resolution-validated:${record.id}:${validation.valid}`, occurredAt: now, operation: "validate_resolution", validation: {valid: validation.valid, reasons: validation.valid ? ["La resolución satisface el contrato del ReviewCase."] : [validation.error]}, references: []});
  if (resolution.type === "create_entity") appendOutcomeEvent({outcomeId: record.id, caseId: reviewCase.id, type: "prepared_entity_created", stage: "application", status: "prepared_not_materialized", source, correlationKey: identity.correlationKey, idempotencyKey: `prepared-entity:${record.id}`, occurredAt: now, operation: "prepare_entity", payload: {entityType: resolution.entityType}, references: []});
  return getOutcomesForCase(reviewCase.id).find((item) => item.id === record.id) ?? record;
}
export function observeResolutionOutcome(reviewCase: ReviewCase, resolution: ReviewResolution, source: OutcomeEventSource = "review_store"): void { safe(() => { ensureResolutionOutcome(reviewCase, resolution, source); }); }
export function observeResolutionApplied(reviewCase: ReviewCase, resolution: ReviewResolution, source: OutcomeEventSource = "autonomous_resolver"): void { safe(() => { const record = ensureResolutionOutcome(reviewCase, resolution, source); appendOutcomeEvent({outcomeId: record.id, caseId: reviewCase.id, type: "resolution_applied", stage: "application", status: "applied_internally", source, correlationKey: record.correlationKey, idempotencyKey: `resolution-applied:${record.id}`, occurredAt: reviewCase.updatedAt, operation: resolution.type, references: []}); }); }
export function observeMaterialization(caseData: ReviewCase, input: {type: "materialization_started" | "materialization_succeeded" | "materialization_failed"; issueId: string; idempotencyKey: string; entityId?: string; entityType?: string; status: string; error?: {code: string; message: string; reconciliationRequired?: boolean}; occurredAt?: string}): void {
  safe(() => { const record = getOutcomesForCase(caseData.id).filter((item) => item.issueId === input.issueId && item.currentStatus !== "superseded").at(0); if (!record) return; const references: OutcomeReference[] = input.entityId ? [{type: "entity", id: input.entityId, relation: input.status}] : []; appendOutcomeEvent({outcomeId: record.id, caseId: caseData.id, type: input.type, stage: "materialization", status: input.status, source: "materialization_executor", correlationKey: record.correlationKey, idempotencyKey: input.idempotencyKey, occurredAt: input.occurredAt, actor: {type: "executor", label: "Entity creation executor"}, operation: "materialize_prepared_entity", payload: {entityType: input.entityType ?? record.entityType ?? "unknown"}, error: input.error, references}); });
}
export function observeResumeForCase(caseData: ReviewCase, input: {type: "resume_preview_generated" | "resume_started" | "resume_succeeded" | "resume_failed" | "draft_created"; idempotencyKey: string; status: string; previewFingerprint?: string; draftId?: string; documentId?: string; error?: {code: string; message: string; reconciliationRequired?: boolean}; occurredAt?: string}): void {
  safe(() => { for (const record of getOutcomesForCase(caseData.id).filter((item) => item.currentStatus !== "superseded")) { const references: OutcomeReference[] = [{type: "resume", id: input.previewFingerprint ?? `resume:${caseData.id}`}]; if (input.draftId) references.push({type: "draft", id: input.draftId}); if (input.documentId) references.push({type: "document", id: input.documentId}); appendOutcomeEvent({outcomeId: record.id, caseId: caseData.id, type: input.type, stage: input.type === "draft_created" ? "draft" : "resume", status: input.status, source: "resume_executor", correlationKey: record.correlationKey, idempotencyKey: `${input.idempotencyKey}:${record.id}`, occurredAt: input.occurredAt, actor: {type: "executor", label: "External news resume executor"}, operation: input.type, payload: {caseVersion: caseData.version, previewFingerprint: input.previewFingerprint ?? null}, error: input.error, references}); } });
}
export function observeRequirementsForCase(caseData: ReviewCase, input: {type: "requirements_inspected" | "enrichment_applied" | "structural_validation_passed" | "structural_validation_failed"; issueId: string; idempotencyKey: string; valid: boolean; reasons: string[]; occurredAt?: string}): void {
  safe(() => { const record = getOutcomesForCase(caseData.id).find((item) => item.issueId === input.issueId && item.currentStatus !== "superseded"); if (!record) return; appendOutcomeEvent({outcomeId: record.id, caseId: caseData.id, type: input.type, stage: "requirements", status: input.valid ? "valid" : "invalid", source: "schema_requirements", correlationKey: record.correlationKey, idempotencyKey: input.idempotencyKey, occurredAt: input.occurredAt, operation: input.type, validation: {valid: input.valid, reasons: input.reasons}, references: []}); });
}
