import type {InvestigationEvidence} from "../investigation";
import type {SchemaEvolutionProposal, SchemaEvolutionRisk, SchemaImpactAssessment, SchemaModelAlternative} from "./types";

const riskRank: Record<SchemaEvolutionRisk, number> = {low: 0, medium: 1, high: 2, critical: 3};
const unique = (values: string[]): string[] => [...new Set(values)].sort((left, right) => left.localeCompare(right));
const uniqueEvidence = (values: InvestigationEvidence[]): InvestigationEvidence[] => [...new Map(values.map((item) => [item.id, item])).values()].sort((left, right) => left.id.localeCompare(right.id));
function mergeImpacts(values: SchemaImpactAssessment[]): SchemaImpactAssessment[] { const groups = new Map<string, SchemaImpactAssessment[]>(); for (const item of values) groups.set(item.area, [...(groups.get(item.area) ?? []), item]); return [...groups.entries()].sort(([left], [right]) => left.localeCompare(right)).map(([, items]) => ({area: items[0].area, affected: items.some((item) => item.affected), severity: items.reduce<SchemaEvolutionRisk>((risk, item) => riskRank[item.severity] > riskRank[risk] ? item.severity : risk, "low"), reason: unique(items.map((item) => item.reason)).join(" "), verificationRequired: items.some((item) => item.verificationRequired)})); }
function normalizeAlternatives(values: SchemaModelAlternative[]): SchemaModelAlternative[] { const groups = new Map<string, SchemaModelAlternative[]>(); for (const item of values) groups.set(item.id, [...(groups.get(item.id) ?? []), item]); return [...groups.values()].map((items) => ({...items[0], benefits: unique(items.flatMap((item) => item.benefits)), risks: unique(items.flatMap((item) => item.risks)), affectedAreas: unique(items.flatMap((item) => item.affectedAreas)) as SchemaModelAlternative["affectedAreas"]})).sort((left, right) => right.score - left.score || left.id.localeCompare(right.id)); }
export function consolidateSchemaEvolutionProposals(proposals: SchemaEvolutionProposal[]): SchemaEvolutionProposal[] { const groups = new Map<string, SchemaEvolutionProposal[]>(); for (const proposal of proposals) groups.set(proposal.identity, [...(groups.get(proposal.identity) ?? []), proposal]); return [...groups.entries()].sort(([left], [right]) => left.localeCompare(right)).map(([identity, items]) => { const sourceIssueIds = unique(items.flatMap((item) => item.sourceIssueIds)); const affectedEntityKeys = unique(items.flatMap((item) => item.affectedEntityKeys)); const impacts = mergeImpacts(items.flatMap((item) => item.impacts)); const alternatives = normalizeAlternatives(items.flatMap((item) => item.alternatives)); const risk = items.reduce<SchemaEvolutionRisk>((current, item) => riskRank[item.risk] > riskRank[current] ? item.risk : current, "low"); const best = alternatives[0]; return {...items[0], id: `proposal:${identity}`, identity, sourceIssueIds, affectedEntityKeys, occurrenceCount: sourceIssueIds.length, confidence: Math.max(...items.map((item) => item.confidence)), risk, impacts, alternatives, recommendedAlternativeId: best?.id, recommendationSummary: best ? `La alternativa mejor puntuada es “${best.title}” (${best.score}/100), pero requiere decisión humana.` : items[0].recommendationSummary, facts: unique(items.flatMap((item) => item.facts)), violatedRules: unique(items.flatMap((item) => item.violatedRules)), contradictions: unique(items.flatMap((item) => item.contradictions)), evidence: uniqueEvidence(items.flatMap((item) => item.evidence)), benefits: unique(items.flatMap((item) => item.benefits)), warnings: unique(items.flatMap((item) => item.warnings))}; }); }
