import {buildSchemaEvolutionProposal} from "./buildSchemaEvolutionProposal";
import {consolidateSchemaEvolutionProposals} from "./consolidateSchemaEvolutionProposals";
import {evaluateAlternativeModels} from "./evaluateAlternativeModels";
import {evaluateEditorialImpact} from "./evaluateEditorialImpact";
import {inspectSchemaConstraints} from "./inspectSchemaConstraint";
import type {SchemaEvolutionInput, SchemaEvolutionResult} from "./types";
import {validateSchemaProposal} from "./validateSchemaProposal";
export function runSchemaEvolutionEngine(input: SchemaEvolutionInput): SchemaEvolutionResult { const generatedAt = (input.now ?? (() => new Date().toISOString()))(); if (!input.report || !Array.isArray(input.report.items)) return {caseId: "unknown", status: "invalid_input", proposals: [], outcomes: [], generatedAt, warnings: ["Entrada inválida."]}; const warnings: string[] = []; const rawProposals = inspectSchemaConstraints(input.report).map((diagnosis) => { const impacts = evaluateEditorialImpact(diagnosis, input.auditedAreas); return buildSchemaEvolutionProposal(diagnosis, impacts, evaluateAlternativeModels(diagnosis, impacts), generatedAt); }); const proposals = consolidateSchemaEvolutionProposals(rawProposals).filter((proposal) => { const validation = validateSchemaProposal(proposal); if (!validation.valid) warnings.push(...validation.errors); return validation.valid; }); return {caseId: input.report.caseId, status: proposals.length ? "proposals_ready" : "no_change_recommended", proposals, outcomes: proposals.length ? [...new Set(proposals.flatMap((proposal) => [proposal.outcome, ...proposal.impacts.filter((impact) => impact.affected && impact.area === "builders").map(() => "builder_change_required" as const), ...proposal.impacts.filter((impact) => impact.affected && impact.area === "queries").map(() => "query_change_required" as const), ...proposal.alternatives.filter((alternative) => alternative.requiresMigration).map(() => "migration_required" as const)]))] : ["no_change_recommended"], generatedAt, warnings: uniqueWarnings(warnings)}; }
const uniqueWarnings = (warnings: string[]): string[] => [...new Set(warnings)].sort((left, right) => left.localeCompare(right));
