import type {InvestigationEvidence} from "../investigation";
import type {PreparedEntityRequirementReport, RequirementResolutionConclusion, SchemaRecommendation} from "../schemaRequirements";
import type {ReviewJsonObject} from "../types";

export type SchemaEvolutionOutcome = "schema_constraint_detected" | "schema_requirement_unnecessary" | "schema_requirement_ambiguous" | "schema_split_relationship" | "schema_optional_relationship" | "schema_requires_new_entity" | "schema_requires_new_document" | "builder_change_required" | "query_change_required" | "migration_required" | "no_change_recommended";
export type SchemaEvolutionRisk = "low" | "medium" | "high" | "critical";
export type SchemaImpactArea = "builders" | "queries" | "producers" | "review" | "resume" | "materialization" | "preview" | "sanity_schema" | "existing_documents" | "public_web" | "panel_ia" | "laboratory";
export type SchemaConstraintDiagnosis = {id: string; caseId: string; issueId: string; affectedEntityKey: string; entityType: string; requirementId: string; field: string; source: string; semanticRole?: string; outcome: SchemaEvolutionOutcome; confidence: number; problem: string; facts: string[]; violatedRules: string[]; contradictions: string[]; evidence: InvestigationEvidence[]; recommendation: SchemaRecommendation};
export type SchemaImpactAssessment = {area: SchemaImpactArea; affected: boolean; severity: SchemaEvolutionRisk; reason: string; verificationRequired: boolean};
export type SchemaModelAlternative = {id: string; type: "make_optional" | "split_relationship" | "new_entity" | "new_document" | "change_semantics" | "fallback_policy" | "keep_current"; title: string; description: string; benefits: string[]; risks: string[]; score: number; requiresMigration: boolean; affectedAreas: SchemaImpactArea[]};
export type SchemaEvolutionProposal = {id: string; identity: string; caseId: string; entityType: string; field: string; outcome: SchemaEvolutionOutcome; recommendationType: SchemaRecommendation["type"]; sourceIssueIds: string[]; affectedEntityKeys: string[]; occurrenceCount: number; problem: string; confidence: number; risk: SchemaEvolutionRisk; riskReason: string; impacts: SchemaImpactAssessment[]; alternatives: SchemaModelAlternative[]; recommendedAlternativeId?: string; recommendationSummary: string; facts: string[]; violatedRules: string[]; contradictions: string[]; evidence: InvestigationEvidence[]; benefits: string[]; warnings: string[]; generatedAt: string; metadata: ReviewJsonObject};
export type SchemaEvolutionInput = {report: PreparedEntityRequirementReport; previousConclusions?: RequirementResolutionConclusion[]; auditedAreas?: Partial<Record<SchemaImpactArea, boolean>>; now?: () => string};
export type SchemaEvolutionResult = {caseId: string; status: "proposals_ready" | "no_change_recommended" | "invalid_input"; proposals: SchemaEvolutionProposal[]; outcomes: SchemaEvolutionOutcome[]; generatedAt: string; warnings: string[]};
