import {registerEditorialCapability, runEditorialAgent, type EditorialAgentFact, type EditorialCapabilityAdapter} from "../agent";
import type {ReviewJsonObject} from "../types";
import {executePreparedEntityMaterialization, previewPreparedEntityMaterialization} from "./preparedEntityMaterialization";
const fact = (key: string, value: ReviewJsonObject, source: string, now: string): EditorialAgentFact => ({key, value, source, confidence: 1, observedAt: now});
const artifact = (context: {facts: EditorialAgentFact[]}, key: string): ReviewJsonObject | undefined => context.facts.find((item) => item.key === key)?.value as ReviewJsonObject | undefined;
const capability = (manifest: EditorialCapabilityAdapter["manifest"], execute: EditorialCapabilityAdapter["execute"]): EditorialCapabilityAdapter => ({manifest: {...manifest, effects: manifest.effects.includes("create_entity") ? [...new Set([...manifest.effects, "write_review_store" as const])] : manifest.effects, idempotency: manifest.effects.includes("create_entity") ? "keyed" : manifest.effects.includes("write_review_store") ? "store_versioned" : "read_only"}, supports: (goal) => typeof goal.target.caseId === "string", execute});
const capabilities: EditorialCapabilityAdapter[] = [
  capability({id: "review.validate_prepared_entity", version: 1, description: "Valida drafts preparados contra schema real.", provides: ["prepared_entity_validated"], requires: [], effects: ["read_local", "read_external"], risk: "low", timeoutMs: 10_000, priority: 100, maxExecutionsPerRun: 1}, async (context) => { const preview = await previewPreparedEntityMaterialization(String(context.goal.target.caseId), () => context.now); const value = preview as unknown as ReviewJsonObject; return {status: "completed", producedOutcomes: ["prepared_entity_validated"], facts: [fact("prepared_entity_validated", value, "review.validate_prepared_entity", context.now)], artifact: value, reasoningSummary: `Se validaron ${preview.entityCount} entidades preparadas contra el schema real.`, evidence: preview.items.flatMap((item) => item.evidence.map((value) => ({label: item.name ?? item.issueId, source: "prepared_entity", value}))), warnings: preview.warnings}; }),
  capability({id: "review.check_entity_duplicate", version: 1, description: "Confirma el resultado de duplicados inmediatamente previo a creación.", provides: ["entity_duplicate_checked"], requires: ["prepared_entity_validated"], effects: ["read_external"], risk: "low", timeoutMs: 10_000, priority: 90, maxExecutionsPerRun: 1}, async (context) => { const value = artifact(context, "prepared_entity_validated") ?? {}; return {status: "completed", producedOutcomes: ["entity_duplicate_checked"], facts: [fact("entity_duplicate_checked", value, "review.check_entity_duplicate", context.now)], artifact: value, reasoningSummary: "La búsqueda final de duplicados quedó registrada en la preview validada.", evidence: [], warnings: []}; }),
  capability({id: "sanity.create_prepared_entity", version: 1, description: "Crea entidades individuales con executor inyectado e idempotencia.", provides: ["entity_created"], requires: ["entity_duplicate_checked"], effects: ["read_local", "read_external", "create_entity"], risk: "high", timeoutMs: 30_000, priority: 80, maxExecutionsPerRun: 1}, async (context) => { const result = await executePreparedEntityMaterialization(String(context.goal.target.caseId), {confirmed: true, now: () => context.now}); const value = result as unknown as ReviewJsonObject; return {status: result.status === "failed" || result.status === "blocked" ? "failed" : "completed", producedOutcomes: ["entity_created"], facts: [fact("entity_created", value, "sanity.create_prepared_entity", context.now)], artifact: value, reasoningSummary: `Materialización controlada terminada con estado ${result.status}.`, evidence: [], warnings: result.warnings}; }),
  capability({id: "review.replace_prepared_entity_with_reference", version: 1, description: "Verifica la sustitución atómica por referencias reales.", provides: ["entity_reference_available", "review_resolution_replaced"], requires: ["entity_created"], effects: ["write_review_store"], risk: "high", timeoutMs: 5_000, priority: 70, maxExecutionsPerRun: 1}, async (context) => { const value = artifact(context, "entity_created") ?? {}; return {status: "completed", producedOutcomes: ["entity_reference_available", "review_resolution_replaced"], facts: [fact("entity_reference_available", value, "review.replace_prepared_entity_with_reference", context.now), fact("review_resolution_replaced", value, "review.replace_prepared_entity_with_reference", context.now)], artifact: value, reasoningSummary: "La materialización sustituyó create_entity por link_reference mediante la API pública del store.", evidence: [], warnings: []}; }),
  capability({id: "review.regenerate_resume_preview", version: 1, description: "Registra la preview regenerada sin reanudar.", provides: ["resume_preview_regenerated"], requires: ["review_resolution_replaced"], effects: ["read_local"], risk: "none", timeoutMs: 5_000, priority: 60, maxExecutionsPerRun: 1}, async (context) => { const value = artifact(context, "entity_created") ?? {}; return {status: "completed", producedOutcomes: ["resume_preview_regenerated"], facts: [fact("resume_preview_regenerated", value, "review.regenerate_resume_preview", context.now)], artifact: value, reasoningSummary: "La preview se regeneró; no se ejecutó la reanudación.", evidence: [], warnings: []}; }),
];
export function registerPreparedEntityCapabilities(): () => void { const cleanups = capabilities.map(registerEditorialCapability); return () => cleanups.reverse().forEach((cleanup) => cleanup()); }
export function runPreparedEntityAgent(caseId: string, options: {execute?: boolean} = {}) { return runEditorialAgent({id: `materialize:${caseId}`, objective: "Validar y materializar entidades preparadas sin publicar ni reanudar.", target: {caseId}, requiredOutcomes: [options.execute ? "resume_preview_regenerated" : "entity_duplicate_checked"]}, options.execute ? {policy: {allowedEffects: ["read_local", "read_external", "write_review_store", "create_entity"], maximumRisk: "high"}} : {}); }
