import {registerEditorialCapability, runEditorialAgent, type EditorialAgentFact, type EditorialCapabilityAdapter} from "../agent";
import type {ReviewJsonObject} from "../types";
import {previewPreparedEntityMaterialization} from "./preparedEntityMaterialization";
const fact = (key: string, value: ReviewJsonObject, source: string, now: string): EditorialAgentFact => ({key, value, source, confidence: 1, observedAt: now});
const capability = (manifest: EditorialCapabilityAdapter["manifest"], execute: EditorialCapabilityAdapter["execute"]): EditorialCapabilityAdapter => ({manifest: {...manifest, effects: manifest.effects.includes("create_entity") ? [...new Set([...manifest.effects, "write_review_store" as const])] : manifest.effects, idempotency: manifest.effects.includes("create_entity") ? "keyed" : manifest.effects.includes("write_review_store") ? "store_versioned" : "read_only"}, supports: (goal) => typeof goal.target.caseId === "string", execute});
const capabilities: EditorialCapabilityAdapter[] = [
  capability({id: "review.validate_prepared_entity", version: 2, description: "Valida drafts y expone el bloqueo del guard universal sin discovery ni escritura.", provides: ["prepared_entity_validated"], requires: [], effects: ["read_local"], risk: "none", timeoutMs: 10_000, priority: 100, maxExecutionsPerRun: 1}, async (context) => { const preview = await previewPreparedEntityMaterialization(String(context.goal.target.caseId), () => context.now); const value = preview as unknown as ReviewJsonObject; return {status: "completed", producedOutcomes: ["prepared_entity_validated"], facts: [fact("prepared_entity_validated", value, "review.validate_prepared_entity", context.now)], artifact: value, reasoningSummary: `Se validaron ${preview.entityCount} entidades; la creación heredada permanece bloqueada.`, evidence: preview.items.flatMap((item) => item.evidence.map((value) => ({label: item.name ?? item.issueId, source: "prepared_entity", value}))), warnings: preview.warnings}; }),
];
export function registerPreparedEntityCapabilities(): () => void { const cleanups = capabilities.map(registerEditorialCapability); return () => cleanups.reverse().forEach((cleanup) => cleanup()); }
export function runPreparedEntityAgent(caseId: string, options: {execute?: boolean} = {}) { return runEditorialAgent({id: `materialize:${caseId}`, objective: options.execute ? "Validar entidades preparadas; la creación solicitada permanece bloqueada por el guard universal." : "Validar entidades preparadas y exponer el estado del guard universal.", target: {caseId}, requiredOutcomes: ["prepared_entity_validated"]}, {policy: {allowedEffects: ["read_local"], maximumRisk: "none"}}); }
