import type {ReactElement} from "react";
import type {GlobalResolutionDashboardViewModel} from "../nucleus";

const relationLabels = Object.freeze({shared_entity: "Entidad compartida", possible_duplicate_case: "Posible duplicado", shared_event: "Evento compartido", shared_organization: "Organización compartida", shared_fighter: "Luchador compartido", shared_news: "Noticia compartida", shared_resolution: "Resolución compartida", shared_transaction: "Transacción compartida", shared_knowledge: "Conocimiento compartido", shared_conflict: "Conflicto compartido", dependency_chain: "Dependencia", merge_candidate: "Revisión conjunta", blocked_by_other_case: "Bloqueado por otro caso"});
const bottleneckLabels = Object.freeze({capability_blocked: "Capability bloqueante", missing_executor: "Executor ausente", repeated_authorization: "Autorización repetida", recurring_reconciliation: "Reconciliación recurrente", stale_cases: "Casos stale", unsupported_entity_type: "Tipo unsupported", shared_conflict: "Conflicto compartido", shared_blocker: "Blocker compartido"});

export default function GlobalResolutionDashboardDetails({model}: {model: GlobalResolutionDashboardViewModel}): ReactElement {
  return <div className="global-dashboard-heavy-sections">
    <section aria-labelledby="global-dashboard-cross-case"><div className="review-row review-row-wrap"><h4 id="global-dashboard-cross-case">Inteligencia transversal</h4><span className="review-badge">{model.crossCase.clusters.length} clusters</span></div><dl className="global-dashboard-mini-metrics"><div><dt>Casos relacionados</dt><dd>{model.crossCase.relatedCaseCount}</dd></div><div><dt>Duplicados</dt><dd>{model.crossCase.duplicateCandidateCount}</dd></div><div><dt>Blockers compartidos</dt><dd>{model.crossCase.sharedBlockerCount}</dd></div><div><dt>Oportunidades</dt><dd>{model.crossCase.coordinatedResolutionOpportunities}</dd></div></dl>{model.crossCase.relations.length ? <ol>{model.crossCase.relations.map((relation) => <li key={relation.relationId}><strong>{relationLabels[relation.kind]}</strong><span>{relation.safeReason}</span><small>{relation.caseIds.length} casos · impacto {relation.rank.impact} · rank {relation.rank.total}</small></li>)}</ol> : <p className="review-muted">Sin relaciones confirmadas para el filtro actual.</p>}<small>Advisory-only. Los clusters nunca fusionan casos ni comparten autorizaciones.</small></section>

    <section aria-labelledby="global-dashboard-bottlenecks"><div className="review-row review-row-wrap"><h4 id="global-dashboard-bottlenecks">Cuellos de botella</h4><span className="review-badge">{model.bottlenecks.length}</span></div>{model.bottlenecks.length ? <ol>{model.bottlenecks.map((entry) => <li key={entry.bottleneckId} className={`dashboard-bottleneck-${entry.severity}`}><strong>{bottleneckLabels[entry.kind]}</strong><span>{entry.safeCause}</span><small>{entry.requiredAction}</small><small>{entry.count} casos afectados</small></li>)}</ol> : <p className="review-muted">No se detectan cuellos de botella reales en este alcance.</p>}</section>

    <section aria-labelledby="global-dashboard-knowledge"><div className="review-row review-row-wrap"><h4 id="global-dashboard-knowledge">Conocimiento</h4><span className="review-badge">advisory-only</span></div><dl className="global-dashboard-mini-metrics"><div><dt>Vigente</dt><dd>{model.knowledge.current}</dd></div><div><dt>En revisión</dt><dd>{model.knowledge.underReview}</dd></div><div><dt>Contradictorio</dt><dd>{model.knowledge.contradictory}</dd></div><div><dt>Invalidado</dt><dd>{model.knowledge.invalidated}</dd></div><div><dt>Recomendaciones</dt><dd>{model.knowledge.recommendationsRelevant}</dd></div><div><dt>Aprendizaje reciente</dt><dd>{model.knowledge.recentLearning}</dd></div></dl><p className="review-muted">La experiencia histórica nunca sustituye la evidencia actual.</p></section>

    <section aria-labelledby="global-dashboard-activity"><div className="review-row review-row-wrap"><h4 id="global-dashboard-activity">Actividad reciente</h4><span className="review-badge">{model.activity.recent.length} eventos</span></div><dl className="global-dashboard-mini-metrics">{Object.entries(model.activity.counts).map(([kind, count]) => <div key={kind}><dt>{kind.replace(/_/g, " ")}</dt><dd>{count}</dd></div>)}</dl>{model.timeline.length ? <ol className="global-dashboard-timeline">{model.timeline.map((entry) => <li key={entry.eventId}><strong>{entry.caseTitle}</strong><span>{entry.safeSummary}</span><small>{new Date(entry.occurredAt).toLocaleString("es-ES")} · {entry.kind.replace(/_/g, " ")}</small></li>)}</ol> : <p className="review-muted">No hay actividad para el filtro actual.</p>}</section>
  </div>;
}
