import {useRef, useState, type ReactElement} from "react";
import {registerReconciliationReviewCase} from "../cases";
import type {EntityKind} from "../types";
import type {ReviewCase} from "../../types";

function endpoint(): string { const configured = import.meta.env?.VITE_FFN3_API_BASE_URL; const base = typeof configured === "string" && configured.trim() ? configured.trim().replace(/\/+$/, "") : "http://localhost:3000"; return `${base}/api/review/entity-reconciliation/scan`; }
export default function ReconciliationScanControls(): ReactElement {
  const [kind, setKind] = useState<EntityKind>("fighter"); const [scope, setScope] = useState<"all" | "recent">("all"); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState("El escaneo sólo se ejecuta mediante esta acción explícita."); const controller = useRef<AbortController>();
  async function scan(): Promise<void> { controller.current?.abort(); const abort = new AbortController(); controller.current = abort; setBusy(true); setFeedback("Escaneando proyección read-only…"); try { const response = await fetch(endpoint(), {method: "POST", headers: {"Content-Type": "application/json"}, credentials: "omit", cache: "no-store", signal: abort.signal, body: JSON.stringify({version: 1, kind, scope, limit: 200, maxGroups: 40, maxBlockSize: 20})}); const body = await response.json() as {ok?: boolean; reasonCode?: string; cases?: ReviewCase[]; scan?: {status?: string; groups?: unknown[]}}; if (!response.ok || body.ok !== true || !Array.isArray(body.cases)) throw new Error(body.reasonCode ?? "scan_unavailable"); let added = 0; for (const reviewCase of body.cases) if (registerReconciliationReviewCase(reviewCase).status === "accepted") added += 1; setFeedback(`Lectura ${body.scan?.status ?? "desconocida"}: ${body.cases.length} grupos, ${added} casos nuevos. Sin mutaciones realizadas.`); } catch { setFeedback(abort.signal.aborted ? "Escaneo cancelado sin mutaciones." : "No se pudo completar el escaneo read-only."); } finally { if (controller.current === abort) setBusy(false); } }
  return <section className="review-subsection" aria-label="Detección de duplicados existentes"><div className="review-row review-row-wrap"><div><p className="review-kicker">AU5 · Sólo lectura</p><h3 className="review-subtitle">Detectar duplicados existentes</h3></div><label>Tipo<select value={kind} disabled={busy} onChange={(event) => setKind(event.target.value as EntityKind)}><option value="fighter">Luchadores</option><option value="event">Eventos</option><option value="organization">Organizaciones</option><option value="weight_category">Categorías de peso</option></select></label><label>Alcance<select value={scope} disabled={busy} onChange={(event) => setScope(event.target.value as "all" | "recent")}><option value="all">Todo el corpus (limitado)</option><option value="recent">Últimos 180 días</option></select></label><button className="review-button" type="button" disabled={busy} onClick={() => void scan()}>{busy ? "Escaneando…" : "Iniciar scan limitado"}</button>{busy ? <button className="review-button review-button-secondary" type="button" onClick={() => controller.current?.abort()}>Cancelar</button> : null}</div><p className="review-muted" role="status">{feedback}</p></section>;
}
