import {createClient} from "@sanity/client";
import {NextResponse} from "next/server";
import {executeReconciliationScanAction, reconciliationReasonCode, type CorpusScanRequest, type EntityCorpusReadAdapter, type EntityKind} from "@/_laboratorio/laboratorio-ia/src/review/entityReconciliation";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
const MAX_BODY_BYTES = 4 * 1024;
const configuredOrigin = process.env.REVIEW_LAB_ORIGIN?.trim();
const allowedOrigins = new Set([configuredOrigin, "http://localhost:5173", "http://127.0.0.1:5173"].filter((value): value is string => Boolean(value)));
const queries: Record<EntityKind, string> = {
  fighter: `*[_type == "luchador" && ($scope == "all" || _updatedAt >= $recentSince) && (!defined($cursor) || _id > $cursor)] | order(_id asc)[0...251]{_id,_rev,nombre,slug,apodo,aliases,externalIds,"disciplina":disciplina._ref,"organizacion":organizacion._ref,"categoriaPeso":categoriaPeso._ref,"referenceImpact":{"status":"known","count":count(*[_type=="combate" && (luchadorRojo._ref==^._id || luchadorAzul._ref==^._id || ganador._ref==^._id)])+count(*[_type=="noticia" && ^._id in luchadoresRelacionados[]._ref]),"sampleDocumentIds":array::unique((*[_type=="combate" && (luchadorRojo._ref==^._id || luchadorAzul._ref==^._id || ganador._ref==^._id)]|order(_id asc)[0...6]._id)+(*[_type=="noticia" && ^._id in luchadoresRelacionados[]._ref]|order(_id asc)[0...6]._id))[0...12]}}`,
  event: `*[_type == "evento" && ($scope == "all" || _updatedAt >= $recentSince) && (!defined($cursor) || _id > $cursor)] | order(_id asc)[0...251]{_id,_rev,nombre,slug,aliases,externalIds,fecha,"organizacion":organizacion._ref,"disciplina":disciplina._ref,recinto,ciudad,pais,"referenceImpact":{"status":"known","count":count(*[_type=="combate" && evento._ref==^._id])+count(*[_type=="noticia" && eventoRelacionado._ref==^._id]),"sampleDocumentIds":array::unique((*[_type=="combate" && evento._ref==^._id]|order(_id asc)[0...6]._id)+(*[_type=="noticia" && eventoRelacionado._ref==^._id]|order(_id asc)[0...6]._id))[0...12]}}`,
  organization: `*[_type == "organizacion" && ($scope == "all" || _updatedAt >= $recentSince) && (!defined($cursor) || _id > $cursor)] | order(_id asc)[0...251]{_id,_rev,nombre,slug,aliases,externalIds,paisOrigen,sitioWeb,"disciplinas":disciplinas[]._ref,"referenceImpact":{"status":"known","count":count(*[_type=="evento" && organizacion._ref==^._id])+count(*[_type=="luchador" && organizacion._ref==^._id])+count(*[_type=="noticia" && organizacionRelacionada._ref==^._id]),"sampleDocumentIds":array::unique((*[_type=="evento" && organizacion._ref==^._id]|order(_id asc)[0...4]._id)+(*[_type=="luchador" && organizacion._ref==^._id]|order(_id asc)[0...4]._id)+(*[_type=="noticia" && organizacionRelacionada._ref==^._id]|order(_id asc)[0...4]._id))[0...12]}}`,
  weight_category: `*[_type == "categoriaPeso" && ($scope == "all" || _updatedAt >= $recentSince) && (!defined($cursor) || _id > $cursor)] | order(_id asc)[0...251]{_id,_rev,nombre,slug,aliases,externalIds,"disciplina":disciplina._ref,modalidad,grupoEdad,sexo,tipoLimite,limitePeso,unidad,"referenceImpact":{"status":"known","count":count(*[_type=="combate" && categoriaPeso._ref==^._id])+count(*[_type=="luchador" && categoriaPeso._ref==^._id]),"sampleDocumentIds":array::unique((*[_type=="combate" && categoriaPeso._ref==^._id]|order(_id asc)[0...6]._id)+(*[_type=="luchador" && categoriaPeso._ref==^._id]|order(_id asc)[0...6]._id))[0...12]}}`,
};
const sanity = createClient({projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!, dataset: process.env.NEXT_PUBLIC_SANITY_DATASET!, apiVersion: process.env.NEXT_PUBLIC_SANITY_API_VERSION || "2025-03-01", token: process.env.SANITY_API_READ_TOKEN, useCdn: false, perspective: "raw"});
const responseHeaders = (origin: string | null) => ({"Cache-Control": "no-store", ...(origin && allowedOrigins.has(origin) ? {"Access-Control-Allow-Origin": origin, Vary: "Origin"} : {})});
const reply = (body: Record<string, unknown>, status: number, origin: string | null) => NextResponse.json(body, {status, headers: responseHeaders(origin)});
const originAllowed = (request: Request) => !request.headers.get("origin") || allowedOrigins.has(request.headers.get("origin")!);

export function OPTIONS(request: Request) { const origin = request.headers.get("origin"); if (!originAllowed(request)) return new NextResponse(null, {status: 403}); return new NextResponse(null, {status: 204, headers: {...responseHeaders(origin), "Access-Control-Allow-Methods": "POST, OPTIONS", "Access-Control-Allow-Headers": "Content-Type", "Access-Control-Max-Age": "600"}}); }
export async function POST(request: Request) {
  const origin = request.headers.get("origin"); if (!originAllowed(request)) return reply({ok: false, code: "origin_forbidden"}, 403, origin);
  if (Number(request.headers.get("content-length") ?? 0) > MAX_BODY_BYTES) return reply({ok: false, code: "request_too_large"}, 413, origin);
  try {
    const raw = await request.text(); if (new TextEncoder().encode(raw).byteLength > MAX_BODY_BYTES) return reply({ok: false, code: "request_too_large"}, 413, origin);
    const body: unknown = JSON.parse(raw);
    const adapter: EntityCorpusReadAdapter = {adapterId: "sanity.read-only.v1", supports: (kind) => Boolean(queries[kind]), async read(scanRequest: CorpusScanRequest, signal) { const recentSince = new Date(Date.now() - 180 * 24 * 60 * 60 * 1_000).toISOString(); const records = await sanity.fetch<unknown[]>(queries[scanRequest.kind], {scope: scanRequest.scope, recentSince, cursor: scanRequest.cursor ?? null}, {perspective: "raw", signal}); const bounded = records.slice(0, scanRequest.limit + 1); const truncated = bounded.length > scanRequest.limit; const visible = bounded.slice(0, scanRequest.limit); return {status: truncated ? "truncated" : "complete", records: visible, cursor: truncated ? String((visible.at(-1) as {_id?: string})?._id ?? "") : undefined, warnings: truncated ? ["El lote alcanzó el límite configurado."] : [], provenance: {adapterId: "sanity.read-only.v1", capability: "entity_reconciliation_scan"}}; }};
    const result = await executeReconciliationScanAction(adapter, body, request.signal); return reply(result, 200, origin);
  } catch (error) { if (request.signal.aborted) return reply({ok: false, code: "cancelled", reasonCode: "scan_cancelled"}, 499, origin); const invalid = error instanceof Error && (error.message.startsWith("invalid_") || error.message.startsWith("unexpected_")); const code = invalid ? "invalid_request" : "scan_unavailable"; return reply({ok: false, code, reasonCode: reconciliationReasonCode(error, code)}, invalid ? 400 : 503, origin); }
}
