import {buildUniversalExecutionPlan, type ReviewEffect, type UniversalExecutionPlan, type UniversalReviewInput} from "../universal";
import type {GlobalResolutionPlan} from "./types";
import {topologicalSortResolutionGraph} from "../resolutionGraph";
import {capabilityForOperation} from "./capabilities";

export type GlobalUniversalBridgeResult = {sourcePlanId: string; sourcePlanFingerprint: string; sourceIdempotencyKey: string; executionAllowed: boolean; orderedOperationIds: string[]; effects: ReviewEffect[]; mappedCapabilities: Array<{operationId: string; capability?: string}>; requiredCapabilities: string[]; missingCapabilities: string[]; universalPlan?: UniversalExecutionPlan; blockers: string[]};

export function adaptGlobalResolutionPlanToUniversal(plan: GlobalResolutionPlan, input: {reviewInput?: UniversalReviewInput; now?: () => string} = {}): GlobalUniversalBridgeResult {
  const order = topologicalSortResolutionGraph(plan.graph); const blockers = [...plan.blockers.map((blocker) => blocker.code), ...order.errors.map((error) => error.code)];
  const effects: ReviewEffect[] = [];
  for (const id of order.nodeIds) { const operation = plan.operations.find((candidate) => candidate.id === id); if (!operation) continue; if (operation.kind === "create_entity" && operation.payload && typeof operation.payload === "object" && !Array.isArray(operation.payload)) effects.push({id: operation.id, type: "create_entity", entityType: operation.entityType, payload: operation.payload}); else if (operation.kind === "reuse_entity" && operation.target?.entityId) effects.push({id: operation.id, type: "reuse_entity", entityType: operation.entityType, entityId: operation.target.entityId}); else if (operation.kind === "replace_reference" && operation.target?.fieldPath) effects.push({id: operation.id, type: "replace_reference", path: operation.target.fieldPath === "fighter" ? "luchadoresRelacionados" : operation.target.fieldPath, referenceId: operation.target.entityId ?? `projected:${operation.entityType}:${operation.id}`}); }
  const mappedCapabilities = order.nodeIds.map((id) => { const operation = plan.operations.find((candidate) => candidate.id === id); return {operationId: id, capability: operation ? capabilityForOperation(operation) : undefined}; }); const requiredCapabilities = [...new Set([...plan.requiredCapabilities, ...mappedCapabilities.flatMap((item) => item.capability ? [item.capability] : [])])].sort(); const missingCapabilities = requiredCapabilities.filter((capability) => !plan.policy.availableCapabilities.includes(capability)); const executionAllowed = plan.executable && !blockers.length && !missingCapabilities.length;
  let universalPlan: UniversalExecutionPlan | undefined;
  const ambiguous = blockers.includes("ambiguous_entity_candidate");
  if (input.reviewInput && effects.length && !ambiguous) universalPlan = buildUniversalExecutionPlan({reviewCase: {id: plan.caseId, version: plan.caseVersion, subject: {type: plan.graph.nodes[0]?.operation.entityType ?? "unknown"}, context: {}}, reviewInput: input.reviewInput, effects, postconditions: effects.map((effect, index) => ({id: `post:${effect.id}`, kind: "projected_effect", description: "Efecto proyectado pendiente de ejecución real.", required: true, effectIndexes: [index]})), requiredCapabilities, now: input.now});
  return {sourcePlanId: plan.id, sourcePlanFingerprint: plan.fingerprint, sourceIdempotencyKey: plan.idempotencyKey, executionAllowed, orderedOperationIds: order.nodeIds, effects, mappedCapabilities, requiredCapabilities, missingCapabilities, universalPlan, blockers};
}
