import {validatePreparedEntity} from "../materialization/validatePreparedEntity";
import {validateExternalNewsResumePayload} from "../resume/externalNews/validateExternalNewsResumePayload";
import {validateGlobalResolutionPlan} from "./validateGlobalResolutionPlan";
import {capabilityForOperation, pilotCapabilityRegistry, type CapabilitySupportLevel, type GlobalResolutionCapabilityRegistry} from "./capabilities";
import type {GlobalResolutionBlocker, GlobalResolutionPlan} from "./types";
import type {ReviewCase, ReviewJsonObject} from "../types";
import type {OperationEvidence} from "../entityOperations";

export type SimulationFighterCandidate = {id: string; name: string; aliases?: string[]; disciplineId?: string; organizationId?: string};
export type SimulationPreparedEntity = {issueId: string; entityType: "fighter"; draft: ReviewJsonObject};
export type ProducerSimulationContract = {producer: string; supportsSimulation: boolean; allowsProjectedReferences: boolean};
export type GlobalResolutionSimulationContext = {reviewCase: ReviewCase; preparedEntities: SimulationPreparedEntity[]; fighterCandidates: SimulationFighterCandidate[]; newsPayload?: ReviewJsonObject; producerContracts: ProducerSimulationContract[]; capabilityRegistry?: GlobalResolutionCapabilityRegistry};
export type ResolutionNodeSimulationResult = {nodeId: string; capability?: string; support: CapabilitySupportLevel | "missing"; status: "simulated" | "blocked" | "contract_only"; input: ReviewJsonObject; evidence: OperationEvidence[]; decision?: "reuse_candidate" | "create_candidate" | "blocked_ambiguous" | "blocked_missing_requirements"; output?: ReviewJsonObject; projectedEffect?: ReviewJsonObject; blockers: GlobalResolutionBlocker[]; warnings: string[]; explanation: string};
export type GlobalResolutionSimulationResult = {planId: string; intentFingerprint: string; structurallyValid: boolean; simulatable: boolean; executable: false; state: "structurally_valid" | "simulatable" | "simulation_blocked" | "execution_blocked"; nodeResults: ResolutionNodeSimulationResult[]; blockers: GlobalResolutionBlocker[]; warnings: string[]; requiredCapabilities: string[]; missingCapabilities: string[]; projectedEffects: ReviewJsonObject[]; projectedResume?: ReviewJsonObject};

const block = (code: GlobalResolutionBlocker["code"], message: string, operationId?: string): GlobalResolutionBlocker => ({code, message, severity: "blocking", scope: "execution", operationId, evidence: [], explanation: message, requiredAction: "Completar el contexto de simulación y volver a intentarlo."});
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const object = (value: unknown): ReviewJsonObject | undefined => value && typeof value === "object" && !Array.isArray(value) ? value as ReviewJsonObject : undefined;

export function simulateGlobalResolutionPlan(plan: GlobalResolutionPlan, context: GlobalResolutionSimulationContext): GlobalResolutionSimulationResult {
  const validation = validateGlobalResolutionPlan(plan); const registry = context.capabilityRegistry ?? pilotCapabilityRegistry;
  const all: GlobalResolutionBlocker[] = validation.valid ? [] : validation.errors.map((error) => block("invalid_planning_input", error.message));
  const results: ResolutionNodeSimulationResult[] = []; const projectedEffects: ReviewJsonObject[] = []; let projectedFighterId: string | undefined; let projectedPayload = context.newsPayload ? JSON.parse(JSON.stringify(context.newsPayload)) as ReviewJsonObject : undefined;
  for (const node of plan.graph.nodes) {
    const operation = node.operation; const capability = capabilityForOperation(operation); const descriptor = capability ? registry.get(capability) : undefined; const payload = object(operation.payload);
    const base = {nodeId: node.id, capability, support: descriptor?.support ?? "missing" as CapabilitySupportLevel | "missing", input: {operationId: operation.id, kind: operation.kind, entityType: operation.entityType, payload: payload ?? null}, evidence: [...operation.evidence], blockers: [] as GlobalResolutionBlocker[], warnings: [] as string[]};
    if (!descriptor) { const blocker = block("missing_required_capability", `Falta la capacidad ${capability ?? "desconocida"}.`, node.id); all.push(blocker); results.push({...base, status: "blocked", blockers: [blocker], explanation: blocker.message}); continue; }
    if (!descriptor.operationKinds.includes(operation.kind)) { const blocker = block("unsupported_operation", `La capacidad ${capability} no soporta ${operation.kind}.`, node.id); all.push(blocker); results.push({...base, status: "blocked", blockers: [blocker], explanation: blocker.message}); continue; }
    if (descriptor.support === "contract_only") { const blocker = block("operation_not_executable", `${capability} solo es contractual.`, node.id); all.push(blocker); results.push({...base, status: "contract_only", blockers: [blocker], explanation: blocker.message}); continue; }
    if (capability === "validate:luchador_prepared") {
      const prepared = context.preparedEntities.find((item) => item.issueId === (payload?.preparedEntity && object(payload.preparedEntity)?.issueId));
      const fallback = context.preparedEntities.find((item) => item.entityType === "fighter");
      const checked = prepared ?? fallback; const valid = checked ? validatePreparedEntity({issueId: checked.issueId, entityType: checked.entityType, draft: checked.draft}) : undefined;
      if (!valid?.valid || !valid.entity) { const blocker = block("schema_requirement_missing", valid?.errors.join(" ") || "Falta entidad preparada.", node.id); all.push(blocker); results.push({...base, status: "blocked", decision: "blocked_missing_requirements", blockers: [blocker], explanation: blocker.message}); }
      else results.push({...base, status: "simulated", output: {identityKey: valid.entity.identityKey, payload: valid.entity.sanityPayload}, explanation: "El luchador preparado es válido para simulación."});
    } else if (capability === "find:luchador" || capability === "reuse:luchador" || capability === "create:luchador") {
      const prepared = context.preparedEntities.find((item) => item.entityType === "fighter"); const identity = prepared && typeof prepared.draft.identityKey === "string" ? prepared.draft.identityKey : ""; const name = prepared && typeof prepared.draft.name === "string" ? prepared.draft.name : ""; const discipline = prepared && typeof prepared.draft.disciplineId === "string" ? prepared.draft.disciplineId : ""; const organization = prepared && Array.isArray(prepared.draft.organizationIds) ? prepared.draft.organizationIds[0] : "";
      const matches = context.fighterCandidates.filter((candidate) => (normalize(candidate.name) === normalize(name) || candidate.aliases?.some((alias) => normalize(alias) === normalize(name))) && candidate.disciplineId === discipline && candidate.organizationId === organization);
      if (matches.length > 1) { const blocker = block("ambiguous_entity_candidate", "Hay varios candidatos de luchador equivalentes.", node.id); all.push(blocker); results.push({...base, status: "blocked", decision: "blocked_ambiguous", blockers: [blocker], explanation: blocker.message}); }
      else if (matches.length === 1) { projectedFighterId = matches[0].id; results.push({...base, status: "simulated", decision: "reuse_candidate", output: {entityId: matches[0].id, identityKey: identity}, explanation: "Existe un candidato reutilizable inequívoco."}); }
      else { projectedFighterId = `projected:luchador:${operation.id}`; const projectedEffect = {type: "create_entity", entityType: "luchador", referenceId: projectedFighterId, provisional: true}; projectedEffects.push(projectedEffect); results.push({...base, status: "simulated", decision: "create_candidate", output: {entityId: projectedFighterId, provisional: true, identityKey: identity}, projectedEffect, explanation: "No hay candidato; se proyecta creación sin escribir."}); }
    } else if (capability === "replace_reference:noticia:luchador") {
      if (!projectedFighterId || !projectedPayload) { const blocker = block("unresolved_dependency", "No existe luchador resuelto o payload de noticia para proyectar la referencia.", node.id); all.push(blocker); results.push({...base, status: "blocked", blockers: [blocker], explanation: blocker.message}); }
      else { const current = Array.isArray(projectedPayload.luchadoresRelacionados) ? projectedPayload.luchadoresRelacionados.filter((item): item is string => typeof item === "string") : []; projectedPayload.luchadoresRelacionados = [...new Set([...current, projectedFighterId])]; const projectedEffect = {type: "replace_reference", path: "luchadoresRelacionados", referenceId: projectedFighterId, provisional: projectedFighterId.startsWith("projected:")}; projectedEffects.push(projectedEffect); results.push({...base, status: "simulated", output: {referenceId: projectedFighterId, provisional: projectedFighterId.startsWith("projected:")}, projectedEffect, explanation: "La referencia se proyectó sin eliminar referencias existentes."}); }
    } else if (capability === "validate:noticia") {
      if (!projectedPayload) { const blocker = block("missing_snapshot", "No hay payload de noticia inyectado para validar.", node.id); all.push(blocker); results.push({...base, status: "blocked", blockers: [blocker], explanation: blocker.message}); }
      else { const application = {caseId: context.reviewCase.id, originalPayload: projectedPayload, resultingPayload: projectedPayload, applied: [], metadata: [], skipped: [], failed: [], warnings: [], preparedEntities: [], generatedAt: "simulation"}; const checked = validateExternalNewsResumePayload(projectedPayload, context.reviewCase, application); const referenceIds = Array.isArray(projectedPayload.luchadoresRelacionados) ? projectedPayload.luchadoresRelacionados.filter((id): id is string => typeof id === "string") : []; const hasProjected = referenceIds.some((id) => id.startsWith("projected:")); const contract = context.producerContracts.find((item) => item.producer === plan.producer); if (!checked.valid || (hasProjected && !contract?.allowsProjectedReferences)) { const blocker = block("unsafe_resume", checked.errors.map((error) => error.message).join(" ") || "La referencia provisional no está autorizada por el contrato.", node.id); all.push(blocker); results.push({...base, status: "blocked", blockers: [blocker], explanation: blocker.message}); } else results.push({...base, status: "simulated", output: {valid: true, projectedReference: hasProjected}, explanation: "El payload es reconstruible bajo el contrato de simulación."}); }
    } else if (capability?.startsWith("resume:")) {
      const contract = context.producerContracts.find((item) => item.producer === plan.producer); const prior = results.every((result) => result.status === "simulated"); const sameCase = context.reviewCase.id === plan.caseId && context.reviewCase.version === plan.caseVersion; const contextProducer = typeof context.reviewCase.context.producer === "string" ? context.reviewCase.context.producer : plan.producer; const contextOperation = typeof context.reviewCase.context.operation === "string" ? context.reviewCase.context.operation : plan.originalOperation; if (!contract?.supportsSimulation || !prior || !sameCase || contextProducer !== plan.producer || contextOperation !== plan.originalOperation || !context.newsPayload) { const blocker = block("unsafe_resume", "La reanudación no cumple contrato, caso, productor, operación, snapshot o dependencias de simulación.", node.id); all.push(blocker); results.push({...base, status: "blocked", blockers: [blocker], explanation: blocker.message}); } else results.push({...base, status: "simulated", output: {producer: plan.producer, operation: plan.originalOperation, caseVersion: plan.caseVersion, fingerprint: plan.fingerprint, conceptual: true}, explanation: "La reanudación es simulable, no ejecutable."});
    } else results.push({...base, status: "simulated", explanation: "Capacidad simulada sin efecto proyectado."});
  }
  const requiredCapabilities = [...new Set(results.flatMap((result) => result.capability ? [result.capability] : []))].sort(); const missingCapabilities = results.filter((result) => result.support === "missing" || result.status === "contract_only").flatMap((result) => result.capability ? [result.capability] : []);
  const simulatable = validation.valid && !all.length && results.every((result) => result.status === "simulated"); const resume = results.find((result) => result.capability?.startsWith("resume:") && result.status === "simulated");
  return {planId: plan.id, intentFingerprint: plan.fingerprint, structurallyValid: plan.structurallyValid, simulatable, executable: false, state: !plan.structurallyValid ? "simulation_blocked" : simulatable ? "simulatable" : "execution_blocked", nodeResults: results, blockers: all, warnings: plan.warnings.map((warning) => warning.message), requiredCapabilities, missingCapabilities, projectedEffects, projectedResume: resume?.output};
}
