import {addReviewResolution, createReviewCase, getReviewCase, transitionReviewCase} from "../../store/reviewStore";
import type {ReviewCase, ReviewIssue, ReviewResolution} from "../../types";

const context = {producer: "external_news", sourceId: "marca", sourceName: "Marca", sourceUrl: "https://marca.com/resume-test", externalItemId: "resume-test", canonicalUrl: "https://marca.com/resume-test", title: "Título original", operation: "create_draft", createdAt: "2026-03-01T10:00:00.000Z", payloadSnapshot: {id: "resume-test", title: "Título original", excerpt: "Resumen original", bodyText: "Cuerpo original suficiente", canonicalUrl: "https://marca.com/resume-test", publishedAt: "2026-03-01T09:00:00.000Z", image: {url: "https://marca.com/original.jpg"}}, analysisSnapshot: {analysis: {relevancia: "alta", disciplinaPrincipal: "MMA"}, resolved: {disciplina: {id: "discipline-old", label: "MMA"}, organizacion: null, evento: null, luchadoresPrincipales: [{id: "fighter-old", label: "Anterior"}], luchadoresSecundarios: []}}, unresolvedRelations: []};

function issue(id: string, fieldPath: string, valueKind: ReviewIssue["valueKind"], currentValue?: ReviewIssue["currentValue"]): ReviewIssue { return {id: `dev:resume:${id}`, kind: "low_confidence", valueKind, fieldPath, label: id, message: `Prueba ${id}`, currentValue}; }

export function createExternalNewsResumeTestCase(): ReviewCase[] {
  const issues: ReviewIssue[] = [issue("title", "title", "text", "Título original"), issue("discipline", "discipline", "discipline"), issue("organization", "organization", "organization"), issue("event", "event", "event"), {...issue("fighter:add", "fighter", "fighter"), candidates: [{id: "fighter-new", label: "Nuevo", value: {}, sanityId: "fighter-new", confidence: 99}]}, {...issue("fighter:fighter-old", "fighter", "fighter"), candidates: [{id: "fighter-replacement", label: "Sustituto", value: {}, sanityId: "fighter-replacement", confidence: 99}]}, issue("date", "date", "date"), issue("canonical-url", "canonical-url", "url"), issue("image-url", "image", "image"), issue("image-asset", "image", "image"), issue("duplicate-rejected", "duplicate", "sanityReference"), issue("duplicate-confirmed", "duplicate", "sanityReference"), {...issue("optional", "summary", "text"), required: false, blocking: false}, {...issue("retry", "body", "text"), required: true, blocking: true}, {...issue("prepared", "fighter", "fighter"), required: true, blocking: true}];
  const reviewCase = createReviewCase({dedupeKey: "dev:external-news-resume-preview", module: "external.news", title: "Prueba completa de preview de reanudación", priority: "high", subject: {type: "external_news", id: "resume-test", label: "Preview 4C1"}, issues, context});
  const resolutions: ReviewResolution[] = [{type: "set_value", issueId: "dev:resume:title", value: "Título corregido"}, {type: "link_reference", issueId: "dev:resume:discipline", sanityId: "discipline-mma"}, {type: "link_reference", issueId: "dev:resume:organization", sanityId: "organization-ufc"}, {type: "link_reference", issueId: "dev:resume:event", sanityId: "event-ufc"}, {type: "select_candidate", issueId: "dev:resume:fighter:add", candidateId: "fighter-new"}, {type: "select_candidate", issueId: "dev:resume:fighter:fighter-old", candidateId: "fighter-replacement"}, {type: "set_value", issueId: "dev:resume:date", value: "2026-03-02T09:00:00.000Z"}, {type: "set_value", issueId: "dev:resume:canonical-url", value: "https://marca.com/resume-corrected"}, {type: "select_image", issueId: "dev:resume:image-url", url: "https://marca.com/new.jpg"}, {type: "select_image", issueId: "dev:resume:image-asset", assetId: "image-asset-1"}, {type: "reject_duplicate", issueId: "dev:resume:duplicate-rejected", reason: "No coincide el contenido."}, {type: "confirm_duplicate", issueId: "dev:resume:duplicate-confirmed", duplicateId: "news-existing"}, {type: "discard", issueId: "dev:resume:optional", reason: "Observación opcional."}, {type: "retry", issueId: "dev:resume:retry"}, {type: "create_entity", issueId: "dev:resume:prepared", entityType: "fighter", draft: {name: "Entidad preparada"}}];
  resolutions.forEach((resolution) => addReviewResolution(reviewCase.id, resolution));
  const incomplete = createReviewCase({dedupeKey: "dev:external-news-resume-incomplete", module: "external.news", title: "Snapshot incompleto 4C1", priority: "normal", subject: {type: "external_news", id: "incomplete"}, issues: [], context: {producer: "external_news"}});
  const resumed = createReviewCase({dedupeKey: "dev:external-news-resume-resumed", module: "external.news", title: "Caso resumed no ejecutable 4C1", priority: "normal", subject: {type: "external_news", id: "resumed"}, issues: [], context});
  transitionReviewCase(resumed.id, "resolved"); transitionReviewCase(resumed.id, "resuming"); const finalResumed = transitionReviewCase(resumed.id, "resumed") ?? resumed;
  return [getReviewCase(reviewCase.id) ?? reviewCase, incomplete, finalResumed];
}
