import {computeExecutorManifestFingerprint,deepFreezeReviewJson} from "./fingerprints";import type {ExecutorAllocation,ExecutorManifest,ReviewEffect,ReviewExecutorRegistration,UniversalExecutionPlan} from "./types";
export type RegisteredReviewExecutor={registration:ReviewExecutorRegistration;manifest:Readonly<ExecutorManifest>;manifestFingerprint:ExecutorAllocation["executorManifestFingerprint"]};const executors=new Map<string,RegisteredReviewExecutor>();const listeners=new Set<()=>void>();
const manifestOf=(r:ReviewExecutorRegistration):ExecutorManifest=>({executorId:r.executorId,version:r.version,capability:r.capability,scope:r.scope,supportedEffects:[...new Set(r.supportedEffects)].sort(),supportedEntityTypes:[...new Set(r.supportedEntityTypes)].sort(),risk:r.risk});
function emit(){for(const listener of listeners)try{listener()}catch(error){console.error("[FFN3 universal] Executor listener failed.",error)}}
function create(r:ReviewExecutorRegistration):RegisteredReviewExecutor{if(!r.executorId?.trim()||!r.capability?.trim()||!Number.isInteger(r.version)||r.version<1||!r.supportedEffects?.length||!r.supportedEntityTypes?.length)throw new Error("invalid_universal_executor_manifest");const manifest=deepFreezeReviewJson(manifestOf(r) as unknown as import("../types").ReviewJsonValue) as unknown as Readonly<ExecutorManifest>;const registration=Object.freeze({...r,...manifest,supportedEffects:manifest.supportedEffects,supportedEntityTypes:manifest.supportedEntityTypes});return Object.freeze({registration,manifest,manifestFingerprint:computeExecutorManifestFingerprint(manifest as unknown as import("../types").ReviewJsonValue)});}
export function registerReviewExecutor(r:ReviewExecutorRegistration,options:{replace?:boolean}={}):()=>void{const next=create(r),current=executors.get(next.manifest.executorId);if(current&&current.registration!==r&&!options.replace)throw new Error(`universal_executor_already_registered:${r.executorId}`);executors.set(r.executorId,next);emit();return()=>{if(executors.get(r.executorId)!==next)return;if(current)executors.set(r.executorId,current);else executors.delete(r.executorId);emit()};}
export const getRegisteredReviewExecutor=(id:string):RegisteredReviewExecutor|undefined=>executors.get(id);export const getReviewExecutor=(id:string)=>executors.get(id)?.registration;export const listRegisteredReviewExecutors=()=>[...executors.values()].sort((a,b)=>a.manifest.executorId.localeCompare(b.manifest.executorId));export const listReviewExecutors=()=>listRegisteredReviewExecutors().map((x)=>x.registration);export const listReviewExecutorsForCapability=(cap:string)=>listReviewExecutors().filter((x)=>x.capability===cap);
export function findReviewExecutorCandidates(plan:UniversalExecutionPlan,effect:ReviewEffect,index:number):RegisteredReviewExecutor[]{return listRegisteredReviewExecutors().filter((x)=>{const m=x.manifest;if(effect.executorSelector?.executorId&&effect.executorSelector.executorId!==m.executorId)return false;if(effect.executorSelector?.scope&&effect.executorSelector.scope!==m.scope)return false;return m.supportedEffects.includes(effect.type)&&(m.supportedEntityTypes.includes("*")||m.supportedEntityTypes.includes(plan.entityType))&&x.registration.canExecute(plan,[index]);});}
export function subscribeReviewExecutors(listener:()=>void):()=>void{listeners.add(listener);return()=>listeners.delete(listener);}
