import assert from "node:assert/strict";
import {authorizeExternalNewsResume, buildPreparedExternalNewsResumeUniversalPlan, createExternalNewsResumeUniversalExecutor, executePreparedExternalNewsResume, fingerprintPreparedExternalNewsResume} from "../_laboratorio/laboratorio-ia/src/review/globalResolution";
import {buildResumeContract, executeUniversalExecutionPlan, registerReviewExecutor, simulateUniversalExecutionPlan, type UniversalReviewInput} from "../_laboratorio/laboratorio-ia/src/review/universal";
import {buildResolutionGraph} from "../_laboratorio/laboratorio-ia/src/review/resolutionGraph";
import {buildEntityOperation} from "../_laboratorio/laboratorio-ia/src/review/entityOperations";
import {buildExternalNewsResumePreview, createExternalNewsResumeExecutionTestCase, type ExternalNewsResumeExecutor} from "../_laboratorio/laboratorio-ia/src/review/resume/externalNews";
import {getReviewCase, setReviewCaseRepositoryForTests} from "../_laboratorio/laboratorio-ia/src/review/store/reviewStore";
import type {ReviewCase} from "../_laboratorio/laboratorio-ia/src/review/types";
import type {PreparedExternalNewsResume} from "../_laboratorio/laboratorio-ia/src/review/globalResolution";

const now = "2026-07-27T18:00:00.000Z";
class ReviewMemoryRepository { constructor(private cases: ReviewCase[] = []) {} load() { return structuredClone(this.cases); } save(cases: readonly ReviewCase[]) { this.cases = structuredClone([...cases]); } }
function prepared(): PreparedExternalNewsResume { const created = createExternalNewsResumeExecutionTestCase(); const reviewCase = getReviewCase(created.id)!; const preview = buildExternalNewsResumePreview(reviewCase, {now: () => now}); assert.equal(preview.canResume, true); const validated = buildEntityOperation({id: `validate:${reviewCase.id}`, kind: "validate_entity", entityType: "noticia", source: "global_resolution", evidence: [], confidence: 1, risk: "low", preconditions: [], postconditions: [], dependencyIds: [], requiredCapability: "validate:noticia", compensatable: false, explanation: "Validate"}); const operation = buildEntityOperation({id: `resume:${reviewCase.id}`, kind: "validate_entity", entityType: "noticia", source: "global_resolution", evidence: [], confidence: 1, risk: "low", preconditions: [], postconditions: [], dependencyIds: [validated.id], requiredCapability: "resume:external_news", compensatable: false, explanation: "Resume"}); const graph = buildResolutionGraph({caseId: reviewCase.id, caseVersion: reviewCase.version, producerId: "external_news", originalOperation: "create_draft", nodes: [{operation: validated}, {operation, isResumeNode: true, requiredForCompletion: false}], now: () => now}); const projectedGraph = {...graph, nodes: graph.nodes.map((node) => ({...node, state: node.isResumeNode ? "ready" as const : "succeeded" as const})), state: "ready" as const}; const fighterId = "fighter:resolved"; const value = {caseId: reviewCase.id, caseVersion: reviewCase.version, planId: `plan:${reviewCase.id}`, planFingerprint: "sha256-v1:plan", snapshotFingerprint: "sha256-v1:snapshot", producer: "external_news" as const, operation: "create_draft", payload: {...preview.resultingPayload, luchadoresRelacionados: [fighterId]}, appliedReferences: [{entityType: "luchador" as const, documentId: fighterId, reference: {_type: "reference" as const, _ref: fighterId}, sourceOperationId: validated.id, sourceResult: "created" as const, identityKey: "fighter:resolved", validated: true as const}], validation: preview.validation, projectedGraph, ready: true, blockers: [], generatedAt: now}; return {...value, previewFingerprint: fingerprintPreparedExternalNewsResume(value)}; }
function reviewInput(caseId: string): UniversalReviewInput { const snapshot = {title: "Resume"}; return {schemaVersion: 1, logicalKey: caseId, producerId: "external_news", operationId: "create_draft", operationType: "create", module: "external.news", entity: {type: "noticia"}, issueFamily: "missing_reference", issueCode: "resume", priority: "high", title: "Resume", snapshot, issues: [], evidence: [], constraints: [], resume: buildResumeContract({producerId: "external_news", operationId: "create_draft", operationType: "create", checkpoint: "review", snapshotVersion: 1, snapshot, idempotencyKey: caseId})}; }
function executor(mode: "success" | "fail" | "timeout" = "success"): {executor: ExternalNewsResumeExecutor; calls: () => number} { let calls = 0; return {calls: () => calls, executor: {buildOutput(form) { return {_type: "noticia", titulo: String(form.titulo), contenido: String(form.contenido)} as unknown as import("../_laboratorio/laboratorio-ia/src/review/types").ReviewJsonObject; }, async saveDraft() { calls += 1; if (mode === "timeout") throw new Error("timeout_after_send"); if (mode === "fail") return {success: false, error: "validation_failed"}; return {success: true, draftId: "draft:resume"}; }}}; }
async function main() { setReviewCaseRepositoryForTests(new ReviewMemoryRepository()); const value = prepared(); const authorization = authorizeExternalNewsResume(value, now); assert.ok(authorization); if (!authorization) return; const source = executor(); const registration = createExternalNewsResumeUniversalExecutor({executor: source.executor, now: () => now}); const unregister = registerReviewExecutor(registration); try { const plan = buildPreparedExternalNewsResumeUniversalPlan({prepared: value, reviewInput: reviewInput(value.caseId), now: () => now}); const state = {prepared: value, authorization} as unknown as import("../_laboratorio/laboratorio-ia/src/review/types").ReviewJsonValue; const simulation = await simulateUniversalExecutionPlan(plan, state, {now: () => now}); assert.equal(simulation.status, "safe"); const first = executeUniversalExecutionPlan(plan, state, simulation, {now: () => now, policy: {allowedRiskLevels: ["medium"], allowedCapabilities: ["resume:external_news"]}}); const second = executeUniversalExecutionPlan(plan, state, simulation, {now: () => now, policy: {allowedRiskLevels: ["medium"], allowedCapabilities: ["resume:external_news"]}}); assert.equal(first, second); assert.equal((await first).status, "succeeded"); assert.equal(source.calls(), 1); const already = await executePreparedExternalNewsResume({prepared: value, authorization, dependencies: {executor: source.executor, now: () => now}}); assert.equal(already.outcome, "already_resumed"); assert.equal(source.calls(), 1); } finally { unregister(); }
  const blockedValue = prepared(); const noAuthorization = authorizeExternalNewsResume({...blockedValue, ready: false}, now); assert.equal(noAuthorization, undefined);
  const stable = prepared(); const stableAuthorization = authorizeExternalNewsResume(stable, now)!; const tampered = {...stable, payload: {...stable.payload, titulo: "Payload alterado"}}; assert.equal(authorizeExternalNewsResume(tampered, now), undefined); const blockedExecutor = executor(); const tamperedResult = await executePreparedExternalNewsResume({prepared: tampered, authorization: stableAuthorization, dependencies: {executor: blockedExecutor.executor, now: () => now}}); assert.equal(tamperedResult.outcome, "blocked"); assert.equal(blockedExecutor.calls(), 0);
  const failing = prepared(); const failingAuth = authorizeExternalNewsResume(failing, now)!; const failed = await executePreparedExternalNewsResume({prepared: failing, authorization: failingAuth, dependencies: {executor: executor("fail").executor, now: () => now}}); assert.equal(failed.outcome, "failed");
  const uncertainValue = prepared(); const uncertainAuth = authorizeExternalNewsResume(uncertainValue, now)!; const uncertain = await executePreparedExternalNewsResume({prepared: uncertainValue, authorization: uncertainAuth, dependencies: {executor: executor("timeout").executor, now: () => now}}); assert.equal(uncertain.outcome, "reconciliation_required");
  const duplicate = createExternalNewsResumeUniversalExecutor({executor: executor().executor}); const remove = registerReviewExecutor(duplicate); try { assert.throws(() => registerReviewExecutor(createExternalNewsResumeUniversalExecutor({executor: executor().executor}))); } finally { remove(); }
  console.log("AU2 external news resume executor tests: OK"); }
main().catch((error) => { console.error(error); process.exitCode = 1; });
