import assert from "node:assert/strict";
import {previewAutonomousReview} from "../_laboratorio/laboratorio-ia/src/review/autonomous";
import {addReviewResolution, beginReviewResumeExecution, createReviewCase, getReviewCase, setReviewCaseRepositoryForTests} from "../_laboratorio/laboratorio-ia/src/review/store/reviewStore";
import {migrateReviewCases} from "../_laboratorio/laboratorio-ia/src/review/store/migrations";
import type {ReviewCase} from "../_laboratorio/laboratorio-ia/src/review/types";
import {createMemoryOutcomeRepository, migrateOutcomeLedger, setOutcomeRepositoryForTests} from "../_laboratorio/laboratorio-ia/src/review/outcomes";
import {createMemoryRepository, emptyMemoryLedger, migrateMemoryLedger, setMemoryRepositoryForTests} from "../_laboratorio/laboratorio-ia/src/review/memory";
import {createMemoryRetrievalRepository, migrateRetrievalLedger, setRetrievalRepositoryForTests} from "../_laboratorio/laboratorio-ia/src/review/retrieval";
import {MemoryInvestigationRepository, setInvestigationRepositoryForTests} from "../_laboratorio/laboratorio-ia/src/review/investigation/deep";
import {buildExternalNewsResumePreview, createExternalNewsPreviewFingerprint, executeExternalNewsResume, type ExternalNewsResumeExecutor} from "../_laboratorio/laboratorio-ia/src/review/resume/externalNews";

const now = "2026-07-18T15:00:00.000Z";
class ReviewMemoryRepository { constructor(private cases: ReviewCase[] = []) {} load() { return structuredClone(this.cases); } save(cases: readonly ReviewCase[]) { this.cases = structuredClone([...cases]); } snapshot() { return structuredClone(this.cases); } }
const input = (dedupeKey: string) => ({dedupeKey, module: "external.news" as const, title: "Recovery 6E", priority: "high" as const, source: "controlled", subject: {type: "external_news", id: dedupeKey}, issues: [{id: `${dedupeKey}:discipline`, kind: "missing_reference" as const, valueKind: "discipline" as const, fieldPath: "discipline", label: "Disciplina", message: "Falta", required: true, blocking: true, candidates: [{id: "mma", label: "MMA", value: {id: "mma"}, sanityId: "mma", confidence: 99}]}], context: {producer: "external_news", sourceId: "controlled", sourceName: "Controlled", sourceUrl: "https://example.test/6e", canonicalUrl: "https://example.test/6e", externalItemId: dedupeKey, title: "Recovery", operation: "create_draft", createdAt: now, payloadSnapshot: {id: dedupeKey, title: "Recovery", excerpt: "Resumen", bodyText: "Contenido controlado suficientemente largo.", canonicalUrl: "https://example.test/6e", publishedAt: now, image: {url: "https://example.test/image.jpg"}}, analysisSnapshot: {analysis: {relevancia: "alta", disciplinaPrincipal: "MMA"}, resolved: {disciplina: {id: "old", label: "Old"}, organizacion: null, evento: null, luchadoresPrincipales: [], luchadoresSecundarios: []}}}});

async function main() {
  const reviewRepo = new ReviewMemoryRepository(); const outcomeRepo = createMemoryOutcomeRepository(); const memoryRepo = createMemoryRepository(emptyMemoryLedger()); const retrievalRepo = createMemoryRetrievalRepository(); const investigationRepo = new MemoryInvestigationRepository();
  const restores = [setReviewCaseRepositoryForTests(reviewRepo), setOutcomeRepositoryForTests(outcomeRepo), setMemoryRepositoryForTests(memoryRepo), setRetrievalRepositoryForTests(retrievalRepo), setInvestigationRepositoryForTests(investigationRepo)];
  try {
    const valid = createReviewCase(input("6e:valid")); const validSnapshot = structuredClone(valid); const mixed = migrateReviewCases([validSnapshot, {schemaVersion: 1, id: 4}, {schemaVersion: 999, id: "future"}]); assert.equal(mixed.length, 1); assert.equal(mixed[0].id, valid.id); assert.deepEqual(validSnapshot, valid, "migración no muta snapshot original"); assert.deepEqual(migrateReviewCases("{broken"), []); assert.deepEqual(migrateReviewCases([{...valid, schemaVersion: 999}]), []);
    assert.deepEqual(migrateOutcomeLedger({schemaVersion: 999, records: [], events: []}), {schemaVersion: 1, records: [], events: []}); assert.deepEqual(migrateMemoryLedger({schemaVersion: 999}), emptyMemoryLedger()); assert.deepEqual(migrateRetrievalLedger({schemaVersion: 999}), {schemaVersion: 1, queries: [], results: [], events: []});

    const failingRepo = {load: () => [valid], save: () => { throw new Error("injected_persistence_failure"); }}; const restoreFailing = setReviewCaseRepositoryForTests(failingRepo); try { assert.throws(() => createReviewCase(input("6e:persistence-failure")), /injected_persistence_failure/); assert.equal(failingRepo.load().length, 1); } finally { restoreFailing(); }
    const beforeInvalidResolution = JSON.stringify(reviewRepo.snapshot()); assert.throws(() => addReviewResolution(valid.id, {type: "link_reference", issueId: valid.issues[0].id, sanityId: ""}), /ID de Sanity/); assert.equal(JSON.stringify(reviewRepo.snapshot()), beforeInvalidResolution);
    const dryBefore = JSON.stringify(reviewRepo.snapshot()); const insufficient = createReviewCase({...input("6e:insufficient"), issues: [{id: "6e:insufficient:entity", kind: "missing_entity" as const, valueKind: "fighter" as const, label: "Sin evidencia", message: "Insuficiente", required: true, blocking: true}]}); const dry = previewAutonomousReview(insufficient.id); assert.ok(dry.needsMoreEvidenceCount > 0); assert.equal(JSON.stringify(reviewRepo.snapshot()).includes(insufficient.id), true); assert.equal(getReviewCase(insufficient.id)?.resolutions.length, 0); assert.notEqual(JSON.stringify(reviewRepo.snapshot()), dryBefore, "solo la creación explícita del fixture cambia el store");

    const incomplete = createReviewCase({...input("6e:incomplete"), context: {producer: "external_news"}}); const incompletePreview = buildExternalNewsResumePreview(incomplete, {now: () => now}); assert.equal(incompletePreview.canResume, false); assert.notEqual(incompletePreview.status, "ready"); assert.ok(incompletePreview.reasons.length > 0); assert.equal((await executeExternalNewsResume({caseId: incomplete.id})).status, "executor_unavailable");

    const recoverable = createReviewCase(input("6e:recoverable")); addReviewResolution(recoverable.id, {type: "link_reference", issueId: recoverable.issues[0].id, sanityId: "mma"}); let calls = 0; const failingExecutor: ExternalNewsResumeExecutor = {buildOutput: () => ({title: "6E"}), saveDraft: async () => { calls += 1; return {success: false, error: "injected_save_failure"}; }}; const failed = await executeExternalNewsResume({caseId: recoverable.id, executor: failingExecutor}); assert.equal(failed.status, "draft_save_failed"); assert.equal(getReviewCase(recoverable.id)?.status, "resume_failed"); assert.match(getReviewCase(recoverable.id)?.lastResumeError ?? "", /injected_save_failure/);
    const successfulExecutor: ExternalNewsResumeExecutor = {buildOutput: () => ({title: "6E"}), saveDraft: async () => { calls += 1; return {success: true, draftId: "draft-6e"}; }}; const recovered = await executeExternalNewsResume({caseId: recoverable.id, executor: successfulExecutor}); assert.equal(recovered.status, "succeeded"); assert.equal(getReviewCase(recoverable.id)?.status, "resumed"); assert.equal(calls, 2, "un intento fallido y un único guardado efectivo");

    const orphan = createReviewCase(input("6e:orphan")); addReviewResolution(orphan.id, {type: "link_reference", issueId: orphan.issues[0].id, sanityId: "mma"}); const orphanCurrent = getReviewCase(orphan.id)!; const orphanPreview = buildExternalNewsResumePreview(orphanCurrent, {now: () => now}); const orphanFingerprint = createExternalNewsPreviewFingerprint(orphanCurrent, orphanPreview); beginReviewResumeExecution(orphan.id, {expectedVersion: orphanCurrent.version, execution: {status: "resuming", attemptCount: 1, startedAt: now, previewFingerprint: orphanFingerprint, caseVersionAtStart: orphanCurrent.version, summary: {appliedResolutionCount: 1, changeCount: orphanPreview.changes.length}}}); const orphanResult = await executeExternalNewsResume({caseId: orphan.id, executor: successfulExecutor}); assert.equal(orphanResult.status, "transition_failed"); assert.equal(getReviewCase(orphan.id)?.status, "resume_failed", "resuming huérfano debe quedar recuperable"); assert.match(getReviewCase(orphan.id)?.lastResumeError ?? "", /huérfana/i); const orphanRetry = await executeExternalNewsResume({caseId: orphan.id, executor: successfulExecutor}); assert.equal(orphanRetry.status, "succeeded"); assert.equal(getReviewCase(orphan.id)?.status, "resumed"); assert.equal(calls, 3, "la recuperación huérfana añade un único guardado efectivo");

    const editorialSucceeded = true; let telegramAttempts = 0; const telegramFailure = async () => { telegramAttempts += 1; throw new Error("telegram_unavailable"); }; await telegramFailure().catch(() => undefined); assert.equal(editorialSucceeded, true); assert.equal(telegramAttempts, 1);
    let apiAvailable = false; const requestDependency = async () => { if (!apiAvailable) throw new Error("api_unavailable"); return {ok: true, items: []}; }; const degraded = await requestDependency().catch((error: Error) => ({ok: false, error: error.message})); assert.deepEqual(degraded, {ok: false, error: "api_unavailable"}); apiAvailable = true; assert.deepEqual(await requestDependency(), {ok: true, items: []});

    console.log(`Phase 6E recovery summary: ${JSON.stringify({partialStoreQuarantine: true, futureVersionRejected: true, persistenceFailureExplicit: true, invalidResolutionAtomic: true, insufficientEvidenceConservative: true, incompletePreviewBlocked: true, executorUnavailable: true, resumeFailurePersisted: true, retryRecovered: true, orphanResumingRecovered: true, telegramDegraded: true, apiDependencyRecovered: true, externalEffects: 0})}`);
    console.log("Phase 6E robustness and recovery tests: OK");
  } finally { restores.reverse().forEach((restore) => restore()); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
