import assert from "node:assert/strict";
import {analyzeCollectedEvidence, assertSafeSerializable, buildDeepInvestigationPlan, buildEvidenceDependencyGraph, deduplicateEvidence, defaultInvestigationProviders, detectInvestigationConflicts, evaluateCandidates, evaluateInvestigationSufficiency, extractClaimsFromEvidence, investigateReviewIssueCore, MemoryInvestigationRepository, validateProviderPolicy, type EvidenceItem, type InvestigationProvider, type InvestigationRequest} from "../_laboratorio/laboratorio-ia/src/review/investigation/deep/index";
import type {ReviewCase} from "../_laboratorio/laboratorio-ia/src/review/types";

const now = "2026-07-17T10:00:00.000Z";
const reviewCase: ReviewCase = {schemaVersion: 1, id: "case-espabox", dedupeKey: "espabox", module: "external.news", title: "Espabox", status: "open", priority: "high", subject: {type: "article", id: "espabox-1", label: "Espabox"}, issues: [{id: "issue-fighter", kind: "ambiguous_reference", valueKind: "fighter", fieldPath: "fighter.organizationIds", label: "Luchador ambiguo", message: "Dos candidatos", candidates: [{id: "erlantz", label: "Erlantz", value: {name: "Erlantz Tejada"}}, {id: "rodrigo", label: "Rodrigo", value: {name: "Rodrigo Caraballo"}}]}], resolutions: [], context: {snapshot: {organization: "WBA"}}, createdAt: now, updatedAt: now, version: 1, resumeAttempts: 0};
const request: InvestigationRequest = {id: "investigation-test", version: 1, case: structuredClone(reviewCase), issue: structuredClone(reviewCase.issues[0]), requestedAt: now, requestedBy: "test", mode: "local_only", allowedProviderIds: [], maxDepth: 12, maxEvidence: 100, timeoutMs: 1000, contextFingerprint: "ctx", policy: {version: "5f.1", maxProviders: 8, maxEvidence: 100, maxClaims: 100, maxConflicts: 50, maxDepth: 12, maxTotalBytes: 1_500_000, maxEvidenceBytes: 32_000, timeoutMs: 1000}};
const makeEvidence = (id: string, value: string, group = id): EvidenceItem => ({id, providerId: "test", providerRunId: "run", sourceClass: "internal_local", sourceId: id, sourceFingerprint: id, subject: "fighter", predicate: "discipline.id", originalValue: value, normalizedValue: value, transformations: [], normalizerVersion: "5f.1", authority: "internal_structured", directness: "direct", freshness: "current", reliability: "high", collectedAt: now, provenance: id, parentEvidenceIds: [], independenceGroup: group, limitations: [], status: "active", equivalentEvidenceIds: []});

async function main() {
  const before = JSON.stringify(reviewCase); const plan = buildDeepInvestigationPlan(request, defaultInvestigationProviders); assert.deepEqual(plan, buildDeepInvestigationPlan(request, defaultInvestigationProviders)); assert.equal(plan.questions.some((item) => item.kind === "candidate_comparison"), true); assert.equal(plan.providers.find((item) => item.providerId === "sanity_read")?.selected, false); assert.equal(request.mode, "local_only");
  for (const kind of ["required_field", "missing_reference", "ambiguous_reference", "missing_image", "contradictory_data", "low_confidence"] as const) { const next = {...request, issue: {...request.issue, kind}}; assert.ok(buildDeepInvestigationPlan(next, defaultInvestigationProviders).questions.length); }
  const unsafeProvider = {...defaultInvestigationProviders[0], readOnly: false as never}; assert.equal(validateProviderPolicy(unsafeProvider, request), "provider_not_read_only");
  assert.throws(() => assertSafeSerializable({token: "x"}), /sensitive_key_rejected/); assert.throws(() => { const value: Record<string, unknown> = {}; value.self = value; assertSafeSerializable(value); }, /circular_reference/); assert.throws(() => assertSafeSerializable(new Date()), /unsupported_instance/); assert.throws(() => assertSafeSerializable("x".repeat(100), 10), /payload_too_large/);
  const duplicated = deduplicateEvidence([makeEvidence("a", "boxing", "origin"), {...makeEvidence("b", "boxing", "origin"), sourceFingerprint: "a", sourceId: "a"}]); assert.equal(duplicated.length, 1); assert.equal(duplicated[0].equivalentEvidenceIds.length, 1);
  const evidence = [makeEvidence("boxing", "boxing", "official-a"), makeEvidence("mma", "mma", "official-b")]; const claims = extractClaimsFromEvidence(evidence); const conflicts = detectInvestigationConflicts(claims, evidence); assert.equal(conflicts.length, 1); assert.equal(conflicts[0].severity, "high"); assert.equal(claims.every((claim) => claim.assessment === "contradicted"), true);
  const dependent = [makeEvidence("root", "boxing", "origin"), {...makeEvidence("derived", "boxing", "origin"), parentEvidenceIds: ["root"], directness: "derived" as const}]; assert.equal(buildEvidenceDependencyGraph(dependent).valid, true); const circular = dependent.map((item, index) => ({...item, parentEvidenceIds: [dependent[1 - index].id]})); assert.equal(buildEvidenceDependencyGraph(circular).valid, false);
  const candidates = evaluateCandidates([{...makeEvidence("candidate", "x"), predicate: "candidate.value", subject: "candidate-a"}]); assert.equal(candidates[0].status, "insufficient_evidence");
  assert.equal(evaluateInvestigationSufficiency({coverage: {criticalQuestions: 1, coveredCriticalQuestions: 1, ratio: 1, independentGroups: 1}, conflicts: [], evidence: [makeEvidence("x", "yes")], candidates: [], failedProviders: [], policyBlocked: false}).status, "sufficient_for_proposal");
  assert.equal(evaluateInvestigationSufficiency({coverage: {criticalQuestions: 1, coveredCriticalQuestions: 1, ratio: 1, independentGroups: 2}, conflicts, evidence, candidates: [], failedProviders: [], policyBlocked: false}).status, "contradictory");
  const output = await investigateReviewIssueCore(request, {outcomes: [], memories: [], clusters: [], providers: defaultInvestigationProviders, now: () => now}); assert.equal(output.result.request.mode, "local_only"); assert.equal(output.result.candidateAssessments.length, 2); assert.equal(output.result.request.case.resolutions.length, 0); assert.equal(output.result.eventIds.length > 0, true); assert.equal(JSON.stringify(reviewCase), before);
  const failing: InvestigationProvider = {...defaultInvestigationProviders[0], id: "failure", collect: async () => { throw new Error("secret internal stack"); }}; const failed = await investigateReviewIssueCore({...request, id: "failed"}, {outcomes: [], memories: [], clusters: [], providers: [failing], now: () => now}); assert.equal(failed.result.failedProviders[0], "failure"); assert.equal(failed.result.providerRuns[0].limitation, "provider_failed_safely");
  const repository = new MemoryInvestigationRepository(); repository.save({schemaVersion: 1, requests: [request], plans: [plan], results: [output.result], events: output.events}); assert.equal(repository.load().results.length, 1); assert.notEqual(repository.load(), repository.load());
  const analyzed = analyzeCollectedEvidence(request, plan, evidence, [], [], [], now); assert.equal(analyzed.result.status, "conflicting_evidence"); assert.equal(analyzed.result.conflicts.length, 1); assert.equal(analyzed.result.request.case.resolutions.length, 0);
  assert.equal(JSON.stringify(output).includes("proposedResolution"), false); assert.equal(JSON.stringify(output).includes("saveDraft"), false); assert.equal(JSON.stringify(output).includes("materialize"), false); assert.equal(JSON.stringify(output).includes("publish"), false);
  console.log("Phase 5F deep investigation tests: OK");
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
