import assert from "node:assert/strict";
import {buildGlobalResolutionPlan, createFighterCreationUniversalExecutor, extractFighterCreationUniversalPlan, pilotCapabilityRegistry, simulateGlobalResolutionPlan, fighterIdentityGuardForCreation, resolveFighterIdentityGuard} from "../_laboratorio/laboratorio-ia/src/review/globalResolution";
import {CandidateDiscoveryRegistry, CandidateDiscoveryService, createSanityFighterCandidateDiscoveryAdapter} from "../_laboratorio/laboratorio-ia/src/review/entityIdentity";
import {createInMemoryCandidateReader} from "../_laboratorio/laboratorio-ia/src/review/entityIdentity/discovery/devFixture";
import {buildResumeContract, executeUniversalExecutionPlan, registerReviewExecutor, simulateUniversalExecutionPlan, type UniversalReviewInput} from "../_laboratorio/laboratorio-ia/src/review/universal";
import type {CreateEditorialEntityExecutor} from "../_laboratorio/laboratorio-ia/src/review/materialization";
import type {ReviewCase, ReviewJsonObject} from "../_laboratorio/laboratorio-ia/src/review/types";

const now = "2026-07-27T16:00:00.000Z";
const draft: ReviewJsonObject = {entityType: "fighter", name: "Ada Fighter", identityKey: "fighter:ada-fighter", disciplineId: "discipline:boxing", organizationIds: ["organization:test"], sourceEvidence: [{source: "test"}]};
function reviewCase(): ReviewCase { return {schemaVersion: 1, id: "case:fighter-executor", dedupeKey: "case:fighter-executor", module: "external.news", title: "Fighter", status: "open", priority: "high", subject: {type: "external_news", id: "news:1"}, issues: [{id: "issue:fighter", kind: "missing_entity", valueKind: "fighter", fieldPath: "fighter", label: "Fighter", message: "Missing", required: true, blocking: true}], resolutions: [{type: "create_entity", issueId: "issue:fighter", entityType: "fighter", draft: {name: "Ada Fighter"}}], context: {producer: "external_news", operation: "create_draft", payloadSnapshot: {id: "news:1"}}, createdAt: now, updatedAt: now, version: 1, resumeAttempts: 0}; }
function universalInput(): UniversalReviewInput { const snapshot = {title: "Fighter"}; return {schemaVersion: 1, logicalKey: "case:fighter-executor", producerId: "external_news", operationId: "create_draft", operationType: "create", module: "external.news", entity: {type: "noticia", id: "news:1"}, issueFamily: "missing_reference", issueCode: "missing_fighter", priority: "high", title: "Fighter", snapshot, issues: [], evidence: [], constraints: [], resume: buildResumeContract({producerId: "external_news", operationId: "create_draft", operationType: "create", checkpoint: "review", snapshotVersion: 1, snapshot, idempotencyKey: "case:fighter-executor"})}; }
async function candidatePlan() { const built = buildGlobalResolutionPlan({reviewCase: reviewCase(), preparedEntities: [{issueId: "issue:fighter", entityType: "fighter", draft, identityKey: "fighter:ada-fighter", valid: true, evidence: [{id: "e", kind: "source", source: "test", confidence: .98, limitations: []}]}], evidence: [{issueId: "issue:fighter", id: "e", kind: "source", source: "test", confidence: .98, limitations: []}], finalEntityType: "noticia", policy: {availableCapabilities: ["create:luchador", "resolve_identity:fighter"]}, now: () => now}); assert.equal(built.ok, true); if (!built.ok) throw new Error("plan"); const simulation = simulateGlobalResolutionPlan(built.plan, {reviewCase: reviewCase(), preparedEntities: [{issueId: "issue:fighter", entityType: "fighter", draft}], fighterCandidates: [], newsPayload: {titulo: "Noticia", contenido: "Contenido", fuenteUrl: "https://example.test", fechaPublicacion: now, disciplina: "discipline:boxing", organizacionRelacionada: "", eventoRelacionado: "", luchadoresRelacionados: [], imagenPrincipal: "https://example.test/image.jpg"}, producerContracts: [{producer: "external_news", supportsSimulation: true, allowsProjectedReferences: true}]}); const registry = new CandidateDiscoveryRegistry(); registry.register(createSanityFighterCandidateDiscoveryAdapter(createInMemoryCandidateReader([]))); const guard = fighterIdentityGuardForCreation(built.plan.operations, built.plan.operations.find((item) => item.kind === "create_entity" && item.entityType === "luchador")!.id)!; const resolved = await resolveFighterIdentityGuard({plan: built.plan, guardOperationId: guard.id, service: new CandidateDiscoveryService(registry), now: () => now}); const extracted = extractFighterCreationUniversalPlan({plan: built.plan, simulation, reviewInput: universalInput(), identityGuardAuthorization: resolved.authorization, now: () => now}); if (!extracted.ok) throw new Error(`fighter_creation_extraction_failed:${extracted.reason}`); return extracted.universalPlan; }
function gateway(mode: "created" | "existing" | "missing-id" | "timeout" = "created"): {gateway: CreateEditorialEntityExecutor; created: () => number} { let calls = 0; return {created: () => calls, gateway: {async checkDuplicate() { throw new Error("legacy_fighter_deduplication_must_not_run"); }, async createEntity() { calls += 1; if (mode === "timeout") return {success: false, error: "timeout_after_send"}; if (mode === "missing-id") return {success: true}; return {success: true, entityId: "fighter:ada", alreadyExisted: false}; }}}; }
async function execute(mode: "created" | "existing" | "missing-id" | "timeout" = "created") { const source = gateway(mode); const unregister = registerReviewExecutor(createFighterCreationUniversalExecutor({entityCreationExecutor: source.gateway, inspectCreatedEntity: async (id) => ({id, entityType: "luchador", name: "Ada Fighter", identityKey: "fighter:ada-fighter", disciplineId: "discipline:boxing", organizationId: "organization:test", payload: {}}), now: () => now}), {replace: true}); try { const plan = await candidatePlan(); const simulation = await simulateUniversalExecutionPlan(plan, {global: "fighter"}, {now: () => now}); assert.equal(simulation.status, "safe"); const first = executeUniversalExecutionPlan(plan, {global: "fighter"}, simulation, {now: () => now, policy: {allowedRiskLevels: ["medium"], allowedCapabilities: ["create:luchador"]}}); const second = executeUniversalExecutionPlan(plan, {global: "fighter"}, simulation, {now: () => now, policy: {allowedRiskLevels: ["medium"], allowedCapabilities: ["create:luchador"]}}); assert.equal(first, second); return {result: await first, calls: source.created()}; } finally { unregister(); } }
async function main() { assert.deepEqual(pilotCapabilityRegistry.list().filter((item) => item.support === "executable").map((item) => item.id), ["create:luchador", "replace_reference:noticia:luchador", "resume:external_news"]); const created = await execute(); assert.equal(created.result.status, "succeeded"); assert.equal(created.calls, 1); assert.equal((created.result.results[0].output as {outcome: string}).outcome, "created"); const legacyExisting = await execute("existing"); assert.equal(legacyExisting.result.status, "succeeded"); assert.equal(legacyExisting.calls, 1); assert.equal((legacyExisting.result.results[0].output as {outcome: string}).outcome, "created"); const missing = await execute("missing-id"); assert.equal(missing.result.status, "reconciliation_required"); const timeout = await execute("timeout"); assert.equal(timeout.result.status, "reconciliation_required"); const duplicate = createFighterCreationUniversalExecutor({entityCreationExecutor: gateway().gateway}); const remove = registerReviewExecutor(duplicate); try { assert.throws(() => registerReviewExecutor(createFighterCreationUniversalExecutor({entityCreationExecutor: gateway().gateway}))); } finally { remove(); } console.log("AU2 fighter creation executor tests: OK"); }
main().catch((error) => { console.error(error); process.exitCode = 1; });
