import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {buildOperatorExperience, buildCrossCaseGraph, buildGlobalResolutionDashboard, buildOperationalWorkspaceViewModel, operatorExperienceSecurity, type ReviewCase} from "../_laboratorio/laboratorio-ia/src/review";

const NOW = "2026-08-10T10:00:00.000Z";
let assertions = 0;
const equal = <T>(a: T, b: T, m?: string) => { assert.equal(a, b, m); assertions += 1; };
const check = (v: unknown, m?: string) => { assert.ok(v, m); assertions += 1; };
const deepEqual = (a: unknown, b: unknown, m?: string) => { assert.deepEqual(a, b, m); assertions += 1; };
function reviewCase(id: string, overrides: Partial<ReviewCase> = {}): ReviewCase { return {schemaVersion: 1, id, dedupeKey: `key:${id}`, module: "external.news", title: `Caso ${id}`, status: "open", priority: "normal", subject: {type: "fighter", id: `fighter:${id}`}, issues: [], resolutions: [], context: {producer: id === "two" ? "beta" : "alpha", token: `secret:${id}`, payloadSnapshot: {raw: `payload:${id}`}}, createdAt: "2026-07-01T10:00:00.000Z", updatedAt: NOW, version: 1, resumeAttempts: 0, ...overrides}; }
function main(): void {
  const cases = [reviewCase("one"), reviewCase("two", {priority: "high", subject: {type: "event", id: "event:two"}}), reviewCase("three", {status: "resolved"}), reviewCase("four", {status: "stale", priority: "critical"}), reviewCase("five"), reviewCase("six"), reviewCase("seven"), reviewCase("eight"), reviewCase("nine")];
  const model = buildOperatorExperience({cases, evaluatedAt: NOW, activeSection: "case", selectedCaseId: "two", filters: {query: "Caso", page: 1, pageSize: 3}});
  equal(model.version, "1.0.0"); equal(model.activeSection, "case"); deepEqual(model.breadcrumbs, ["Centro de revisión", "Núcleo Resolutivo IA", "Caso two"]); equal(model.navigation.length, 5); check(model.navigation.some((entry) => entry.id === "dashboard")); check(model.navigation.some((entry) => entry.id === "activity")); check(model.navigation.some((entry) => entry.id === "knowledge"));
  equal(model.filtered, cases.length); equal(model.page, 1); equal(model.pageSize, 3); equal(model.pageCount, 3); equal(model.rows.length, 3); check(model.rows.every((row) => row.progress.total >= 1)); check(model.rows.every((row) => row.phaseCount >= 1)); check(model.rows.every((row) => row.investigationSources >= 0)); check(model.rows.every((row) => typeof row.action.label === "string"));
  const pageTwo = buildOperatorExperience({cases, evaluatedAt: NOW, filters: {query: "Caso", page: 2, pageSize: 3}}); equal(pageTwo.rows.length, 3); check(pageTwo.rows[0].caseId !== model.rows[0].caseId); const last = buildOperatorExperience({cases, evaluatedAt: NOW, filters: {query: "Caso", page: 999, pageSize: 3}}); equal(last.page, 3); equal(last.rows.length, 3);
  equal(buildOperatorExperience({cases, evaluatedAt: NOW, filters: {query: "no-match"}}).rows.length, 0); equal(buildOperatorExperience({cases, evaluatedAt: NOW, filters: {status: "resolved"}}).filtered, 1); equal(buildOperatorExperience({cases, evaluatedAt: NOW, filters: {severity: "high"}}).filtered, 1); equal(buildOperatorExperience({cases, evaluatedAt: NOW, filters: {producer: "beta"}}).filtered, 1); equal(buildOperatorExperience({cases, evaluatedAt: NOW, filters: {entityType: "event"}}).filtered, 1); equal(buildOperatorExperience({cases, evaluatedAt: NOW, filters: {query: "fighter:one"}}).filtered, 1); check(model.facets.actions.length > 0); check(model.facets.capabilities.length >= 0);
  check(model.notifications.some((entry) => entry.kind === "completed")); check(model.notifications.some((entry) => entry.kind === "stale")); equal(model.notifications.every((entry, index, all) => index === 0 || ({critical: 3, high: 2, normal: 1}[all[index - 1].priority] >= {critical: 3, high: 2, normal: 1}[entry.priority])), true); check(model.notifications.every((entry) => entry.safeMessage.length > 5));
  const replay = buildOperatorExperience({cases: [...cases].reverse(), evaluatedAt: NOW, activeSection: "case", selectedCaseId: "two", filters: {query: "Caso", page: 1, pageSize: 3}}); deepEqual(replay, model); equal(model.writes, false); equal(model.persistsFilters, false); equal(model.invokesExecutors, false); equal(model.autoExecutes, false);
  const serialized = JSON.stringify(model); check(!serialized.includes("secret:")); check(!serialized.includes("payload:")); check(!serialized.includes("payloadSnapshot"));
  const dashboard = buildGlobalResolutionDashboard({cases, evaluatedAt: NOW}); equal(dashboard.writes, false); const graph = buildCrossCaseGraph({cases, evaluatedAt: NOW}); equal(graph.writes, false); const workspace = buildOperationalWorkspaceViewModel({reviewCase: cases[0], evaluatedAt: NOW}); equal(workspace.onePrimaryAction, true);
  equal(operatorExperienceSecurity.pure, true); equal(operatorExperienceSecurity.createsStores, false); equal(operatorExperienceSecurity.createsRouters, false); equal(operatorExperienceSecurity.invokesExecutors, false); equal(operatorExperienceSecurity.accessesSanity, false); equal(operatorExperienceSecurity.autoExecutes, false); equal(operatorExperienceSecurity.persistsFilters, false); equal(operatorExperienceSecurity.persistsAuth, false); equal(operatorExperienceSecurity.autoAppliesKnowledge, false); equal(operatorExperienceSecurity.writes, false);
  const source = readFileSync(new URL("../_laboratorio/laboratorio-ia/src/review/nucleus/operatorExperience.ts", import.meta.url), "utf8"); check(!/from ["'][^"']*(store|executor|sanity)/i.test(source)); check(!source.includes("fetch(")); check(!source.includes("localStorage")); check(!source.includes("payloadSnapshot"));
  const ui = readFileSync(new URL("../_laboratorio/laboratorio-ia/src/review/components/OperatorExperienceNavigation.tsx", import.meta.url), "utf8"); check(ui.includes("Breadcrumbs")); check(ui.includes("role=\"tablist\"")); check(ui.includes("aria-selected")); check(ui.includes("aria-live")); check(ui.includes("operator-spinner")); check(!ui.includes("execute("));
  const center = readFileSync(new URL("../_laboratorio/laboratorio-ia/src/review/components/ReviewCenter.tsx", import.meta.url), "utf8"); check(center.includes("buildOperatorExperience")); check(center.includes("operator-pagination")); check(center.includes("Título, entidad, ID, productor o capability")); check(center.includes("Anterior")); check(center.includes("Siguiente"));
  const css = readFileSync(new URL("../_laboratorio/laboratorio-ia/src/styles.css", import.meta.url), "utf8"); check(css.includes("prefers-reduced-motion")); check(css.includes("@media (max-width: 560px)")); check(css.includes("operator-spinner"));
  console.log(`AU10 B5 Operator Experience tests: OK (${assertions} assertions; navigation, breadcrumbs, filters, search, pagination, empty states, quick actions, progress, loaders, feedback, notifications, badges, responsive, accessibility and zero writes)`);
}
main();
