import assert from "node:assert/strict";
import {applyAutonomousReview} from "../_laboratorio/laboratorio-ia/src/review/autonomous";
import {createReviewCase, getReviewCase, getReviewCases, setReviewCaseRepositoryForTests} from "../_laboratorio/laboratorio-ia/src/review/store/reviewStore";
import type {ReviewCase} from "../_laboratorio/laboratorio-ia/src/review/types";
import {confirmEditorialOutcome, createMemoryOutcomeRepository, getOutcomeEvents, getOutcomesForCase, setOutcomeRepositoryForTests, validateOutcomeStore} from "../_laboratorio/laboratorio-ia/src/review/outcomes";
import {createMemoryFromOutcome, createMemoryRepository, emptyMemoryLedger, getDecisionMemories, setMemoryRepositoryForTests, validateDecisionMemoryStore} from "../_laboratorio/laboratorio-ia/src/review/memory";
import {createMemoryRetrievalRepository, getRetrievalResults, persistRetrieval, setRetrievalRepositoryForTests, validateDecisionRetrievalStore} from "../_laboratorio/laboratorio-ia/src/review/retrieval";
import {buildRetrievalQuery} from "../_laboratorio/laboratorio-ia/src/review/retrieval/buildRetrievalQuery";
import {getReviewInvestigations, investigateReviewIssue, MemoryInvestigationRepository, reconcileReviewInvestigations, setInvestigationRepositoryForTests, validateReviewInvestigationStore} from "../_laboratorio/laboratorio-ia/src/review/investigation/deep";
import {buildExternalNewsResumePreview, createExternalNewsPreviewFingerprint, executeExternalNewsResume, type ExternalNewsResumeExecutor} from "../_laboratorio/laboratorio-ia/src/review/resume/externalNews";

const now = "2026-07-17T12:00:00.000Z";
class ReviewMemoryRepository { constructor(private cases: ReviewCase[] = []) {} load() { return structuredClone(this.cases); } save(cases: readonly ReviewCase[]) { this.cases = structuredClone([...cases]); } snapshot() { return structuredClone(this.cases); } }
const reviewRepository = new ReviewMemoryRepository(); const outcomeRepository = createMemoryOutcomeRepository(); const memoryRepository = createMemoryRepository(emptyMemoryLedger()); const retrievalRepository = createMemoryRetrievalRepository(); const investigationRepository = new MemoryInvestigationRepository();
const restoreReview = setReviewCaseRepositoryForTests(reviewRepository); const restoreOutcome = setOutcomeRepositoryForTests(outcomeRepository); const restoreMemory = setMemoryRepositoryForTests(memoryRepository); const restoreRetrieval = setRetrievalRepositoryForTests(retrievalRepository); const restoreInvestigation = setInvestigationRepositoryForTests(investigationRepository);

async function main() {
  try {
    const input = {dedupeKey: "phase-6a:external-news:ufc", module: "external.news" as const, title: "Phase 6A integration", priority: "high" as const, source: "controlled-test", subject: {type: "external_news", id: "phase-6a-item", label: "Phase 6A"}, issues: [{id: "phase-6a:discipline", kind: "missing_reference" as const, valueKind: "discipline" as const, fieldPath: "discipline", label: "Disciplina", message: "Referencia pendiente", required: true, blocking: true, candidates: [{id: "discipline-mma", label: "MMA", value: {id: "discipline-mma"}, sanityId: "discipline-mma", confidence: 99}]}], context: {producer: "external_news", sourceId: "controlled", sourceName: "Controlled source", sourceUrl: "https://example.test/news", externalItemId: "phase-6a-item", canonicalUrl: "https://example.test/news", title: "Phase 6A", operation: "create_draft", createdAt: now, payloadSnapshot: {id: "phase-6a-item", title: "Phase 6A", excerpt: "Resumen", bodyText: "Contenido suficientemente largo para validar el flujo controlado.", canonicalUrl: "https://example.test/news", publishedAt: now, image: {url: "https://example.test/image.jpg"}}, analysisSnapshot: {analysis: {relevancia: "alta", disciplinaPrincipal: "MMA"}, resolved: {disciplina: {id: "discipline-old", label: "Old"}, organizacion: null, evento: null, luchadoresPrincipales: [], luchadoresSecundarios: []}}}};
    const reviewCase = createReviewCase(input); const duplicateAttempt = createReviewCase(input); assert.equal(getReviewCases().length, 1, "dedupeKey debe impedir ReviewCases duplicados"); assert.equal(duplicateAttempt.id, reviewCase.id);
    const autonomous = applyAutonomousReview(reviewCase.id); assert.deepEqual(autonomous.application?.applied, ["phase-6a:discipline"]); const resolvedCase = getReviewCase(reviewCase.id)!; assert.equal(resolvedCase.resolutions.length, 1); const autonomousRetry = applyAutonomousReview(reviewCase.id); assert.equal(autonomousRetry.application?.applied.length, 0, "repetir autonomous review no reaplica la resolución");
    const outcomesBeforeRetry = getOutcomesForCase(reviewCase.id); assert.equal(outcomesBeforeRetry.length, 1); const outcome = outcomesBeforeRetry[0]; assert.equal(outcome.issueId, "phase-6a:discipline"); assert.equal(outcome.resolutionId, outcome.decisionFingerprint);
    const confirmed = confirmEditorialOutcome(outcome.id, "phase-6a-editor", "Confirmación controlada 6A").record; const memoryCreated = createMemoryFromOutcome(confirmed); assert.equal(memoryCreated.eligible, true); assert.equal(memoryCreated.created, true); const memory = memoryCreated.record!; const memoryRetry = createMemoryFromOutcome(confirmed); assert.equal(memoryRetry.created, false, "repetir creación de memoria debe ser idempotente"); assert.equal(getDecisionMemories().length, 1);
    const query = buildRetrievalQuery(getReviewCase(reviewCase.id)!, getReviewCase(reviewCase.id)!.issues[0], {now}); const retrieval = persistRetrieval(query); persistRetrieval(query); assert.equal(getRetrievalResults().length, 1, "retrieval equivalente no debe duplicarse"); assert.equal(retrieval.query.caseId, reviewCase.id); assert.equal(retrieval.query.issueId, outcome.issueId);
    const domainsBeforeInvestigation = JSON.stringify({review: reviewRepository.snapshot(), outcomes: outcomeRepository.snapshot(), memory: memoryRepository.snapshot(), retrieval: retrievalRepository.snapshot()}); const investigation = await investigateReviewIssue(reviewCase.id, outcome.issueId, {mode: "local_only"}); assert.equal(investigation.request.retrieval?.id, retrieval.id); assert.equal(investigation.request.case.resolutions.length, 1); assert.equal(JSON.stringify({review: reviewRepository.snapshot(), outcomes: outcomeRepository.snapshot(), memory: memoryRepository.snapshot(), retrieval: retrievalRepository.snapshot()}), domainsBeforeInvestigation, "5F no puede mutar dominios previos");
    await new Promise((resolve) => setTimeout(resolve, 2)); const repeatedInvestigation = await investigateReviewIssue(reviewCase.id, outcome.issueId, {mode: "local_only"}); assert.notEqual(repeatedInvestigation.id, investigation.id, "una reejecución explícita crea historia nueva"); assert.equal(getReviewInvestigations().length, 2);
    const preview = buildExternalNewsResumePreview(getReviewCase(reviewCase.id)!, {now: () => now}); assert.equal(preview.status, "ready"); assert.equal(preview.canResume, true); const previewFingerprint = createExternalNewsPreviewFingerprint(getReviewCase(reviewCase.id)!, preview);
    let saveCalls = 0; const successfulExecutor: ExternalNewsResumeExecutor = {buildOutput: () => ({title: "Phase 6A output"}), saveDraft: async (_output, options) => { saveCalls += 1; assert.equal(options.idempotencyKey, `external-news-resume:${reviewCase.id}`); return {success: true, draftId: "draft-phase-6a", documentId: "document-phase-6a"}; }};
    const stale = await executeExternalNewsResume({caseId: reviewCase.id, executor: successfulExecutor, options: {expectedCaseVersion: getReviewCase(reviewCase.id)!.version + 1, expectedPreviewFingerprint: previewFingerprint, now: () => now}}); assert.equal(stale.status, "stale_preview"); assert.equal(saveCalls, 0, "preview stale no debe guardar");
    const failingExecutor: ExternalNewsResumeExecutor = {buildOutput: () => ({title: "Phase 6A output"}), saveDraft: async () => ({success: false, error: "controlled_failure"})}; const failed = await executeExternalNewsResume({caseId: reviewCase.id, executor: failingExecutor, options: {expectedCaseVersion: getReviewCase(reviewCase.id)!.version, expectedPreviewFingerprint: createExternalNewsPreviewFingerprint(getReviewCase(reviewCase.id)!, buildExternalNewsResumePreview(getReviewCase(reviewCase.id)!, {now: () => now})), now: () => now}}); assert.equal(failed.status, "draft_save_failed"); assert.equal(getReviewCase(reviewCase.id)!.status, "resume_failed");
    const retryCase = getReviewCase(reviewCase.id)!; const retryPreview = buildExternalNewsResumePreview(retryCase, {now: () => now}); const resumed = await executeExternalNewsResume({caseId: reviewCase.id, executor: successfulExecutor, options: {expectedCaseVersion: retryCase.version, expectedPreviewFingerprint: createExternalNewsPreviewFingerprint(retryCase, retryPreview), now: () => now}}); assert.equal(resumed.status, "succeeded"); assert.equal(getReviewCase(reviewCase.id)!.status, "resumed"); assert.equal(saveCalls, 1); const doubleResume = await executeExternalNewsResume({caseId: reviewCase.id, executor: successfulExecutor}); assert.equal(doubleResume.status, "already_resumed"); assert.equal(saveCalls, 1, "doble resume no debe guardar otra vez");
    const reconciliation = reconcileReviewInvestigations(investigation.id); assert.equal(reconciliation.changed, true); assert.equal(reconciliation.results[0].stale, true); const secondReconciliation = reconcileReviewInvestigations(investigation.id); assert.equal(secondReconciliation.changed, false, "reconciliación repetida debe ser idempotente");
    assert.deepEqual(validateOutcomeStore(), {valid: true, errors: []}); assert.deepEqual(validateDecisionMemoryStore(), {valid: true, errors: []}); assert.deepEqual(validateDecisionRetrievalStore(), {valid: true, errors: []}); assert.deepEqual(validateReviewInvestigationStore(), {valid: true, errors: []});
    const finalOutcome = getOutcomesForCase(reviewCase.id)[0]; const resumeEvents = getOutcomeEvents(finalOutcome.id).filter((event) => event.stage === "resume"); assert.ok(resumeEvents.some((event) => event.type === "resume_failed")); assert.ok(resumeEvents.some((event) => event.type === "resume_succeeded"));
    const executionId = `resume:${reviewCase.id}:${getReviewCase(reviewCase.id)!.resumeExecution!.attemptCount}`; const trace = {caseId: reviewCase.id, issueId: outcome.issueId, resolutionId: outcome.resolutionId, outcomeId: outcome.id, memoryId: memory.id, retrievalId: retrieval.id, investigationId: investigation.id, previewFingerprint: resumed.previewFingerprint, resumeExecutionId: executionId}; assert.ok(Object.values(trace).every(Boolean)); assert.equal(memory.outcomeId, trace.outcomeId); assert.equal(retrieval.query.caseId, trace.caseId); assert.equal(investigation.request.retrieval?.id, trace.retrievalId);
    const reloadedInvestigationRepository = new MemoryInvestigationRepository(); reloadedInvestigationRepository.save(investigationRepository.load()); assert.equal(reloadedInvestigationRepository.load().results.length, 2, "recarga simulada conserva investigación"); assert.equal(JSON.parse(JSON.stringify(memoryRepository.snapshot())).records.length, 1); assert.equal(JSON.parse(JSON.stringify(retrievalRepository.snapshot())).results.length, 1);
    console.log(`Phase 6A trace: ${JSON.stringify(trace)}`); console.log("Phase 6A end-to-end integration validation tests: OK");
  } finally { restoreInvestigation(); restoreRetrieval(); restoreMemory(); restoreOutcome(); restoreReview(); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
