import assert from "node:assert/strict";
import type {DecisionOutcomeRecord} from "../_laboratorio/laboratorio-ia/src/review/outcomes";
import {addDecisionMemoryNote, appendMemoryEvent, buildClusterFingerprint, buildDecisionMemoryFromOutcome, buildMemoryFingerprint, createMemoryFromOutcome, createMemoryRepository, deprecateDecisionMemory, emptyMemoryLedger, evaluateOutcomeMemoryEligibility, exportDecisionMemory, getConfirmedMemories, getContestedMemoryClusters, getDecisionMemories, getInvalidMemories, getMemoryClusters, getMemoryEvents, getRejectedMemories, getReusableMemoryCandidates, invalidateDecisionMemory, markDecisionMemoryObsolete, migrateMemoryLedger, rebuildDecisionMemoryRecords, restoreDecisionMemory, safelyObserveOutcomeForMemory, setMemoryRepositoryForTests, synchronizeMemoryFromOutcome, validateDecisionMemory, validateDecisionMemoryStore} from "../_laboratorio/laboratorio-ia/src/review/memory";

const outcome = (id: string, editorialStatus: DecisionOutcomeRecord["editorialStatus"], overrides: Partial<DecisionOutcomeRecord> = {}): DecisionOutcomeRecord => ({schemaVersion: 1, engineVersion: "5c.1", id, caseId: `case-${id}`, issueId: `issue-${id}`, resolutionId: `resolution-${id}`, decisionFingerprint: "decision:shared", contextFingerprint: "context:shared", inputFingerprint: "input:shared", evidenceFingerprint: `evidence:${id}`, correlationKey: `correlation:${id}`, producer: "external_news", source: `source-${id}`, entityType: "fighter", issueType: "missing_reference", decisionType: "link_reference", reviewSchemaVersion: 1, currentStatus: editorialStatus === "rejected" ? "rejected" : "editorially_confirmed", technicalStatus: "succeeded", structuralStatus: "valid", editorialStatus, operationalStatus: "completed", createdAt: "2026-07-17T10:00:00.000Z", updatedAt: "2026-07-17T11:00:00.000Z", confirmedAt: "2026-07-17T11:00:00.000Z", reconciliationRequired: false, conflicts: [], eventIds: [`event-${id}`], ...overrides});

const repo = createMemoryRepository(); const restore = setMemoryRepositoryForTests(repo);
assert.equal(evaluateOutcomeMemoryEligibility(outcome("pending", "pending_confirmation")).eligible, false, "pending no crea memoria");
assert.equal(createMemoryFromOutcome(outcome("pending", "pending_confirmation")).eligible, false);

const first = createMemoryFromOutcome(outcome("one", "confirmed")); assert.equal(first.created, true); assert.equal(first.record?.reusePolicy, "manual_only");
assert.equal(first.record?.status, "confirmed"); assert.equal(first.record?.confidence.level === "high", false, "una confirmación no es high");
assert.equal(validateDecisionMemory({...first.record!, notes: [(() => "unsafe") as unknown as string]}).valid, false, "funciones rechazadas");
assert.equal(validateDecisionMemory({...first.record!, evidence: [...first.record!.evidence, {kind: "note", value: "x", apiKey: "unsafe"} as never]}).valid, false, "claves sensibles rechazadas");
assert.equal(buildMemoryFingerprint({b: 2, a: 1}), buildMemoryFingerprint({a: 1, b: 2})); assert.notEqual(buildClusterFingerprint({field: "a"}), buildClusterFingerprint({field: "b"}));
const duplicate = createMemoryFromOutcome(outcome("one", "confirmed")); assert.equal(duplicate.created, false, "creación idempotente"); assert.equal(getDecisionMemories().length, 1);
synchronizeMemoryFromOutcome(outcome("one", "confirmed")); synchronizeMemoryFromOutcome(outcome("one", "confirmed")); assert.equal(getMemoryEvents(first.record!.id).filter((item) => item.type === "memory_confirmed").length, 1);
appendMemoryEvent(first.record!.id, "memory_noted", "idempotente", {type: "human", id: "editor"}, "collision", {value: "a"}); assert.throws(() => appendMemoryEvent(first.record!.id, "memory_noted", "idempotente", {type: "human", id: "editor"}, "collision", {value: "b"}));

createMemoryFromOutcome(outcome("two", "confirmed")); let cluster = getMemoryClusters()[0]; assert.equal(cluster.status, "supported"); assert.equal(cluster.caseIds.length, 2); assert.ok(cluster.confidence.score > first.record!.confidence.score, "experiencia independiente aumenta confianza");
createMemoryFromOutcome(outcome("duplicate-case", "confirmed", {caseId: "case-one", source: "source-one"})); cluster = getMemoryClusters()[0]; assert.equal(cluster.caseIds.length, 2, "duplicado del mismo caso no aumenta independencia");

const rejected = createMemoryFromOutcome(outcome("rejected", "rejected")); assert.equal(rejected.record?.reusePolicy, "never"); cluster = getMemoryClusters()[0]; assert.equal(cluster.status, "contested"); assert.ok(cluster.confidence.score <= 25); assert.equal(getContestedMemoryClusters().length, 1); assert.equal(getRejectedMemories().length, 1); assert.equal(getReusableMemoryCandidates().length, 0, "contradicción bloquea candidatos");
const changingConfirmed = synchronizeMemoryFromOutcome(outcome("changing", "confirmed")); const changingId = changingConfirmed.record!.id; synchronizeMemoryFromOutcome(outcome("changing", "rejected", {updatedAt: "2026-07-17T12:00:00.000Z"})); assert.equal(getDecisionMemories().filter((item) => item.outcomeId === "changing").length, 1, "cambio editorial conserva una memoria"); assert.equal(getDecisionMemories().find((item) => item.id === changingId)?.status, "rejected"); assert.ok(getMemoryEvents(changingId).some((item) => item.type === "memory_confirmed") && getMemoryEvents(changingId).some((item) => item.type === "memory_rejected"), "historial confirmado y rechazado preservado");

const incompatible = buildDecisionMemoryFromOutcome(outcome("old", "confirmed", {reviewSchemaVersion: 2})); assert.equal(incompatible?.compatibility.status, "incompatible");
const lifecycleId = first.record!.id; addDecisionMemoryNote(lifecycleId, "editor", "Contexto documentado"); invalidateDecisionMemory(lifecycleId, "editor", "Evidencia invalidada"); assert.equal(getInvalidMemories().some((item) => item.id === lifecycleId), true); restoreDecisionMemory(lifecycleId, "editor", "Nueva validación explícita"); deprecateDecisionMemory(lifecycleId, "editor", "Preferencia anterior"); restoreDecisionMemory(lifecycleId, "editor", "Revisión explícita"); markDecisionMemoryObsolete(lifecycleId, "editor", "Modelo retirado"); assert.equal(getDecisionMemories().find((item) => item.id === lifecycleId)?.status, "obsolete");

assert.ok(getConfirmedMemories().length >= 3); assert.deepEqual(validateDecisionMemoryStore(), {valid: true, errors: []}); const exported = exportDecisionMemory(); assert.deepEqual(rebuildDecisionMemoryRecords(exported.events), [...exported.records].sort((left, right) => left.id.localeCompare(right.id)), "snapshots reconstruibles desde eventos"); assert.doesNotThrow(() => JSON.stringify(exported)); assert.equal(JSON.stringify(exported).includes("function"), false); assert.equal(migrateMemoryLedger(JSON.parse(JSON.stringify(exported))).records.length, exported.records.length); assert.equal(migrateMemoryLedger({broken: true}).records.length, 0);

const failureRepo = {load: () => emptyMemoryLedger(), save: () => { throw new Error("storage_failed"); }}; const restoreFailure = setMemoryRepositoryForTests(failureRepo); assert.doesNotThrow(() => safelyObserveOutcomeForMemory(outcome("observer", "confirmed")), "fallo secundario no afecta outcome"); restoreFailure();
restore();
console.log("Phase 5D decision memory tests: OK");
process.exit(0);
