import assert from "node:assert/strict";
import type {DecisionOutcomeRecord} from "../_laboratorio/laboratorio-ia/src/review/outcomes";
import type {ReviewCase} from "../_laboratorio/laboratorio-ia/src/review/types";
import {buildDecisionMemoryFromOutcome, buildMemoryClusters, createMemoryRepository as createMemoryLedgerRepository, setMemoryRepositoryForTests, type DecisionMemoryRecord} from "../_laboratorio/laboratorio-ia/src/review/memory";
import {buildRetrievalQuery, createMemoryRetrievalRepository, detectRetrievalContradictions, evaluateNegativeEvidence, evaluateRetrievalCompatibility, exportDecisionRetrieval, generateMemoryCandidates, getRetrievalResults, hashRetrievalValue, migrateRetrievalLedger, normalizeRetrievalValue, persistRetrieval, reconcileDecisionRetrieval, retrieveRelevantMemoriesPure, scoreRetrievalCandidate, setRetrievalRepositoryForTests, validateDecisionRetrievalStore, validateRetrievalResult} from "../_laboratorio/laboratorio-ia/src/review/retrieval";

const now = "2026-07-18T10:00:00.000Z";
const reviewCase: ReviewCase = {schemaVersion: 1, id: "case-new", dedupeKey: "5e:test", module: "external.news", title: "Caso", status: "open", priority: "normal", source: "Espabox", subject: {type: "fighter"}, issues: [{id: "issue-new", kind: "missing_entity", valueKind: "fighter", fieldPath: "fighters", label: "Luchador", message: "Falta", currentValue: null, evidence: ["Fuente editorial"]}], resolutions: [{type: "create_entity", issueId: "issue-new", entityType: "fighter", draft: {name: "Erlantz"}}], context: {producer: "external_news"}, createdAt: now, updatedAt: now, version: 1, resumeAttempts: 0};
const outcome = (id: string, editorial: "confirmed" | "rejected", decisionType = "create_entity", fingerprint = "decision:entity"): DecisionOutcomeRecord => ({schemaVersion: 1, engineVersion: "5c.1", id, caseId: `old-${id}`, issueId: `old-issue-${id}`, resolutionId: `old-resolution-${id}`, decisionFingerprint: fingerprint, contextFingerprint: "ctx", inputFingerprint: "input", evidenceFingerprint: `evidence:${id}`, correlationKey: id, producer: "external_news", source: "Espabox", entityType: "fighter", issueType: "missing_entity", decisionType, reviewSchemaVersion: 1, currentStatus: editorial === "confirmed" ? "editorially_confirmed" : "rejected", technicalStatus: "succeeded", structuralStatus: "valid", editorialStatus: editorial, operationalStatus: "unknown", createdAt: now, updatedAt: now, confirmedAt: now, reconciliationRequired: false, conflicts: [], eventIds: [`event:${id}`]});
const memory = (id: string, editorial: "confirmed" | "rejected", overrides: Partial<DecisionMemoryRecord> = {}) => ({...buildDecisionMemoryFromOutcome(outcome(id, editorial))!, id: `memory:${id}`, ...overrides});

const snapshot = structuredClone(reviewCase); const query = buildRetrievalQuery(reviewCase, reviewCase.issues[0], {now}); assert.deepEqual(reviewCase, snapshot, "query no muta el caso"); assert.equal(query.issueType, "missing_entity"); assert.equal(query.decisionType, "create_entity"); assert.equal(query.entityType, "fighter"); assert.deepEqual(normalizeRetrievalValue({b: 2, a: 1, updatedAt: "x"}), {a: 1, b: 2}); assert.equal(buildRetrievalQuery(reviewCase, reviewCase.issues[0], {now}).queryFingerprint, query.queryFingerprint); assert.ok(query.missingDimensions.includes("currentValue") === false, "null es un valor disponible");
const sparseCase = {...reviewCase, resolutions: [], issues: [{...reviewCase.issues[0], valueKind: undefined, currentValue: undefined, fieldPath: undefined}]}; const sparse = buildRetrievalQuery(sparseCase, sparseCase.issues[0], {now}); assert.ok(sparse.missingDimensions.includes("decisionType") && sparse.limitations.length > 0);

const confirmed = memory("confirmed", "confirmed"); const rejected = memory("rejected", "rejected"); const incompatible = memory("incompatible", "confirmed", {entityType: "event"}); const invalidated = memory("invalidated", "confirmed", {status: "invalidated"}); const deprecated = memory("deprecated", "confirmed", {status: "deprecated"}); const superseded = memory("superseded", "confirmed", {status: "superseded"}); const memories = [confirmed, rejected, incompatible, invalidated, deprecated, superseded]; const clusters = buildMemoryClusters(memories, now); const contested = clusters.find((item) => item.id === confirmed.clusterId); assert.equal(contested?.status, "contested");
const generated = generateMemoryCandidates(query, memories, 3); assert.equal(generated.length, 3, "límite de candidatos"); assert.deepEqual(generateMemoryCandidates(query, memories, 3).map((item) => item.id), generated.map((item) => item.id), "orden estable"); assert.equal(generateMemoryCandidates({...query, issueType: "invalid_url", entityType: "url"}, memories).length, 0, "sin búsqueda textual genérica");
assert.equal(evaluateRetrievalCompatibility(query, confirmed, contested).status, "exact"); assert.equal(evaluateRetrievalCompatibility(query, incompatible).status, "incompatible"); assert.equal(evaluateRetrievalCompatibility({...query, decisionType: undefined}, confirmed).status, "partially_compatible"); assert.equal(evaluateRetrievalCompatibility({...query, producer: "otro"}, confirmed).status, "compatible"); assert.equal(evaluateRetrievalCompatibility(query, invalidated).status, "incompatible");
const positiveScore = scoreRetrievalCandidate(query, confirmed, contested); const negativeScore = scoreRetrievalCandidate(query, rejected, contested); assert.ok(positiveScore.finalScore >= 0 && positiveScore.finalScore <= 100); assert.ok(positiveScore.contradictionPenalty > 0); assert.equal(negativeScore.positiveOrNegative, "negative"); assert.match(evaluateNegativeEvidence(negativeScore).message, /no como regla universal/); assert.equal(scoreRetrievalCandidate(query, incompatible).candidateStatus, "excluded"); assert.notEqual(scoreRetrievalCandidate(query, deprecated).candidateStatus, "strongly_relevant");
const contradictions = detectRetrievalContradictions([positiveScore, negativeScore]); assert.ok(contradictions.length >= 1); const result = retrieveRelevantMemoriesPure(query, memories, clusters); assert.equal(result.status, "contradictory_evidence"); assert.ok(result.positiveEvidence.length && result.negativeEvidence.length); assert.equal(validateRetrievalResult(result).valid, true); assert.equal(result.summary.some((item) => /autoriza/.test(item)), true);

const memoryRepo = createMemoryLedgerRepository({schemaVersion: 1, records: memories, events: [], clusters, clusterEvents: []}); const restoreMemory = setMemoryRepositoryForTests(memoryRepo); const retrievalRepo = createMemoryRetrievalRepository(); const restoreRetrieval = setRetrievalRepositoryForTests(retrievalRepo); const caseBefore = structuredClone(reviewCase); const memoryBefore = memoryRepo.snapshot(); const stored = persistRetrieval(query); assert.equal(getRetrievalResults().length, 1); persistRetrieval(query); assert.equal(getRetrievalResults().length, 1, "retry no duplica resultados ni eventos"); assert.deepEqual(reviewCase, caseBefore); assert.deepEqual(memoryRepo.snapshot(), memoryBefore, "retrieval no modifica memoria"); assert.equal(validateDecisionRetrievalStore().valid, true); assert.doesNotThrow(() => JSON.stringify(exportDecisionRetrieval())); assert.equal(migrateRetrievalLedger(JSON.parse(JSON.stringify(exportDecisionRetrieval()))).results.length, 1); assert.equal(migrateRetrievalLedger({broken: true}).results.length, 0);
memoryRepo.save({...memoryRepo.snapshot(), records: memories.map((item) => item.id === confirmed.id ? {...item, updatedAt: "2026-07-19T00:00:00.000Z"} : item)}); assert.equal(reconcileDecisionRetrieval(stored.id).changed, true); assert.equal(getRetrievalResults()[0].stale, true); assert.ok(hashRetrievalValue(exportDecisionRetrieval()).length > 0);
restoreRetrieval(); restoreMemory();
console.log("Phase 5E relevant decision retrieval tests: OK");
process.exit(0);
