import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import * as u from "../_laboratorio/laboratorio-ia/src/review/universal";

const now="2026-07-18T12:00:00.000Z",snapshot={title:"Original"};
const resume=u.buildResumeContract({producerId:"test",operationId:"op",operationType:"update",checkpoint:"ready",snapshotVersion:1,snapshot,requiredCapabilities:[],idempotencyKey:"test:op"});
const input:u.UniversalReviewInput={schemaVersion:1,logicalKey:"test:case",producerId:"test",operationId:"op",operationType:"update",module:"test",entity:{type:"news"},issueFamily:"invalid_metadata",issueCode:"invalid_title",priority:"high",title:"Test",snapshot,issues:[{id:"issue",kind:"invalid_value",label:"Title",message:"Invalid"}],evidence:[],constraints:[],resume};
const reviewCase={id:"case",version:1,subject:{type:"news"},context:{}};
const effect=(id:string,value="Corrected"):u.ReviewEffect=>({id,type:"set_field",path:"title",value});
const post=(id:string,indexes:number[]):u.PostExecutionCheck=>({id,kind:"field_equals",description:"Persisted",expected:"Corrected",required:true,effectIndexes:indexes});
const plan=(effects:u.ReviewEffect[]=[effect("set")],posts:u.PostExecutionCheck[]=[post("post",[0])])=>u.buildUniversalExecutionPlan({reviewCase,reviewInput:input,effects,postconditions:posts,now:()=>now});
function executor(id:string,capability:string,effects:u.ReviewEffect["type"][],log:string[],risk:u.ExecutorRisk="low"):u.ReviewExecutorRegistration{return{executorId:id,version:1,capability,supportedEffects:effects,supportedEntityTypes:["news"],risk,canExecute:()=>true,async simulate(_p,_s,indexes){const b=u.getRegisteredReviewExecutor(id)!;return{executorId:id,executorVersion:1,executorManifestFingerprint:b.manifestFingerprint,capability,status:"safe",effectIndexes:indexes,changes:[{executor:id}],warnings:[],blockingReasons:[],errors:[]}},async execute(_p,_s,indexes,o){log.push(id);const b=u.getRegisteredReviewExecutor(id)!;return{executorId:id,executorVersion:1,executorManifestFingerprint:b.manifestFingerprint,capability,status:"succeeded",effectIndexes:indexes,idempotencyKey:o.idempotencyKey,references:[]}},async validateExecution(p,r){return{valid:true,planFingerprint:p.planFingerprint,executorId:id,executionIdempotencyKey:r.idempotencyKey,checkedPostconditionIds:p.postconditions.filter((x)=>x.effectIndexes.some((i)=>r.effectIndexes.includes(i))).map((x)=>x.id),checkedEffectIndexes:r.effectIndexes,errors:[],warnings:[],validatedAt:now}}};}

async function main(){
  assert.equal(u.computeUniversalFingerprint({a:1,b:2}),u.computeUniversalFingerprint({b:2,a:1}));assert.notEqual(u.computeUniversalFingerprint([1,2]),u.computeUniversalFingerprint([2,1]));assert.equal(u.computeUniversalFingerprint("abc"),`sha256-v1:${createHash("sha256").update(JSON.stringify("abc")).digest("hex")}`);assert.notEqual(u.computeSnapshotFingerprint(snapshot),u.computeSnapshotFingerprint({title:"Changed"}));
  assert.equal(u.validateUniversalReviewInput({...input,snapshot:{title:"Changed"}}).valid,false);assert.doesNotThrow(()=>u.validateUniversalReviewInput(null));assert.doesNotThrow(()=>u.validateUniversalExecutionPlan({}));
  const p=plan();assert.equal(Object.isFrozen(p),true);assert.equal(Object.isFrozen(p.effects),true);assert.throws(()=>{(p.effects[0] as {path:string}).path="other"});const tampered=structuredClone(p);tampered.effects[0]=effect("set","Mutated");assert.equal(u.validateUniversalExecutionPlan(tampered).valid,false);assert.throws(()=>plan([effect("write")],[]));
  assert.throws(()=>plan([{id:"danger",type:"set_field",path:"__proto__.x",value:1}],[post("p",[0])]));assert.throws(()=>plan([{id:"secret",type:"create_entity",entityType:"news",payload:{apiKey:"x"}}],[post("p",[0])]));
  const log:string[]=[];const unA=u.registerReviewExecutor(executor("a","write",["set_field"],log));const unB=u.registerReviewExecutor(executor("b","write",["set_field"],log));try{assert.equal((await u.simulateUniversalExecutionPlan(p,snapshot,{now:()=>now})).status,"unsupported")}finally{unB();unA()}
  const selectorLog:string[]=[];const usa=u.registerReviewExecutor(executor("selected","write",["set_field"],selectorLog));const usb=u.registerReviewExecutor(executor("ignored","write",["set_field"],selectorLog));try{const selected=plan([{...effect("selected-effect"),executorSelector:{executorId:"selected"}}]);assert.equal((await u.simulateUniversalExecutionPlan(selected,snapshot,{now:()=>now})).status,"safe")}finally{usb();usa()}
  const mutable=executor("immutable","write",["set_field"],log);const unMutable=u.registerReviewExecutor(mutable);try{mutable.supportedEffects.push("create_entity");assert.deepEqual(u.getReviewExecutor("immutable")?.supportedEffects,["set_field"])}finally{unMutable()}
  let listenerCalled=0;const removeListener=u.subscribeReviewExecutors(()=>{listenerCalled+=1;throw new Error("listener")});const unListener=u.registerReviewExecutor(executor("listener","write",["set_field"],log));assert.ok(u.getReviewExecutor("listener"));unListener();removeListener();assert.equal(listenerCalled,2);
  const unOriginal=u.registerReviewExecutor(executor("bound","write",["set_field"],log));const boundPlan=u.buildUniversalExecutionPlan({reviewCase,reviewInput:{...input,resume:{...resume,requiredCapabilities:["write"]}},effects:[effect("set")],postconditions:[post("post",[0])],now:()=>now});const boundSimulation=await u.simulateUniversalExecutionPlan(boundPlan,snapshot,{now:()=>now});const unReplacement=u.registerReviewExecutor({...executor("bound","write",["set_field"],log),version:2},{replace:true});try{const result=await u.executeUniversalExecutionPlan(boundPlan,snapshot,boundSimulation,{now:()=>now});assert.equal(result.status,"blocked");assert.equal(result.error?.code,"executor_outside_policy_or_changed")}finally{unReplacement();unOriginal()}
  assert.equal(u.validateUniversalSimulation(boundSimulation,boundPlan,{title:"Changed"}).valid,false);assert.equal(u.validateSimulationResult({...boundSimulation.simulations[0],status:"safe",blockingReasons:["blocked"]},boundPlan).valid,false);
  const ordered:string[]=[];const unCreate=u.registerReviewExecutor(executor("z-create","create",["create_entity"],ordered));const unLink=u.registerReviewExecutor(executor("a-link","link",["replace_reference"],ordered));try{const orderedPlan=plan([{id:"create",type:"create_entity",entityType:"fighter",payload:{name:"X"}},{id:"link",type:"replace_reference",path:"fighter",referenceId:"new"}],[post("created",[0]),post("linked",[1])]);const sim=await u.simulateUniversalExecutionPlan(orderedPlan,snapshot,{now:()=>now});assert.equal(sim.status,"safe");const result=await u.executeUniversalExecutionPlan(orderedPlan,snapshot,sim,{now:()=>now,policy:{allowedRiskLevels:["low"]}});assert.equal(result.status,"succeeded");assert.deepEqual(ordered,["z-create","a-link"])}finally{unLink();unCreate()}
  const riskLog:string[]=[];const unRisk=u.registerReviewExecutor(executor("critical","danger",["set_field"],riskLog,"critical"));try{const rp=u.buildUniversalExecutionPlan({reviewCase,reviewInput:{...input,resume:{...resume,requiredCapabilities:["danger"]}},effects:[effect("risk")],postconditions:[post("post",[0])],now:()=>now});const sim=await u.simulateUniversalExecutionPlan(rp,snapshot,{now:()=>now});assert.equal((await u.executeUniversalExecutionPlan(rp,snapshot,sim,{now:()=>now,policy:{allowedRiskLevels:["critical"]}})).status,"blocked")}finally{unRisk()}
  const cancelLog:string[]=[];const unCancel=u.registerReviewExecutor(executor("cancel","write",["set_field"],cancelLog));try{const sim=await u.simulateUniversalExecutionPlan(p,snapshot,{now:()=>now});const controller=new AbortController();controller.abort();const cancelled=await u.executeUniversalExecutionPlan(p,snapshot,sim,{signal:controller.signal,now:()=>now,policy:{allowedRiskLevels:["low"]}});assert.equal(cancelled.status,"cancelled");assert.equal(cancelLog.length,0)}finally{unCancel()}
  let concurrentCalls=0;let release!:()=>void;const gate=new Promise<void>((resolve)=>{release=resolve});const concurrent=executor("concurrent","write",["set_field"],[]);concurrent.execute=async(_p,_s,indexes,o)=>{concurrentCalls+=1;await gate;const b=u.getRegisteredReviewExecutor("concurrent")!;return{executorId:"concurrent",executorVersion:1,executorManifestFingerprint:b.manifestFingerprint,capability:"write",status:"succeeded",effectIndexes:indexes,idempotencyKey:o.idempotencyKey,references:[]}};const uc=u.registerReviewExecutor(concurrent);try{const sim=await u.simulateUniversalExecutionPlan(p,snapshot,{now:()=>now});const first=u.executeUniversalExecutionPlan(p,snapshot,sim,{now:()=>now,policy:{allowedRiskLevels:["low"]}});const second=u.executeUniversalExecutionPlan(p,snapshot,sim,{now:()=>now,policy:{allowedRiskLevels:["low"]}});assert.equal(first,second);release();assert.equal((await first).status,"succeeded");assert.equal(concurrentCalls,1)}finally{uc()}
  const compensationOrder:string[]=[];const firstExecutor=executor("first","first",["create_entity"],compensationOrder);firstExecutor.compensate=async(_p,r)=>{compensationOrder.push("undo-first");const b=u.getRegisteredReviewExecutor("first")!;return{executorId:"first",executorVersion:1,executorManifestFingerprint:b.manifestFingerprint,status:"compensated",effectIndexes:r.effectIndexes,message:"undone"}};const secondExecutor=executor("second","second",["replace_reference"],compensationOrder);secondExecutor.execute=async(_p,_s,indexes,o)=>{compensationOrder.push("second");const b=u.getRegisteredReviewExecutor("second")!;return{executorId:"second",executorVersion:1,executorManifestFingerprint:b.manifestFingerprint,capability:"second",status:"failed",effectIndexes:indexes,idempotencyKey:o.idempotencyKey,references:[],error:{code:"injected",message:"fail",retryable:true}}};const uf=u.registerReviewExecutor(firstExecutor),us=u.registerReviewExecutor(secondExecutor);try{const cp=plan([{id:"create",type:"create_entity",entityType:"fighter",payload:{name:"X"}},{id:"link",type:"replace_reference",path:"fighter",referenceId:"new"}],[post("created",[0]),post("linked",[1])]);const sim=await u.simulateUniversalExecutionPlan(cp,snapshot,{now:()=>now});const result=await u.executeUniversalExecutionPlan(cp,snapshot,sim,{now:()=>now,policy:{allowedRiskLevels:["low"]}});assert.equal(result.status,"failed");assert.deepEqual(compensationOrder,["first","second","undo-first"])}finally{us();uf()}
  const malformed=executor("malformed","write",["set_field"],[]);malformed.execute=async(_p,_s,indexes,o)=>({executorId:"wrong",executorVersion:1,executorManifestFingerprint:u.computeUniversalFingerprint({}),capability:"write",status:"succeeded",effectIndexes:indexes,idempotencyKey:o.idempotencyKey,references:[]});const um=u.registerReviewExecutor(malformed);try{const sim=await u.simulateUniversalExecutionPlan(p,snapshot,{now:()=>now});assert.equal((await u.executeUniversalExecutionPlan(p,snapshot,sim,{now:()=>now,policy:{allowedRiskLevels:["low"]}})).status,"failed")}finally{um()}
  const incompleteValidation=executor("incomplete-validation","write",["set_field"],[]);incompleteValidation.validateExecution=async(pv,r)=>({valid:true,planFingerprint:pv.planFingerprint,executorId:"incomplete-validation",executionIdempotencyKey:r.idempotencyKey,checkedPostconditionIds:[],checkedEffectIndexes:[],errors:[],warnings:[],validatedAt:now});const uiv=u.registerReviewExecutor(incompleteValidation);try{const sim=await u.simulateUniversalExecutionPlan(p,snapshot,{now:()=>now});assert.equal((await u.executeUniversalExecutionPlan(p,snapshot,sim,{now:()=>now,policy:{allowedRiskLevels:["low"]}})).status,"reconciliation_required")}finally{uiv()}
  console.log(`AU1.1 summary: ${JSON.stringify({fingerprints:true,immutablePlan:true,snapshotBinding:true,postconditions:true,paths:true,secrets:true,ambiguity:true,explicitSelector:true,manifestImmutability:true,executorBinding:true,causalOrder:true,riskPolicy:true,cancellation:true,concurrentDedupe:true,reverseCompensation:true,malformedResultRejected:true})}`);console.log("AU1.1 universal hardening tests: OK");
}
main().catch((error)=>{console.error(error);process.exitCode=1});
