import assert from "node:assert/strict";
import {applyAutonomousReview, previewAutonomousReview} from "../_laboratorio/laboratorio-ia/src/review/autonomous";
import {createReviewCase, getReviewCase, getReviewCases, setReviewCaseRepositoryForTests} from "../_laboratorio/laboratorio-ia/src/review/store/reviewStore";
import type {CreateReviewCaseInput, ReviewCase} from "../_laboratorio/laboratorio-ia/src/review/types";
import {confirmEditorialOutcome, createMemoryOutcomeRepository, getOutcomesForCase, rejectEditorialOutcome, setOutcomeRepositoryForTests, validateOutcomeStore} from "../_laboratorio/laboratorio-ia/src/review/outcomes";
import {createMemoryFromOutcome, createMemoryRepository, emptyMemoryLedger, getDecisionMemories, setMemoryRepositoryForTests, validateDecisionMemoryStore} from "../_laboratorio/laboratorio-ia/src/review/memory";
import {buildRetrievalQuery} from "../_laboratorio/laboratorio-ia/src/review/retrieval/buildRetrievalQuery";
import {createMemoryRetrievalRepository, getRetrievalResultsForCase, persistRetrieval, setRetrievalRepositoryForTests, validateDecisionRetrievalStore} from "../_laboratorio/laboratorio-ia/src/review/retrieval";
import {getReviewInvestigationsForCase, investigateReviewIssue, MemoryInvestigationRepository, setInvestigationRepositoryForTests, validateReviewInvestigationStore} from "../_laboratorio/laboratorio-ia/src/review/investigation/deep";
import {buildExternalNewsResumePreview, createExternalNewsPreviewFingerprint, executeExternalNewsResume, type ExternalNewsResumeExecutor} from "../_laboratorio/laboratorio-ia/src/review/resume/externalNews";

const now = "2026-07-17T15:00:00.000Z";
class ReviewMemoryRepository { constructor(private cases: ReviewCase[] = []) {} load() { return structuredClone(this.cases); } save(cases: readonly ReviewCase[]) { this.cases = structuredClone([...cases]); } snapshot() { return structuredClone(this.cases); } }
const reviewRepo = new ReviewMemoryRepository(); const outcomeRepo = createMemoryOutcomeRepository(); const memoryRepo = createMemoryRepository(emptyMemoryLedger()); const retrievalRepo = createMemoryRetrievalRepository(); const investigationRepo = new MemoryInvestigationRepository();
const restore = [setReviewCaseRepositoryForTests(reviewRepo), setOutcomeRepositoryForTests(outcomeRepo), setMemoryRepositoryForTests(memoryRepo), setRetrievalRepositoryForTests(retrievalRepo), setInvestigationRepositoryForTests(investigationRepo)];
const context = (sourceId: string, sourceName: string, url: string, title: string, organization: string, discipline: string) => ({producer: "external_news", sourceId, sourceName, sourceUrl: url, canonicalUrl: url, externalItemId: `${sourceId}:${title}`, title, operation: "create_draft", createdAt: now, payloadSnapshot: {id: `${sourceId}:${title}`, title, excerpt: title, bodyText: `${title}. Payload sanitizado derivado de datos y contratos conservados en FFN3.`, canonicalUrl: url, publishedAt: now, image: {url: `${url}/image.jpg`}}, analysisSnapshot: {analysis: {relevancia: "alta", disciplinaPrincipal: discipline, organizacionPrincipal: organization}, resolved: {disciplina: {id: `discipline-${discipline.toLowerCase().replaceAll(" ", "-")}`, label: discipline}, organizacion: {id: `organization-${organization.toLowerCase().replaceAll(" ", "-")}`, label: organization}, evento: null, luchadoresPrincipales: [], luchadoresSecundarios: []}}});
const safeIssue = (id: string, kind: "missing_reference" | "contradictory_data", valueKind: "discipline" | "organization", label: string, sanityId: string) => ({id, kind, valueKind, fieldPath: valueKind, label, message: `${label} requiere validación`, required: true, blocking: true, candidates: [{id: sanityId, label, value: {id: sanityId}, sanityId, confidence: 99}]});
const fixtures: CreateReviewCaseInput[] = [
  {dedupeKey: "6b:ufc:312", module: "ufc.events", title: "UFC 312", priority: "high", source: "UFC", subject: {type: "event", id: "evento-ufc-312", label: "UFC 312", sourceUrl: "https://www.ufc.com/event/ufc-312"}, issues: [safeIssue("ufc312:discipline", "missing_reference", "discipline", "MMA", "discipline-mma")], context: context("ufc", "UFC", "https://www.ufc.com/event/ufc-312", "UFC 312: Du Plessis vs Strickland 2", "UFC", "MMA")},
  {dedupeKey: "6b:ufc:310:kai", module: "ufc.events", title: "UFC 310 — Kai Asakura ausente", priority: "high", source: "UFC", subject: {type: "event", id: "evento-ufc-310", label: "UFC 310", sourceUrl: "https://www.ufc.com/event/ufc-310"}, issues: [{id: "ufc310:kai", kind: "missing_entity", valueKind: "fighter", fieldPath: "fighters", label: "Kai Asakura", message: "El propio lote indica que el luchador no existe todavía.", required: true, blocking: true, expected: {mentionedLabel: "Kai Asakura", entityType: "fighter"}}], context: context("ufc", "UFC", "https://www.ufc.com/event/ufc-310", "UFC 310: Pantoja vs Kai Asakura", "UFC", "MMA")},
  {dedupeKey: "6b:one:discipline", module: "one.news", title: "ONE Championship — Muay Thai", priority: "high", source: "ONE Championship", subject: {type: "news", id: "one-muay-thai", label: "ONE Muay Thai", sourceUrl: "https://www.onefc.com/news/"}, issues: [safeIssue("one:discipline", "contradictory_data", "discipline", "Muay Thai", "discipline-muay-thai")], context: context("one", "ONE Championship", "https://www.onefc.com/news/", "ONE Championship Muay Thai", "ONE Championship", "Muay Thai")},
  {dedupeKey: "6b:bkfc:bare-knuckle", module: "bkfc.news", title: "BKFC — Bare Knuckle", priority: "high", source: "BKFC", subject: {type: "news", id: "bkfc-bare-knuckle", label: "BKFC", sourceUrl: "https://www.bkfc.com/news"}, issues: [safeIssue("bkfc:discipline", "missing_reference", "discipline", "Bare Knuckle", "discipline-bare-knuckle")], context: context("bkfc", "BKFC", "https://www.bkfc.com/news", "BKFC Bare Knuckle", "BKFC", "Bare Knuckle")},
  {dedupeKey: "6b:espabox:erlantz", module: "external.news", title: "Erlantz Tejada y Rodrigo Caraballo, en el peso", priority: "high", source: "Espabox", subject: {type: "external_news", id: "espabox-erlantz", label: "Erlantz Tejada", sourceUrl: "https://www.espabox.com/"}, issues: [{id: "espabox:erlantz", kind: "missing_entity", valueKind: "fighter", fieldPath: "fighter", label: "Erlantz Tejada", message: "Sin referencia inequívoca", required: true, blocking: true, expected: {mentionedLabel: "Erlantz Tejada", entityType: "fighter"}}], context: context("espabox", "Espabox", "https://www.espabox.com/", "Erlantz Tejada y Rodrigo Caraballo", "WBA", "Boxeo")},
  {dedupeKey: "6b:marca:ambiguous", module: "external.news", title: "Dos luchadores preparan un evento", priority: "normal", source: "Marca", subject: {type: "external_news", id: "marca-ambiguous", label: "Noticia Marca", sourceUrl: "https://www.marca.com/combates/"}, issues: [{id: "marca:fighter", kind: "ambiguous_reference", valueKind: "fighter", fieldPath: "fighter", label: "Luchador ambiguo", message: "Dos candidatos próximos", required: true, blocking: true, candidates: [{id: "fighter-a", label: "Candidato A", value: {id: "fighter-a"}, sanityId: "fighter-a", confidence: 89}, {id: "fighter-b", label: "Candidato B", value: {id: "fighter-b"}, sanityId: "fighter-b", confidence: 87}]}], context: context("marca", "Marca", "https://www.marca.com/combates/", "Dos luchadores preparan un evento", "UFC", "MMA")},
];

async function main() {
  try {
    assert.deepEqual(validateOutcomeStore(), {valid: true, errors: []}); assert.deepEqual(validateDecisionMemoryStore(), {valid: true, errors: []}); assert.deepEqual(validateDecisionRetrievalStore(), {valid: true, errors: []}); assert.deepEqual(validateReviewInvestigationStore(), {valid: true, errors: []});
    const cases = fixtures.map(createReviewCase); fixtures.forEach(createReviewCase); assert.equal(getReviewCases().length, 6, "detección repetida debe deduplicar los seis casos"); cases.forEach((item) => { assert.ok(item.source); assert.ok(item.subject.id); assert.ok(item.subject.sourceUrl); });
    assert.equal(cases[2].context.analysisSnapshot && (cases[2].context.analysisSnapshot as {analysis: {organizacionPrincipal: string; disciplinaPrincipal: string}}).analysis.organizacionPrincipal, "ONE Championship"); assert.equal((cases[2].context.analysisSnapshot as {analysis: {disciplinaPrincipal: string}}).analysis.disciplinaPrincipal, "Muay Thai"); assert.equal((cases[3].context.analysisSnapshot as {analysis: {organizacionPrincipal: string}}).analysis.organizacionPrincipal, "BKFC"); assert.equal((cases[3].context.analysisSnapshot as {analysis: {disciplinaPrincipal: string}}).analysis.disciplinaPrincipal, "Bare Knuckle");
    const previews = cases.map((item) => previewAutonomousReview(item.id)); assert.equal(previews[1].needsMoreEvidenceCount > 0, true); assert.equal(previews[4].needsMoreEvidenceCount > 0, true); assert.equal(previews[5].needsMoreEvidenceCount > 0, true); [0, 2, 3].forEach((index) => { const applied = applyAutonomousReview(cases[index].id); assert.equal(applied.application?.applied.length, 1); assert.equal(applyAutonomousReview(cases[index].id).application?.applied.length, 0); });
    const safeOutcomes = [0, 2, 3].map((index) => getOutcomesForCase(cases[index].id)[0]); const confirmedUfc = confirmEditorialOutcome(safeOutcomes[0].id, "6b-editor", "Evidencia estructurada del lote UFC").record; const confirmedOne = confirmEditorialOutcome(safeOutcomes[1].id, "6b-editor", "Separación organización/disciplina demostrada").record; const rejectedBkfc = rejectEditorialOutcome(safeOutcomes[2].id, "6b-editor", "Conservar como evidencia negativa contextual de prueba").record; [confirmedUfc, confirmedOne, rejectedBkfc].forEach((item) => createMemoryFromOutcome(item)); assert.equal(getDecisionMemories().length, 3); assert.equal(getDecisionMemories().find((item) => item.outcomeId === rejectedBkfc.id)?.reusePolicy, "never");
    const traces: Array<Record<string, string>> = [];
    for (const reviewCase of cases) {
      const current = getReviewCase(reviewCase.id)!; const issue = current.issues[0]; const retrieval = persistRetrieval(buildRetrievalQuery(current, issue, {now})); const before = JSON.stringify({review: reviewRepo.snapshot(), outcome: outcomeRepo.snapshot(), memory: memoryRepo.snapshot(), retrieval: retrievalRepo.snapshot()}); const investigation = await investigateReviewIssue(current.id, issue.id, {mode: "local_only"}); const after = JSON.stringify({review: reviewRepo.snapshot(), outcome: outcomeRepo.snapshot(), memory: memoryRepo.snapshot(), retrieval: retrievalRepo.snapshot()}); assert.equal(after, before, `5F mutó un dominio previo en ${current.title}`); assert.equal(investigation.request.retrieval?.id, retrieval.id); traces.push({caseId: current.id, issueId: issue.id, retrievalId: retrieval.id, investigationId: investigation.id});
    }
    const ufc = getReviewCase(cases[0].id)!; const ufcPreview = buildExternalNewsResumePreview(ufc, {now: () => now}); assert.equal(ufcPreview.canResume, true); const fingerprint = createExternalNewsPreviewFingerprint(ufc, ufcPreview); let saves = 0; const executor: ExternalNewsResumeExecutor = {buildOutput: () => ({title: "UFC 312 controlled output"}), saveDraft: async () => { saves += 1; return {success: true, draftId: "draft-6b-controlled"}; }}; const resumed = await executeExternalNewsResume({caseId: ufc.id, executor, options: {expectedCaseVersion: ufc.version, expectedPreviewFingerprint: fingerprint, now: () => now}}); assert.equal(resumed.status, "succeeded"); assert.equal((await executeExternalNewsResume({caseId: ufc.id, executor})).status, "already_resumed"); assert.equal(saves, 1); traces[0] = {...traces[0], resolutionId: safeOutcomes[0].resolutionId, outcomeId: safeOutcomes[0].id, memoryId: getDecisionMemories().find((item) => item.outcomeId === safeOutcomes[0].id)!.id, previewFingerprint: resumed.previewFingerprint!, resumeExecutionId: `resume:${ufc.id}:1`};
    const onePreview = buildExternalNewsResumePreview(getReviewCase(cases[2].id)!, {now: () => now}); traces[2] = {...traces[2], resolutionId: safeOutcomes[1].resolutionId, outcomeId: safeOutcomes[1].id, memoryId: getDecisionMemories().find((item) => item.outcomeId === safeOutcomes[1].id)!.id, previewFingerprint: createExternalNewsPreviewFingerprint(getReviewCase(cases[2].id)!, onePreview)};
    assert.equal(getReviewCase(cases[4].id)!.resolutions.length, 0); assert.equal(getReviewCase(cases[5].id)!.resolutions.length, 0); assert.equal(getReviewInvestigationsForCase(cases[4].id)[0].sufficiency.status === "insufficient", true); assert.equal(getRetrievalResultsForCase(cases[4].id).length, 1);
    assert.deepEqual(validateOutcomeStore(), {valid: true, errors: []}); assert.deepEqual(validateDecisionMemoryStore(), {valid: true, errors: []}); assert.deepEqual(validateDecisionRetrievalStore(), {valid: true, errors: []}); assert.deepEqual(validateReviewInvestigationStore(), {valid: true, errors: []}); assert.equal(resumed.documentId, undefined, "el executor controlado no publica ni crea documento editorial real");
    console.log(`Phase 6B traces: ${JSON.stringify(traces)}`); console.log("Phase 6B real-world case validation tests: OK");
  } finally { restore.reverse().forEach((item) => item()); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
