import assert from "node:assert/strict";
import {buildEntityOperation} from "../_laboratorio/laboratorio-ia/src/review/entityOperations";
import {finalizeGlobalResolutionPlan, resolveGlobalResolutionPlanningPolicy} from "../_laboratorio/laboratorio-ia/src/review/globalResolution";
import type {ExecutionResult, PostExecutionValidation, RegisteredReviewExecutor, UniversalExecutionPlan} from "../_laboratorio/laboratorio-ia/src/review/universal";
import {
  buildTransactionIncidentSummary, buildTransactionOperationalView, buildUniversalTransactionPlan,
  createTransactionExecutionAuthorization, createTransactionExecutionRuntime, createUniversalTransactionCheckpoint,
  orchestrateTransaction, policyForTransactionIncident, transactionOrchestratorSecurity,
  type TransactionCheckpointApplication, type TransactionCheckpointSnapshot, type TransactionExecutionRuntime,
  type TransactionOrchestrationRuntime, type UniversalTransactionCheckpoint, type UniversalTransactionPlan,
} from "../_laboratorio/laboratorio-ia/src/review/transactions";

const NOW = "2026-08-11T10:00:00.000Z";
let assertions = 0;
const check = (value: unknown, message?: string): void => { assert.ok(value, message); assertions += 1; };
const equal = <T>(actual: T, expected: T): void => { assert.equal(actual, expected); assertions += 1; };

const caps = ["create:luchador", "replace_reference:noticia:luchador", "validate:noticia", "resume:external_news"] as const;
function transaction(options: {independent?: boolean; high?: boolean; resumeAuth?: boolean} = {}): UniversalTransactionPlan {
  const ids = ["create", "reference", "validate", "resume"];
  const operations = ids.map((id, index) => buildEntityOperation({id, kind: "validate_entity", entityType: "noticia", payload: {id}, source: "global_resolution", evidence: [], confidence: 1, risk: options.high && id === "create" ? "high" : "low", preconditions: [], postconditions: [], dependencyIds: options.independent ? [] : index ? [ids[index - 1]] : [], requiredCapability: caps[index], compensatable: false, explanation: id}));
  const planned = finalizeGlobalResolutionPlan({caseId: "case:b5", caseVersion: 1, producer: "fixture", originalOperation: "fixture", operations, policy: resolveGlobalResolutionPlanningPolicy({availableCapabilities: [...caps], maximumRisk: "high"}), graphMetadata: {completionMode: "entity_resolution"}, now: () => NOW});
  if (!planned.ok) throw new Error(JSON.stringify(planned));
  const built = buildUniversalTransactionPlan(planned.plan, {sourceCheckpointFingerprint: "sha256-v1:source", bindings: planned.plan.operations.map((operation, index) => ({operationId: operation.id, capability: caps[index], mode: "external_effect" as const, risk: options.high && operation.id === "create" ? "high" as const : "low" as const, authorization: operation.id === "resume" && options.resumeAuth !== false ? "human_required" as const : "none" as const, retry: "after_reconciliation" as const, reconciliation: "required_before_retry" as const, compensation: "none" as const, executorId: `executor:${operation.id}`, executorVersion: 1, executorManifestFingerprint: `sha256-v1:${operation.id}`, preExecutionValidationRequired: true})), now: () => NOW});
  if (!built.ok) throw new Error(JSON.stringify(built));
  return built.value;
}
const universalPlan: UniversalExecutionPlan = {schemaVersion: 1, id: "universal:b5", caseId: "case:b5", caseVersion: 1, producerId: "fixture", operationId: "fixture", operationType: "fixture", entityType: "noticia", resume: {schemaVersion: 1, producerId: "fixture", operationId: "fixture", operationType: "fixture", checkpoint: "review", snapshotVersion: 1, snapshotFingerprint: "sha256-v1:snapshot", requiredCapabilities: [], idempotencyKey: "b5"}, preconditions: [], effects: [{id: "effect", type: "block_operation", reason: "fixture"}], requiredCapabilities: [], rollback: [], postconditions: [{id: "post", kind: "valid", description: "valid", required: true, effectIndexes: [0]}], snapshotFingerprint: "sha256-v1:snapshot", planFingerprint: "sha256-v1:plan", idempotencyKey: "b5", generatedAt: NOW};

type Fixture = {runtime: TransactionOrchestrationRuntime; app: TransactionCheckpointApplication; root: () => string; checkpoint: () => UniversalTransactionCheckpoint; calls: {execute: string[]; persist: number[]}; mode(stepId: string, value: string): void; failPersist(call: number): void};
function fixture(transactionValue: UniversalTransactionPlan): Fixture {
  let checkpoint = createUniversalTransactionCheckpoint(transactionValue, {now: () => NOW}); let root = "sha256-v1:global0"; let persistenceFailure = 0;
  const resultModes = new Map<string, string>(); const calls = {execute: [] as string[], persist: [] as number[]};
  const reviewCase = {id: transactionValue.caseId, version: 1} as TransactionCheckpointSnapshot["reviewCase"];
  const app: TransactionCheckpointApplication = {load: () => ({reviewCase, checkpoint, globalCheckpointFingerprint: root, currentContext: transactionValue.contextBinding}), persist: async (input) => { calls.persist.push(calls.persist.length + 1); if (calls.persist.length === persistenceFailure || input.expectedGlobalCheckpointFingerprint !== root) return {persisted: false, conflict: true, reasons: ["checkpoint_conflict"]}; checkpoint = input.checkpoint; root = `sha256-v1:global${calls.persist.length}`; return {persisted: true, conflict: false, checkpointFingerprint: root}; }};
  const registry: TransactionExecutionRuntime["executorRegistry"] = {get(id) { const stepId = id.split(":")[1]; const step = transactionValue.steps.find((candidate) => candidate.stepId === stepId); if (!step || resultModes.get(stepId) === "unsupported") return undefined; const registration: RegisteredReviewExecutor["registration"] = {executorId: id, version: 1, capability: step.capability, supportedEffects: ["block_operation"], supportedEntityTypes: ["noticia"], risk: "low", canExecute: () => true, async simulate() { throw new Error("not_used"); }, async execute(_plan, _state, indexes, input) { calls.execute.push(stepId); const mode = resultModes.get(stepId) ?? "success"; const status: ExecutionResult["status"] = mode === "fail" ? "failed" : mode === "uncertain" ? "reconciliation_required" : "succeeded"; return {executorId: id, executorVersion: 1, executorManifestFingerprint: `sha256-v1:${stepId}`, capability: step.capability, status, effectIndexes: indexes, idempotencyKey: input.idempotencyKey, references: [{type: "noticia", id: `doc:${stepId}`}], error: status === "failed" ? {code: "deterministic_failure", message: "safe", retryable: false} : status === "reconciliation_required" ? {code: "timeout_uncertain", message: "safe", retryable: false} : undefined}; }, async validateExecution(plan, execution): Promise<PostExecutionValidation> { return {valid: true, planFingerprint: plan.planFingerprint, executorId: id, executionIdempotencyKey: execution.idempotencyKey, checkedPostconditionIds: ["post"], checkedEffectIndexes: [0], errors: [], warnings: [], validatedAt: NOW}; }}; return {registration, manifest: {executorId: id, version: 1, capability: step.capability, supportedEffects: ["block_operation"], supportedEntityTypes: ["noticia"], risk: "low"}, manifestFingerprint: `sha256-v1:${stepId}`}; }};
  const execution = createTransactionExecutionRuntime({executorRegistry: registry, checkpointApplication: app, prepareStep: () => ({valid: true, reasonCodes: [], plan: universalPlan, state: {fixture: true}, effectIndexes: [0]}), now: () => NOW});
  return {runtime: {execution, now: () => NOW}, app, root: () => root, checkpoint: () => checkpoint, calls, mode: (stepId, value) => resultModes.set(stepId, value), failPersist: (call) => { persistenceFailure = call; }};
}
function authorization(transactionValue: UniversalTransactionPlan, root: string, stepId: string) { const step = transactionValue.steps.find((item) => item.stepId === stepId)!; return createTransactionExecutionAuthorization({transactionFingerprint: transactionValue.transactionFingerprint, stepId, operationFingerprint: step.fingerprints.operationFingerprint, caseVersion: 1, checkpointFingerprint: root, authorizedAt: NOW, expiresAt: "2026-08-11T11:00:00.000Z", approvedByHuman: true}); }
function run(transactionValue: UniversalTransactionPlan, value: Fixture, input: Partial<Parameters<typeof orchestrateTransaction>[0]> = {}) { return orchestrateTransaction({caseId: transactionValue.caseId, transaction: transactionValue, expectedFingerprint: transactionValue.transactionFingerprint, expectedCheckpointFingerprint: value.root(), mode: "supervised_run", runtime: value.runtime, ...input}); }

async function main(): Promise<void> {
  let plan = transaction(); let value = fixture(plan); let result = await run(plan, value); equal(result.stopReason, "authorization_required"); equal(result.executions.length, 3); equal(value.calls.execute.join(","), "create,reference,validate"); equal(result.view.progress.completed, 3); check(result.view.authorizationRequired.includes("resume")); equal(result.incidents[0].kind, "authorization_required");
  result = await run(plan, value, {runtimeAuthorizations: [authorization(plan, value.root(), "resume")]}); equal(result.status, "completed"); equal(result.stopReason, "completed"); equal(value.calls.execute.length, 4); equal(result.view.progress.completed, 4); equal(result.notificationEvents[0].kind, "transaction_completed");
  result = await run(plan, value); equal(result.status, "already_completed"); equal(value.calls.execute.length, 4);
  plan = transaction({independent: true, resumeAuth: false}); value = fixture(plan); result = await run(plan, value, {mode: "safe_batch", stepIds: ["validate", "create"]}); equal(result.executions.length, 2); equal(value.calls.execute.join(","), "create,validate"); equal(result.stopReason, "max_steps_reached");
  result = await run(plan, value, {mode: "safe_batch", stepIds: []}); equal(result.stopReason, "invalid_batch");
  plan = transaction({high: true}); value = fixture(plan); result = await run(plan, value); equal(result.stopReason, "high_risk_requires_operator"); equal(value.calls.execute.length, 0);
  plan = transaction(); value = fixture(plan); value.mode("create", "uncertain"); result = await run(plan, value); equal(result.stopReason, "reconciliation_required"); equal(value.calls.execute.length, 1); equal(result.view.progress.reconciliation, 1); equal(result.incidents[0].kind, "effect_uncertain");
  plan = transaction(); value = fixture(plan); value.mode("validate", "fail"); result = await run(plan, value); equal(result.stopReason, "step_failed"); equal(value.calls.execute.length, 3); equal(result.incidents[0].kind, "step_failed"); check(!result.view.compensationRequired.length);
  plan = transaction(); value = fixture(plan); value.failPersist(2); result = await run(plan, value); equal(result.stopReason, "reconciliation_required"); equal(result.incidents[0].severity, "critical"); equal(value.calls.execute.length, 1);
  plan = transaction({resumeAuth: false}); value = fixture(plan); result = await run(plan, value, {maxSteps: 1}); equal(result.stopReason, "max_steps_reached"); equal(result.status, "paused"); equal(value.calls.execute.length, 1);
  const controller = new AbortController(); controller.abort(); result = await run(plan, value, {signal: controller.signal}); equal(result.stopReason, "cancelled"); equal(result.status, "paused");
  plan = transaction({resumeAuth: false}); value = fixture(plan); result = await run(plan, value, {mode: "single_step", stepId: "create"}); equal(result.executions.length, 1); equal(value.calls.execute[0], "create"); result = await run(plan, value, {mode: "single_step", stepId: "create"}); equal(result.stopReason, "unexpected_result");
  plan = transaction(); value = fixture(plan); result = await run(plan, value, {expectedCheckpointFingerprint: "sha256-v1:wrong"}); equal(result.stopReason, "checkpoint_conflict"); equal(value.calls.execute.length, 0); result = await run(plan, value, {expectedFingerprint: "sha256-v1:wrong"}); equal(result.stopReason, "transaction_stale");
  plan = transaction(); value = fixture(plan); value.mode("create", "unsupported"); result = await run(plan, value); equal(result.stopReason, "unsupported_step"); equal(result.incidents[0].kind, "unsupported_step");
  const view = buildTransactionOperationalView({transaction: plan, checkpoint: value.checkpoint(), now: () => NOW}); equal(view.progress.total, 4); check(view.timeline.length >= 1); const summary = buildTransactionIncidentSummary(result.incidents); equal(summary.blocking, 1); equal(policyForTransactionIncident(result.incidents[0]), "stop");
  const safe = JSON.stringify(view).toLowerCase(); check(!safe.includes('"payload"')); check(!safe.includes('"token"')); check(!safe.includes('"stack"')); check(!safe.includes('"groq"')); check(!safe.includes('"client"'));
  check(transactionOrchestratorSecurity.fullyAutonomous === false); check(transactionOrchestratorSecurity.autoCompensation === false); check(transactionOrchestratorSecurity.autoReconciliation === false); check(transactionOrchestratorSecurity.notificationsSent === false);
  check(assertions >= 55, `Se esperaban al menos 55 comprobaciones y hubo ${assertions}`);
  console.log(`AU7 B5 transaction orchestration tests: OK (${assertions} assertions; modes, supervised flow, incidents, progress, max steps, idempotency and zero real writes)`);
}
main();
