import assert from "node:assert/strict";
import {adaptGlobalResolutionPlanToUniversal, buildGlobalResolutionPlan, createGlobalResolutionCapabilityRegistry, pilotCapabilityRegistry, simulateGlobalResolutionPlan} from "../_laboratorio/laboratorio-ia/src/review/globalResolution";
import {topologicalSortResolutionGraph} from "../_laboratorio/laboratorio-ia/src/review/resolutionGraph";
import {buildResumeContract, type UniversalReviewInput} from "../_laboratorio/laboratorio-ia/src/review/universal";
import type {ReviewCase} from "../_laboratorio/laboratorio-ia/src/review/types";

const now = "2026-07-27T15:00:00.000Z";
function reviewCase(): ReviewCase { return {schemaVersion: 1, id: "case:simulation", dedupeKey: "case:simulation", module: "external.news", title: "Simulation", status: "open", priority: "high", subject: {type: "external_news", id: "news:1"}, issues: [{id: "issue:fighter", kind: "missing_entity", valueKind: "fighter", fieldPath: "fighter", label: "Fighter", message: "Missing", required: true, blocking: true}], resolutions: [{type: "create_entity", issueId: "issue:fighter", entityType: "fighter", draft: {name: "Ada Fighter"}}], context: {producer: "external_news", operation: "create_draft", payloadSnapshot: {id: "news:1"}}, createdAt: now, updatedAt: now, version: 1, resumeAttempts: 0}; }
const preparedDraft = {entityType: "fighter", name: "Ada Fighter", identityKey: "fighter:ada-fighter", disciplineId: "discipline:boxing", organizationIds: ["organization:test"], sourceEvidence: [{source: "test"}]};
function plan(existingEntityId?: string, policy = {}) { return buildGlobalResolutionPlan({reviewCase: reviewCase(), preparedEntities: [{issueId: "issue:fighter", entityType: "fighter", draft: preparedDraft, identityKey: "fighter:ada-fighter", valid: true, existingEntityId, evidence: [{id: "e", kind: "source", source: "test", confidence: .98, limitations: []}]}], evidence: [{issueId: "issue:fighter", id: "e", kind: "source", source: "test", confidence: .98, limitations: []}], finalEntityType: "noticia", policy, now: () => now}); }
function context(candidates: Array<{id: string; name: string; disciplineId: string; organizationId: string}> = []) { return {reviewCase: reviewCase(), preparedEntities: [{issueId: "issue:fighter", entityType: "fighter" as const, draft: preparedDraft}], fighterCandidates: candidates, newsPayload: {titulo: "Una noticia válida", contenido: "Contenido válido", fuenteUrl: "https://example.test/news", fechaPublicacion: now, disciplina: "discipline:boxing", organizacionRelacionada: "", eventoRelacionado: "", luchadoresRelacionados: [], imagenPrincipal: "https://example.test/image.jpg"}, producerContracts: [{producer: "external_news", supportsSimulation: true, allowsProjectedReferences: true}]}; }
function universalInput(): UniversalReviewInput { const snapshot = {title: "Simulation"}; return {schemaVersion: 1, logicalKey: "case:simulation", producerId: "external_news", operationId: "create_draft", operationType: "create", module: "external.news", entity: {type: "noticia", id: "news:1"}, issueFamily: "missing_reference", issueCode: "missing_fighter", priority: "high", title: "Simulation", snapshot, issues: [], evidence: [], constraints: [], resume: buildResumeContract({producerId: "external_news", operationId: "create_draft", operationType: "create", checkpoint: "review", snapshotVersion: 1, snapshot, requiredCapabilities: [], idempotencyKey: "case:simulation"})}; }
function main(): void {
  const built = plan(); assert.equal(built.ok, true); if (!built.ok) return; const original = structuredClone(built.plan);
  const simulated = simulateGlobalResolutionPlan(built.plan, context());
  assert.equal(simulated.simulatable, true); assert.equal(simulated.executable, false); assert.equal(simulated.state, "simulatable"); assert.equal(simulated.projectedEffects[0].provisional, true); assert.equal(simulated.projectedResume?.conceptual, true); assert.equal(simulated.nodeResults.every((node) => typeof node.input.operationId === "string" && Array.isArray(node.evidence)), true); assert.equal(simulated.nodeResults.some((node) => node.projectedEffect?.provisional === true), true); assert.deepEqual(pilotCapabilityRegistry.list().filter((capability) => capability.support === "executable").map((capability) => capability.id), ["create:luchador", "replace_reference:noticia:luchador", "resume:external_news"]); assert.deepEqual(built.plan, original);
  const repeated = simulateGlobalResolutionPlan(built.plan, context()); assert.deepEqual(repeated, simulated);
  const bridge = adaptGlobalResolutionPlanToUniversal(built.plan); assert.equal(bridge.executionAllowed, false); assert.equal(bridge.sourcePlanId, built.plan.id); assert.equal(bridge.sourceIdempotencyKey, built.plan.idempotencyKey); assert.deepEqual(bridge.orderedOperationIds, topologicalSortResolutionGraph(built.plan.graph).nodeIds); assert.equal(bridge.effects.every((effect) => built.plan.operations.some((operation) => operation.id === effect.id)), true);
  const bridgeCandidate = adaptGlobalResolutionPlanToUniversal(built.plan, {reviewInput: universalInput(), now: () => now}); assert.equal(bridgeCandidate.executionAllowed, false); assert.ok(bridgeCandidate.universalPlan); assert.equal(bridgeCandidate.universalPlan.effects.length, bridgeCandidate.effects.length);

  const reusePlan = plan("fighter:existing"); assert.equal(reusePlan.ok, true); if (reusePlan.ok) { const reuse = simulateGlobalResolutionPlan(reusePlan.plan, context([{id: "fighter:existing", name: "Ada Fighter", disciplineId: "discipline:boxing", organizationId: "organization:test"}])); const create = simulateGlobalResolutionPlan(reusePlan.plan, context([{id: "fighter:other", name: "Other Fighter", disciplineId: "discipline:mma", organizationId: "organization:other"}])); assert.equal(reuse.nodeResults.some((node) => node.decision === "reuse_candidate"), true); assert.notDeepEqual(reuse, create); }
  const candidate = {id: "fighter:existing", name: "Ada Fighter", disciplineId: "discipline:boxing", organizationId: "organization:test"}; const irrelevant = {id: "fighter:other", name: "Other Fighter", disciplineId: "discipline:mma", organizationId: "organization:other"}; assert.deepEqual(simulateGlobalResolutionPlan(built.plan, context([candidate, irrelevant])), simulateGlobalResolutionPlan(built.plan, context([irrelevant, candidate])));
  const alternativePolicyPlan = plan(undefined, {allowSkippedDependencyForResume: true}); assert.equal(alternativePolicyPlan.ok, true); if (alternativePolicyPlan.ok) assert.notEqual(simulateGlobalResolutionPlan(alternativePolicyPlan.plan, context()).intentFingerprint, simulated.intentFingerprint);
  const ambiguous = simulateGlobalResolutionPlan(built.plan, context([{id: "a", name: "Ada Fighter", disciplineId: "discipline:boxing", organizationId: "organization:test"}, {id: "b", name: "Ada Fighter", disciplineId: "discipline:boxing", organizationId: "organization:test"}])); assert.equal(ambiguous.blockers.some((blocker) => blocker.code === "ambiguous_entity_candidate"), true);
  const missingDiscipline = simulateGlobalResolutionPlan(built.plan, {...context(), preparedEntities: [{issueId: "issue:fighter", entityType: "fighter", draft: {...preparedDraft, disciplineId: ""}}]}); assert.equal(missingDiscipline.blockers.some((blocker) => blocker.code === "schema_requirement_missing"), true);
  const missingOrganization = simulateGlobalResolutionPlan(built.plan, {...context(), preparedEntities: [{issueId: "issue:fighter", entityType: "fighter", draft: {...preparedDraft, organizationIds: []}}]}); assert.equal(missingOrganization.blockers.some((blocker) => blocker.code === "schema_requirement_missing"), true);
  const unsafeIdentity = simulateGlobalResolutionPlan(built.plan, {...context(), preparedEntities: [{issueId: "issue:fighter", entityType: "fighter", draft: {...preparedDraft, identityKey: "fighter:not-ada"}}]}); assert.equal(unsafeIdentity.blockers.some((blocker) => blocker.code === "schema_requirement_missing"), true);
  const missingCapability = simulateGlobalResolutionPlan(built.plan, {...context(), capabilityRegistry: createGlobalResolutionCapabilityRegistry()}); assert.equal(missingCapability.missingCapabilities.length > 0, true);
  const disposableRegistry = createGlobalResolutionCapabilityRegistry(); const unregisterCapability = disposableRegistry.register({id: "test:temporary", support: "contract_only", operationKinds: ["validate_entity"], description: "Temporary"}); assert.ok(disposableRegistry.get("test:temporary")); unregisterCapability(); assert.equal(disposableRegistry.get("test:temporary"), undefined);
  const mismatchRegistry = createGlobalResolutionCapabilityRegistry(pilotCapabilityRegistry.list().map((capability) => capability.id === "find:luchador" ? {...capability, operationKinds: ["create_entity"]} : capability)); const mismatch = simulateGlobalResolutionPlan(built.plan, {...context(), capabilityRegistry: mismatchRegistry}); assert.equal(mismatch.blockers.some((blocker) => blocker.code === "unsupported_operation"), true);
  const contractOnly = createGlobalResolutionCapabilityRegistry(pilotCapabilityRegistry.list().map((capability) => capability.id === "resume:external_news" ? {...capability, support: "contract_only" as const} : capability)); const contractResult = simulateGlobalResolutionPlan(built.plan, {...context(), capabilityRegistry: contractOnly}); assert.equal(contractResult.nodeResults.some((node) => node.status === "contract_only"), true);
  const altered = {...built.plan, fingerprint: "sha256-v1:altered"}; const tampered = simulateGlobalResolutionPlan(altered, context()); assert.equal(tampered.blockers.some((blocker) => blocker.code === "invalid_planning_input"), true);
  console.log("AU2 global resolution simulation tests: OK");
}
main();
