import {useEffect, useState, type ReactElement} from "react";
import {applyAutonomousInvestigation, hasInvestigationSource, previewAutonomousInvestigation, subscribeInvestigationSources, type AutonomousInvestigationResult} from "..";

export default function AutonomousInvestigationPanel({caseId, editable, investigable}: {caseId: string; editable: boolean; investigable: boolean}): ReactElement | null {
  const [available, setAvailable] = useState(() => hasInvestigationSource("local_case") || hasInvestigationSource("sanity_read"));
  const [running, setRunning] = useState(false);
  const [result, setResult] = useState<AutonomousInvestigationResult | null>(null);
  const [open, setOpen] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => subscribeInvestigationSources(() => setAvailable(hasInvestigationSource("local_case") || hasInvestigationSource("sanity_read"))), []);
  async function preview(): Promise<void> { setRunning(true); setMessage(""); try { const next = await previewAutonomousInvestigation(caseId); setResult(next); setOpen(true); setMessage(next.investigatedIssueCount ? "Investigación de solo lectura completada." : "No hay incidencias investigables pendientes."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo investigar."); } finally { setRunning(false); } }
  async function apply(): Promise<void> { if (!window.confirm("Se aplicarán solo las conclusiones validadas al store. No se crearán entidades ni borradores. ¿Continuar?")) return; setRunning(true); try { const next = await applyAutonomousInvestigation(caseId); setResult(next); setMessage(`${next.appliedIssueIds.length} conclusión(es) aplicada(s) al store. El preview puede regenerarse con el nuevo estado.`); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudieron aplicar las conclusiones."); } finally { setRunning(false); } }
  if (!editable || !investigable || !available) return null;
  return <section className="review-subsection investigation-panel" aria-label="Investigación editorial autónoma"><div className="review-row review-row-wrap"><div><p className="review-kicker">INVESTIGACIÓN · SOLO LECTURA</p><h4 className="review-subtitle">Motor autónomo de investigación editorial</h4></div><button className="review-button" type="button" disabled={running} onClick={preview}>{running ? "Investigando…" : "Investigar y resolver"}</button></div><p aria-live="polite" role="status">{message}</p>{result ? <><div className="review-badges"><span className="review-badge">EVIDENCIA INTERNA</span><span className="review-badge">SANITY SOLO LECTURA</span>{result.appliedIssueIds.length ? <span className="review-badge">APLICADO AL STORE</span> : null}</div><button className="review-disclosure" type="button" aria-expanded={open} aria-controls={`investigation-${caseId}`} onClick={() => setOpen((value) => !value)}>{open ? "Ocultar investigación" : "Ver plan y conclusiones"}</button>{open ? <div id={`investigation-${caseId}`} className="investigation-results"><p>Fuentes: {result.sourcesUsed.join(", ") || "solo evidencia disponible"}</p>{result.conclusions.map((conclusion) => <details key={conclusion.issueId}><summary>{conclusion.status === "resolved_existing_entity" ? "ENTIDAD EXISTENTE" : conclusion.status === "prepared_new_entity" ? "ENTIDAD PREPARADA" : conclusion.status === "conflict" ? "CONFLICTO" : conclusion.status === "needs_more_evidence" ? "FALTA EVIDENCIA" : "INVESTIGACIÓN"} · {(conclusion.confidence * 100).toFixed(0)}%</summary><p>{conclusion.reasoningSummary}</p><p>Evidencias verificables: {conclusion.evidence.length}</p>{conclusion.warnings.map((warning) => <p key={warning} className="review-readonly-message">{warning}</p>)}</details>)}{!result.dryRun ? null : <button className="review-button" type="button" disabled={running || !result.conclusions.some((item) => item.validation.valid && !["needs_more_evidence", "conflict", "rejected"].includes(item.status))} onClick={apply}>Aplicar conclusiones seguras</button>}</div> : null}</> : null}</section>;
}
