import {useState, type ReactElement} from "react";
import type {ReviewCase} from "../../types";
import {executePreparedEntityMaterialization, previewPreparedEntityMaterialization, type PreparedEntityMaterializationPreview, type PreparedEntityMaterializationResult} from "..";
export default function PreparedEntityMaterializationPanel({reviewCase}: {reviewCase: ReviewCase}): ReactElement | null {
  const [preview, setPreview] = useState<PreparedEntityMaterializationPreview | null>(null); const [result, setResult] = useState<PreparedEntityMaterializationResult | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const prepared = reviewCase.resolutions.filter((resolution) => resolution.type === "create_entity"); if (!prepared.length) return null;
  async function validate() { setBusy(true); try { const next = await previewPreparedEntityMaterialization(reviewCase.id); setPreview(next); setMessage(next.canExecute ? "Entidades validadas y duplicados comprobados." : "La materialización está bloqueada; revisa los motivos."); } catch (error) { setMessage(error instanceof Error ? error.message : "Fallo de validación."); } finally { setBusy(false); } }
  async function execute() { if (!preview?.canExecute) return; const names = preview.items.map((item) => item.name).filter(Boolean).join(", "); if (!window.confirm(`Se materializarán ${preview.entityCount} entidades reales: ${names}. Se crearán borradores en Sanity; no se publicará ni se reanudará automáticamente. ¿Continuar?`)) return; setBusy(true); try { const next = await executePreparedEntityMaterialization(reviewCase.id, {confirmed: true, expectedVersion: reviewCase.version}); setResult(next); setMessage(next.canResume ? "Entidades materializadas. La preview está lista para usar la reanudación manual existente." : `Materialización terminada: ${next.status}.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Falló la materialización."); } finally { setBusy(false); } }
  return <section className="review-subsection investigation-panel" aria-label="Materialización de entidades preparadas"><p className="review-kicker">CREACIÓN CONTROLADA · NO PUBLICA</p><h4 className="review-subtitle">Entidades preparadas ({prepared.length})</h4><button className="review-button" type="button" disabled={busy} onClick={validate}>{busy ? "Validando…" : "Validar y crear entidades preparadas"}</button><p role="status" aria-live="polite">{message}</p>{preview ? <div className="investigation-results">{preview.items.map((item) => <details key={item.issueId} open><summary>{item.name ?? item.issueId} · {item.status}</summary>{item.sanityPayload ? <pre className="review-json">{JSON.stringify(item.sanityPayload, null, 2)}</pre> : null}<p>Campos internos omitidos: {item.omittedFields.join(", ") || "ninguno"}</p>{item.errors.map((error) => <p key={error} className="review-readonly-message">{error}</p>)}</details>)}<button className="review-button" type="button" disabled={busy || !preview.canExecute} onClick={execute}>Confirmar creación real</button></div> : null}{result ? <div className="investigation-results">{result.items.map((item) => <p key={item.issueId}>{item.issueId}: {item.status}{item.entityId ? ` · ${item.entityId}` : ""}{item.error ? ` · ${item.error.message}` : ""}</p>)}</div> : null}</section>;
}
