import {createClient} from "@sanity/client"
import {NextResponse} from "next/server"
export const runtime="nodejs"; export const dynamic="force-dynamic"
type DK="kickboxing"|"muay_thai"; type G="masculino"|"femenino"|"mixto"; type A="senior"|"veterano"|"junior"|"juvenil"|"cadete"|"infantil"|"escolar"|"otro"; type B="hasta"|"mas_de"|"exacto"
type S={label?:string;discipline?:DK|string;gender?:G|string;ageGroup?:A|string;modality?:string;eventCode?:string;weightLabel?:string;limitKg?:number}; type R={confirm?:boolean;categories?:S[]}
type Ref={_id:string;nombre?:string}; type Cat=Ref&{limitePeso?:number;unidad?:"kg"|"lb";tipoLimite?:B;modalidad?:string;grupoEdad?:A;sexo?:G;disciplina?:{_ref?:string}|null}
type C={sourceLabel:string;disciplineKey:DK;discipline:Ref;gender:G;ageGroup:A;modality:string;boundary:B;limitKg:number;nombre:string;slug:string}
const projectId=process.env.NEXT_PUBLIC_SANITY_PROJECT_ID||process.env.SANITY_STUDIO_PROJECT_ID; const dataset=process.env.NEXT_PUBLIC_SANITY_DATASET||process.env.SANITY_STUDIO_DATASET||"production"; const apiVersion=process.env.NEXT_PUBLIC_SANITY_API_VERSION||"2025-03-01"; const token=process.env.SANITY_API_WRITE_TOKEN
const client=createClient({projectId:projectId||"",dataset,apiVersion,token,useCdn:false,perspective:"raw"}); const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Cache-Control":"no-store"}; function cors<T>(r:NextResponse<T>){for(const[k,v]of Object.entries(H))r.headers.set(k,v);return r}
function t(v:unknown){return typeof v==="string"?v.trim():""} function sd(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"")} function n(v:string){return sd(v).toLowerCase().replace(/[–—−]/g,"-").replace(/[^a-z0-9+.,-]+/g," ").replace(/\s+/g," ").trim()} function slug(v:string){return sd(v).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,96)} function base(v:string){return v.replace(/^drafts\./,"")} function ref(id:string){return{_type:"reference" as const,_ref:base(id)}}
function dk(v:string):DK|null{const x=n(v);if(x.includes("muay")||x.includes("thai"))return"muay_thai";if(x.includes("kick")||x==="kb")return"kickboxing";return null} function gen(v:string):G{const x=n(v);if(/\b(fem|female|women|woman|mujer|femenin)/.test(x))return"femenino";if(/\b(masc|male|men|man|hombre|masculin)/.test(x))return"masculino";return"mixto"} function age(v:string):A{const x=n(v);if(x.includes("veteran"))return"veterano";if(x.includes("senior"))return"senior";if(x.includes("junior"))return"junior";if(x.includes("juvenil"))return"juvenil";if(x.includes("cadete"))return"cadete";if(x.includes("infantil"))return"infantil";if(x.includes("escolar"))return"escolar";return"otro"}
function mod(v:string){const x=n(v);if(x.includes("k-1l")||x.includes("k1 light")||x.includes("k-1 light"))return"K-1 Light";if(x.includes("kick light")||/\bkl\b/.test(x))return"Kick Light";if(x.includes("light contact")||/\blc\b/.test(x))return"Light Contact";if(x.includes("point fighting")||/\bpf\b/.test(x))return"Point Fighting";if(x.includes("creative forms")||/\bcf\b/.test(x))return"Creative Forms";if(x.includes("muay"))return"Muay Thai";return t(v)||"General"}
function weight(i:S):{limitKg:number;boundary:B}|null{const raw=n([t(i.weightLabel),t(i.label)].filter(Boolean).join(" "));const value=(m:RegExpMatchArray|null)=>m?Number(m[1].replace(",",".")):null;if(typeof i.limitKg==="number"&&Number.isFinite(i.limitKg))return{limitKg:i.limitKg,boundary:raw.includes("+")||raw.includes("mas de")?"mas_de":"hasta"};const p=value(raw.match(/(?:^|\s)\+(\d{2,3}(?:[.,]\d+)?)\s*(?:kg)?/));if(p!==null)return{limitKg:p,boundary:"mas_de"};const m=value(raw.match(/(?:^|\s)-(\d{2,3}(?:[.,]\d+)?)\s*(?:kg)?/));if(m!==null)return{limitKg:m,boundary:"hasta"};const u=value(raw.match(/(?:hasta|menos de|under|<)\s*(\d{2,3}(?:[.,]\d+)?)\s*(?:kg)?/));if(u!==null)return{limitKg:u,boundary:"hasta"};const o=value(raw.match(/(?:mas de|over|>)\s*(\d{2,3}(?:[.,]\d+)?)\s*(?:kg)?/));if(o!==null)return{limitKg:o,boundary:"mas_de"};const b=value(raw.match(/(?:^|\s)(\d{2,3}(?:[.,]\d+)?)\s*kg(?:\s|$)/));return b!==null?{limitKg:b,boundary:"exacto"}:null}
function fmt(v:number){return Number.isInteger(v)?String(v):String(v).replace(".",",")} function bl(v:B){return v==="mas_de"?"Más de":v==="exacto"?"Peso":"Hasta"} function findD(k:DK,ds:Ref[]){const a=k==="muay_thai"?["muay thai","muaythai"]:["kickboxing","kick boxing","kick-boxing"];return ds.find(d=>a.includes(n(t(d.nombre))))||null}
function build(i:S,ds:Ref[]):C|null{const sourceLabel=t(i.label)||[t(i.modality),t(i.ageGroup),t(i.gender),t(i.weightLabel)].filter(Boolean).join(" · ");const key=dk(t(i.discipline));const w=weight(i);if(!sourceLabel||!key||!w||w.limitKg<20||w.limitKg>200)return null;const discipline=findD(key,ds);if(!discipline)return null;const gender=gen(t(i.gender)||sourceLabel),ageGroup=age(t(i.ageGroup)||sourceLabel),modality=mod(t(i.modality)||t(i.eventCode)||sourceLabel),nombre=`${modality} · ${ageGroup} · ${gender} · ${bl(w.boundary)} ${fmt(w.limitKg)} kg`;return{sourceLabel,disciplineKey:key,discipline,gender,ageGroup,modality,boundary:w.boundary,limitKg:w.limitKg,nombre,slug:slug(`${nombre}-${key}`)}}
function id(c:C){return[base(c.discipline._id),n(c.modality),c.ageGroup,c.gender,c.boundary,c.limitKg.toFixed(3)].join("::")} function docId(c:Cat){return[base(t(c.disciplina?._ref)),n(t(c.modalidad)||t(c.nombre)),c.grupoEdad||"otro",c.sexo||"mixto",c.tipoLimite||(/mas de|\+/.test(n(t(c.nombre)))?"mas_de":"hasta"),(c.limitePeso??0).toFixed(3)].join("::")}
function env(){if(!projectId)return"Falta projectId de Sanity.";if(!dataset)return"Falta dataset de Sanity.";if(!token)return"Falta SANITY_API_WRITE_TOKEN.";return null}
export async function OPTIONS(){return cors(new NextResponse(null,{status:204}))} export async function POST(request:Request){try{const e=env();if(e)return cors(NextResponse.json({ok:false,error:e},{status:500}));let body:R;try{body=await request.json() as R}catch{return cors(NextResponse.json({ok:false,error:"El body no es un JSON válido."},{status:400}))}if(!body.confirm)return cors(NextResponse.json({ok:false,error:"Falta confirmación explícita para crear categorías FEKM."},{status:400}));const inputs=Array.isArray(body.categories)?body.categories:[];if(!inputs.length)return cors(NextResponse.json({ok:false,error:"No se recibieron categorías FEKM."},{status:400}));const[disciplines,existing]=await Promise.all([client.fetch<Ref[]>(`*[_type == "disciplina"]{_id,nombre}`,{}, {perspective:"raw"}),client.fetch<Cat[]>(`*[_type == "categoriaPeso"]{_id,nombre,limitePeso,unidad,tipoLimite,modalidad,grupoEdad,sexo,disciplina}`,{}, {perspective:"raw"})]);const created:any[]=[],skipped:any[]=[],failed:any[]=[],seen=new Set<string>();for(const input of inputs){const c=build(input,disciplines);const sourceLabel=t(input.label);if(!c){skipped.push({sourceLabel,reason:"categoria_o_disciplina_no_normalizable"});continue}const key=id(c);if(seen.has(key)){skipped.push({sourceLabel,reason:"duplicada_en_la_peticion"});continue}seen.add(key);if(existing.some(d=>docId(d)===key||n(t(d.nombre))===n(c.nombre))){skipped.push({sourceLabel,reason:"categoria_ya_existente"});continue}const draftId=`drafts.fekm-category-${c.slug}`;try{await client.createIfNotExists({_id:draftId,_type:"categoriaPeso",nombre:c.nombre,slug:{_type:"slug",current:c.slug},disciplina:ref(c.discipline._id),limitePeso:c.limitKg,unidad:"kg",tipoLimite:c.boundary,modalidad:c.modality,grupoEdad:c.ageGroup,sexo:c.gender,descripcion:`Categoría ${c.modality}, ${c.ageGroup}, ${c.gender}, ${bl(c.boundary).toLowerCase()} ${fmt(c.limitKg)} kg. Normalizada desde documentación oficial FEKM.`});created.push({sourceLabel,nombre:c.nombre,draftId,discipline:c.discipline.nombre||c.disciplineKey,modality:c.modality,ageGroup:c.ageGroup,gender:c.gender,boundary:c.boundary,limitKg:c.limitKg});existing.push({_id:draftId,nombre:c.nombre,limitePeso:c.limitKg,unidad:"kg",tipoLimite:c.boundary,modalidad:c.modality,grupoEdad:c.ageGroup,sexo:c.gender,disciplina:{_ref:base(c.discipline._id)}})}catch(error){failed.push({sourceLabel,error:error instanceof Error?error.message:"Error desconocido creando la categoría."})}}
return cors(NextResponse.json({ok:failed.length===0,source:"fekm",summary:{received:inputs.length,created:created.length,skipped:skipped.length,failed:failed.length},created,skipped,failed}))}catch(error){console.error("Error creando categorías FEKM:",error);return cors(NextResponse.json({ok:false,error:error instanceof Error?error.message:"Error desconocido creando categorías FEKM."},{status:500}))}}
